#!/usr/bin/csh -f

setenv KIT_PATH /p/hdk/cad/kits_10nm/10nm_14.2.2
setenv compName sbendpoint
setenv SIP_LIB_TYPE  e05
setenv SIP_LIB_VERSION 1

/p/sip/utils/bin/runATPG \
   ../../../syn/syn_1274/sbendpoint/rdt/outputs/sbendpoint_atpg.final.v \
   ../../../syn/syn_1274/sbendpoint/rdt/outputs/sbendpoint_atpg.final.spf -f \
   -lib /p/hdk/cad/stdcells/e05/14ww45.3_e05_d.0_cnlgt/mentor/ln/${SIP_LIB_TYPE}_ln_core.atpglib \
   -lib /p/hdk/cad/stdcells/e05/14ww45.3_e05_d.0_cnlgt/mentor/primitives/primitive.atpglib \
   -lib /p/hdk/cad/stdcells/e05/14ww45.3_e05_d.0_cnlgt/mentor/primitives/udp.atpglib

