#!/usr/bin/csh -f

setenv KIT_PATH /p/kits/intel/p1273/p1273_0.8.0
setenv compName sbebase
setenv SIP_LIB_TYPE  d04   
setenv SIP_LIB_VERSION 1

/p/sip/utils/bin/runATPG \
   ../../../syn/syn_1273/sbebase/rdt/outputs/sbebase_atpg.final.v \
   ../../../syn/syn_1273/sbebase/rdt/outputs/sbebase_atpg.final.spf -f \
   -lib ${KIT_PATH}/stdcells/${SIP_LIB_TYPE}/default/latest/mentor/wn/${SIP_LIB_TYPE}_wn_core.atpglib \
   -lib ${KIT_PATH}/stdcells/${SIP_LIB_TYPE}/default/latest/mentor/primitives/primitive.atpglib \
   -lib ${KIT_PATH}/stdcells/${SIP_LIB_TYPE}/default/latest/mentor/primitives/udp.atpglib

