#!/bin/tcsh -f
# name: runConfig
# date: <DATE>
# auth: <AUTHOR>
# desc: Create top level netlist for this configuration
# Status codes: 0=pass, 1-49=fail, 50=TBD, 60=N/A

setenv SIP_QA_MODULE "Configuration"

#########################################
# Define variables
#########################################
set SIP_TOOL_NAME=`echo $0 | sed -e 's/.*\///'`
setenv SIP_PWD $cwd
if (! $?SIP_VARIATION) then
  setenv SIP_VARIATION unknown
endif

set flag=0
#####################################################
# UNIX Environment setup
#####################################################
# No setup needed

#####################################################
# Run commands
#####################################################
set status=50   # Default status = TBD
# <COMMANDS>
set exitStatus=$status

#####################################################
# Verification
#####################################################
if ($exitStatus == 50) then
  echo "Note: $SIP_QA_MODULE TBD.  ($SIP_TOOL_NAME)"
else if ($exitStatus == 60) then
  echo "Note: $SIP_QA_MODULE N/A.  ($SIP_TOOL_NAME)"
else if ($exitStatus) then
  echo "Error: $SIP_QA_MODULE failed.  ($SIP_TOOL_NAME)"
else 
  echo "Note: $SIP_QA_MODULE passed.  ($SIP_TOOL_NAME)"
endif

exit $exitStatus
