#!/bin/tcsh -f
# name: runDOA
# date: <DATE>
# auth: <AUTHOR>
# desc: Run sign-of-life VCS simulation
# Status codes: 0=pass, 1-49=fail, 50=TBD, 60=N/A

setenv SIP_QA_MODULE "DOA Simulation"

#########################################
# Define variables
#########################################
set SIP_TOOL_NAME=`echo $0 | sed -e 's/.*\///'`
setenv SIP_PWD $cwd

set flag=0
#####################################################
# UNIX Environment setup
#####################################################
cd ..
if (! $?SIP_NO_SETUP) then
#  source setup -ft
endif

#####################################################
# Dependent module
#####################################################
#if ($?SIP_DO_DEPENDENT_MODULE) then
#  cd qa
#  source ./runConfig
#  if ($status == 1) then
#    echo "Error: Terminated $SIP_QA_MODULE because dependent module failed"
#    exit 1
#  endif
#  cd ..
#endif

#####################################################
# Run commands
#####################################################
set status=50   # Default status = TBD
# <COMMANDS>
set exitStatus=$status

#####################################################
# Report
#####################################################
if ($?SIP_CREATE_REPORT) then
endif

#####################################################
# Verification
#####################################################
if ($exitStatus == 50) then
  echo "Note: $SIP_QA_MODULE TBD.  ($SIP_TOOL_NAME)"
else if ($exitStatus == 60) then
  echo "Note: $SIP_QA_MODULE N/A.  ($SIP_TOOL_NAME)"
else if ($exitStatus) then
  echo "Error: $SIP_QA_MODULE failed.  ($SIP_TOOL_NAME)"
else
  echo "Note: $SIP_QA_MODULE passed.  ($SIP_TOOL_NAME)"
endif

exit $exitStatus
