#!/bin/tcsh -f
# name: runSpyglass
# date: 31-Oct-11
# auth: N M Pavan
# desc: Run Spyglass
# Status codes: 0=pass, 1-49=fail, 50=TBD, 60=N/A

setenv SIP_QA_MODULE "Spyglass"

#########################################
# Define variables
#########################################
set SIP_TOOL_NAME=`echo $0 | sed -e 's/.*\///'`
setenv SIP_PWD $cwd
set flag=0
#####################################################
# UNIX Environment setup
#####################################################
cd ..
if (! $?SIP_NO_SETUP) then
 source setup -ft
endif

#####################################################
# Run commands
#####################################################
set status=50   # Default status = TBD
cd ${IP_ROOT}/tools/spyglass
#source setup_spyglass.sh
/p/com/eda/intel/siputils/prod/bin/runGenCmd 'spyglass -f ./stap.spp' -setup none -pc '^SpyGlass\s+Exit\s+Code\s+0.*'

#spyglass -f ./stap.spp
set exitStatus=$status

#####################################################
# Report
#####################################################
if ($?SIP_CREATE_REPORT) then
endif

#####################################################
# Verification
#####################################################
setenv SIP_QA_MODULE "Spyglass"
if ($exitStatus == 50) then
  echo "Note: $SIP_QA_MODULE TBD.  ($SIP_TOOL_NAME)"
else if ($exitStatus == 60) then
  echo "Note: $SIP_QA_MODULE N/A.  ($SIP_TOOL_NAME)"
else if ($exitStatus) then
  echo "Error: $SIP_QA_MODULE failed.  ($SIP_TOOL_NAME)"
else
  echo "Note: $SIP_QA_MODULE passed.  ($SIP_TOOL_NAME)"
endif

exit $exitStatus
