//==================================================
// This file contains the Excluded objects
// Generated By User: araghuw
// Format Version: 2
// Date: Wed Apr 29 04:13:14 2020
// ExclMode: default
//==================================================
CHECKSUM: "1365687329 4580094"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_m_addr_space
	coveritem "_m_addr_space"
		bins "auto_IO", "auto_CFG", "auto_MSG"
CHECKSUM: "2097976224 742384533"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_ism_agent_arcs_actReq_crdReq
CHECKSUM: "231818029 511577736"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_mlength
	coveritem "_mlength"
		bins "val_002", "val_003", "val_005", "val_006", "val_007", "val_009", "val_00a", "val_00b", "val_00d", "val_00e", "val_00f"
CHECKSUM: "2509636393 526311350"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_tdec_on_fabric_ism
CHECKSUM: "2641129256 2560479515"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_ism_fabric_arcs_actReq_crdReq
CHECKSUM: "2786003895 1414174085"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_mcmd
	coveritem "_mcmd"
		bins "auto_MRd64", "auto_NPMWr32", "auto_NPMWr64", "auto_IORd", "auto_IOWr", "auto_CfgRd0", "auto_CfgWr0", "auto_CfgRd1", "auto_CfgWr1", "auto_FAdd32", "auto_FAdd64", "auto_Swap32", "auto_Swap64", "auto_CAS32", "auto_CAS64", "auto_Msg0", "auto_Msg1", "auto_Msg2", "auto_Msg3", "auto_Msg4", "auto_Msg5", "auto_Msg6", "auto_Msg7", "auto_MsgD0", "auto_MsgD1", "auto_MsgD2", "auto_MsgD3", "auto_MsgD4", "auto_MsgD5", "auto_MsgD6", "auto_MsgD7"
CHECKSUM: "2824926392 3483975663"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_mfbe
	coveritem "_mfbe"
		bins auto[2]-auto[14]
CHECKSUM: "3030394546 1118548141"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_req_rtype
	coveritem "_req_rtype"
		bins "auto_NONPOSTED"
CHECKSUM: "3073020835 3821105134"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_crd_data
	coveritem "_crd_data"
		bins "val_3"
CHECKSUM: "308915848 3118033229"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_tdec_on_agent_ism
CHECKSUM: "3304024016 764932897"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_crd_rtype
	coveritem "_crd_rtype"
		bins "auto_COMPLETION"
CHECKSUM: "3336285476 2207164062"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_mlbe
	coveritem "_mlbe"
		bins auto[5]-auto[7], auto[9]-auto[11], auto[13]-auto[14]
CHECKSUM: "371220700 2689722792"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_crd_put_on_fabric_ism
	coveritem "_crd_put_on_fabric_ism"
		bins "val_FAB_ACT_REQ"
CHECKSUM: "3901112083 1170175946"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_gnt_type
	coveritem "_gnt_type"
		bins "auto_GNT_SHOW"
CHECKSUM: "3928165627 1221898062"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_tdec_b2b
CHECKSUM: "994532845 62958369"
covergroup hqm_tb_top.hqm_test_island.hqm_global_ti.iosf_fabric_VC.genblk0.primary_quickcov::cg_req_dlength
	coveritem "_req_dlength"
		bins "val_002", "val_003", "val_005", "val_006", "val_007", "val_009", "val_00a", "val_00b", "val_00d", "val_00e", "val_00f"
