#!/usr/intel/bin/tcsh
cd $MODEL_ROOT/

#Set up the environment and source appropriate environment before running the below commands
simbuild -dut dfxsecure_plugin -1c -CUST ADL -1c- -s all +s sgcdc_build
simbuild -dut dfxsecure_plugin -1c -CUST ADL -1c- -s all +s sgcdc_test -sgcdc_test "-t spyglasscdc/dfxsecure_plugin/"

cd $MODEL_ROOT/

#\cp -r ace/dfxsecure_plugin_hdl_bkp.udf ace/dfxsecure_plugin_hdl.udf

##Simbuild command to run SGCDC Gui is below, to check Errors. You need to run the flow once again and uncomment the below line to open GUI 
#simbuild -dut dfxsecure_plugin -1c -CUST ADL -1c- -s all +s sgcdc_test -sgcdc_test "-t spyglasscdc/dfxsecure_plugin/ -spyglass_debug"

#If not possible to open GUI in xterm, to open GUI in Konsole, use the following command,
#Osetup spyglass
#spyglass -project <prj_name.prj> &

