#!/bin/csh -f

#rm -rf pwa

\cp verif/tb/include/configs/use1/DfxSecurePlugin_TbDefines.svh              verif/tb/DfxSecurePlugin_TbDefines.svh
\cp verif/tb/include/configs/use1/DFXSECURE_dfxsecureplugin_param_overide.vh verif/tb/include/DFXSECURE_dfxsecureplugin_param_overide.vh
\cp verif/tb/include/configs/use1/DFXSECURE_dfxsecureplugin_param_values.vh  verif/tb/include/DFXSECURE_dfxsecureplugin_param_values.vh

ace -cc -cc_on -ccm branch+line+tgl+cond+fsm+assert -pwa pwa
ace -x       DfxSecurePlugin_DefaultTest:20:seed                    \
             DfxSecurePlugin_DriveUserPolicySeqTest:20:seed         \
             DfxSecurePlugin_PolicySweepSeqTest:20:seed             \
             DfxSecurePlugin_DriveUserPolicyViaSBOVRSeqTest:20:seed \
             DfxSecurePlugin_DriveAllUserInputSeqTest:20:seed       \
             \
                       -cleanup_pattern_file ace/clean_up.cfg -nb -nbmon \
                       -simv_args "+vcs+lic+wait"                        \
                       -simv_args "-cm_noconst"                          \
                       -cc_on -ccm branch+line+tgl+cond+fsm+assert       \
                       -test_elab_opts "-lca"                            \
                       -rtt -pwa pwa

cd $IP_ROOT/pwa/results/tests/

$IP_ROOT/scripts/scr_genlist $IP_ROOT pwa

cd $IP_ROOT/pwa

urg -f $IP_ROOT/pwa/results/tests/vdblist.txt \
    -hier $IP_ROOT/scripts/coverage_inclusion.txt \
    -elfile $IP_ROOT/verif/tb/include/dsp_cov_exclusions_use1.el \
    -excl_bypass_checks \
    -dbname Merge \
    -report AllCov \
    -format both

firefox $IP_ROOT/pwa/AllCov/dashboard.html &

cd $MODEL_ROOT
\cp $MODEL_ROOT/verif/tb/include/configs/default/DfxSecurePlugin_TbDefines.svh              $MODEL_ROOT/verif/tb/DfxSecurePlugin_TbDefines.svh
\cp $MODEL_ROOT/verif/tb/include/configs/default/DFXSECURE_dfxsecureplugin_param_overide.vh $MODEL_ROOT/verif/tb/include/DFXSECURE_dfxsecureplugin_param_overide.vh
\cp $MODEL_ROOT/verif/tb/include/configs/default/DFXSECURE_dfxsecureplugin_param_values.vh  $MODEL_ROOT/verif/tb/include/DFXSECURE_dfxsecureplugin_param_values.vh
