#!/bin/tcsh -f

set SIP_TOOL_NAME=`echo $0 | sed -e 's/.*\///'`
##############################
# UNIX Environment setup
##############################
cd  ../../../scripts
if (! $?SIP_NO_SETUP) then
  source setup -ft
endif

cd ../tools/lec/sbendpoint

############  Setting PROCESS  & TOOLS ENV ################
setenv CAD_ROOT     /p/com/eda/dt/linux_2.6.5_x86-64
setenv SYNOPSYS_DC  /p/com/eda/synopsys/designcompiler/D-2010.03-SP5
setenv DESIGN_NAME  sbendpoint
setenv KIT_PATH     /p/kits/intel/p1273/p1273_0.8.0
setenv KIT_NAME     1273
setenv LIBRARY_TYPE d04
setenv bname        d04

rm -rf results
mkdir  results

lec -xl -dof sbendpoint.1273.do -nogui
