#!/usr/intel/bin/tcsh

source $SBR_ROOT/verif/sim/verdi_header

vericom +define+VERDI+SVC_USE_PGCB_VC+SVC_USE_CCU_VC \
-sverilog $OVM_HOME/src/ovm_pkg.sv \
+incdir+$OVM_HOME/src \
+incdir+$SBR_ROOT/bfm/sideband_vc/svlib \
+incdir+$SBR_ROOT/verif/tb/top_tb/$NETWORK \
$SBR_ROOT/verif/bfm/sideband_vc/svlib/svlib_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/svlib \
$SBR_ROOT/verif/bfm/sideband_vc/svlib/svlib_pkg_xml.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/common \
$SBR_ROOT/verif/bfm/sideband_vc/tb/common/iosfsbm_cm_pkg.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/common/defs.svh \
$SBR_ROOT/verif/bfm/sideband_vc/tb/common/queue_defs.svh \
$SBR_ROOT/verif/bfm/sideband_vc/tb/ip_vc/iosfsbm_ipvc_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/ip_vc \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/compmon/sideband \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/compmon/lib \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/compmon/ism \
+define+VCSSIM $SBR_ROOT/verif/bfm/sideband_vc/compmon/lib/iosf_sb_lib_fifo.sv \
$SBR_ROOT/verif/bfm/sideband_vc/compmon/lib/iosf_sb_lib_cam.sv \
$SBR_ROOT/verif/bfm/sideband_vc/compmon/ism/iosf_sb_agent_ism_compliance.sv \
$SBR_ROOT/verif/bfm/sideband_vc/compmon/ism/iosf_sb_fabric_ism_compliance.sv \
$SBR_ROOT/verif/bfm/sideband_vc/compmon/ism/iosf_sb_clock_gating_compliance.sv \
$SBR_ROOT/verif/bfm/sideband_vc/compmon/sideband/iosf_sb_credit_compliance.sv \
$SBR_ROOT/verif/bfm/sideband_vc/compmon/sideband/iosf_sb_flow_compliance.sv \
$SBR_ROOT/verif/bfm/sideband_vc/compmon/sideband/iosf_sb_message_compliance.sv \
$SBR_ROOT/verif/bfm/sideband_vc/compmon/sideband/iosf_sb_ifc_compliance.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/intf \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/iosf_sbc_intf.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/comm_intf.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/agent_vc \
$SBR_ROOT/verif/bfm/sideband_vc/tb/agent_vc/iosfsbm_agent_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/fabric_vc \
$SBR_ROOT/verif/bfm/sideband_vc/tb/fabric_vc/iosfsbm_fbrc_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/env \
$SBR_ROOT/verif/bfm/sideband_vc/tb/env/iosfsbm_agent_fbrc_env_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/common \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/agent_vc \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/fabric_vc \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/seq_lib \
$SBR_ROOT/verif/bfm/sideband_vc/tb/seq_lib/iosfsbm_seq_pkg.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/common/iosf_sb_ti.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/clk_rst_vc \
$SBR_ROOT/verif/bfm/sideband_vc/tb/clk_rst_vc/clk_rst_pkg.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/connect_sbc_intf.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/clk_rst_intf.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/pmu_vc \
$SBR_ROOT/verif/bfm/sideband_vc/tb/pmu_vc/iosf_pmu_pkg.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/iosf_pmu_intf.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/power_intf.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/iosfsb_ep_mon.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/iosf_sbr_pmu_intf.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/debug \
$SBR_ROOT/verif/bfm/sideband_vc/tb/debug/iosfsbm_debug_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/ip_vc \
$SBR_ROOT/verif/bfm/sideband_vc/tb/ip_vc/iosfsbm_ipvc_pkg.sv \
$SBR_ROOT/verif/bfm/sideband_vc/tb/intf/iosf_ep_intf.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/rtr_vc \
$SBR_ROOT/verif/bfm/sideband_vc/tb/rtr_vc/iosfsbm_rtr_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/fbrc_rtr_vc \
$SBR_ROOT/verif/bfm/sideband_vc/tb/fbrc_rtr_vc/iosfsbm_fbrc_rtr_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/tb/env \
$SBR_ROOT/verif/bfm/sideband_vc/tb/env/iosfsbm_rtr_env_pkg.sv \
+incdir+$SBR_ROOT/verif/tests/rtr_tests \
+incdir+$SBR_ROOT/verif/bfm/ccu_vc/verif/ccu-vc \
#$SAOLA_HOME/verilog/sla_pkg.sv \
#$SBR_ROOT/verif/bfm/sideband_vc/sip_vintf_manager/src/sip_vintf_pkg.sv \
+incdir+$SBR_ROOT/verif/bfm/sideband_vc/sip_vintf_manager/src \
+incdir+/p/com/eda/intel/saola/v20130225/verilog \
+incdir+$SBR_ROOT/verif/lib/sip_vintf_manager/src \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_OOB/ccu_ob_pkg.sv \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_OOB/ccu_ob_intf.sv \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_OOB/ccu_ob_ti.sv \
#+incdir+$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_OOB \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_CRG/ccu_crg_pkg.sv \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_CRG/ccu_crg_pkg.sv \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_CRG/ccu_crg_intf.sv \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_CRG/ccu_crg_no_param_intf.sv \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_CRG/ccu_crg_ti.sv \
+incdir+$SBR_ROOT/verif/bfm/ccu_vc/verif/lib/CCU_CRG \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/ccu-vc/ccu_vc_pkg.sv \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/ccu-vc/ccu_vc_ti.sv \
#$SBR_ROOT/verif/bfm/ccu_vc/verif/ccu-vc/ccu_vc.svh \
#$SBR_ROOT/verif/bfm/pgcb_vc/source/Common/PowerGatingParamsPkg.sv \
#$SBR_ROOT/verif/bfm/pgcb_vc/source/Common/PowerGatingCommonPkg.sv \
#$SBR_ROOT/verif/bfm/pgcb_vc/source/CC/CCAgentPkg.sv \
#$SBR_ROOT/verif/bfm/pgcb_vc/source/PGCB/PGCBAgentPkg.sv \
#$SBR_ROOT/verif/bfm/pgcb_vc/source/Common/PowerGatingIF.sv \
#$SBR_ROOT/verif/bfm/pgcb_vc/source/Common/PowerGatingNoParamIF.sv \
#$SBR_ROOT/verif/bfm/pgcb_vc/source/CC/CCAgentTI.sv \
#$SBR_ROOT/verif/bfm/pgcb_vc/source/PGCB/PGCBAgentTI.sv \
+incdir+$SBR_ROOT/verif/bfm/pgcb_vc/source/Common \
+incdir+$SBR_ROOT/verif/bfm/pgcb_vc/source/CC \
+incdir+$SBR_ROOT/verif/bfm/pgcb_vc/source/PGCB \
+incdir+$SBR_ROOT/source/rtl/iosfsbc/common \
+incdir+$SBR_ROOT/source/rtl/iosfsbc/router \
$SBR_ROOT/verif/tests/rtr_tests/iosfsbm_rtr_tests_pkg.sv \
$SBR_ROOT/source/rtl/iosfsbc/common/*.sv \
$SBR_ROOT/source/rtl/iosfsbc/router/*.sv \
#$SBR_ROOT/verif/tb/env/$NETWORK/staticNetworkConfig.svh \
$SBR_ROOT/verif/tb/top_tb/$NETWORK/TestIsland/*.sv \
$SBR_ROOT/verif/tb/top_tb/$NETWORK/*.sv 

csh -f $SBR_ROOT/verif/sim/verdi_script

