
//  INTEL CONFIDENTIAL
//
//  Copyright 2023 Intel Corporation All Rights Reserved.
//
//  The source code contained or described herein and all documents related
//  to the source code ("Material") are owned by Intel Corporation or its
//  suppliers or licensors. Title to the Material remains with Intel
//  Corporation or its suppliers and licensors. The Material contains trade
//  secrets and proprietary and confidential information of Intel or its
//  suppliers and licensors. The Material is protected by worldwide copyright
//  and trade secret laws and treaty provisions. No part of the Material may
//  be used, copied, reproduced, modified, published, uploaded, posted,
//  transmitted, distributed, or disclosed in any way without Intel's prior
//  express written permission.
//
//  No license under any patent, copyright, trade secret or other intellectual
//  property right is granted to or conferred upon you by disclosure or
//  delivery of the Materials, either expressly, by implication, inducement,
//  estoppel or otherwise. Any license under such intellectual property rights
//  must be express and approved by Intel in writing.
//

//------------------------------------------------------------------------------------------------------------------------
// Intel Proprietary        Intel Confidential        Intel Proprietary        Intel Confidential        Intel Proprietary
//------------------------------------------------------------------------------------------------------------------------
// Generated by                  : cudoming
// Generated on                  : April 18, 2023
//------------------------------------------------------------------------------------------------------------------------
// General Information:
// ------------------------------
// 1r1w0c standard array for SDG server designs.
// Behavioral modeling of a parameterized register file core with no DFX features.
// RTL is written in SystemVerilog.
//------------------------------------------------------------------------------------------------------------------------
// Detail Information:
// ------------------------------
// Addresses        : RD/WR addresses are encoded.
//                    Input addresses will be valid at the array in 1 phases after being driven.
//                    Address latency of 1 is corresponding to a B-latch.
// Enables          : RD/WR enables are used to condition the clock and wordlines.
//                  : Input enables will be valid at the array in 1 phases after being driven.
//                    Enable latency of 1 is corresponding to a B-latch.
// Write Data       : Write data will be valid at the array 2 phases after being driven.
//                    Write data latency of 2 is corresponding to a rising-edge flop. 
// Read Data        : Read data will be valid at the output of a SDL 1 phase after being read.
//                    Read data latency of 1 is corresponding to a B-latch.
// Address Offset   : 
//------------------------------------------------------------------------------------------------------------------------

//------------------------------------------------------------------------------------------------------------------------
// Other Information:
// ------------------------------
// SDG RFIP RTL Release Path:
// /p/hdk/rtl/ip_releases/shdk74/array_macro_module
//
//------------------------------------------------------------------------------------------------------------------------

////////////////////////////////////////////////////////////////
// FileName : arf198b128e1r1w0cbbehbaa4acw.v
// RAM Library Model - Top
// this module definition allows the sdl_init to be external to the atpglib 
// so that it can have a separate init attribute
////////////////////////////////////////////////////////////////

module arf198b128e1r1w0cbbehbaa4acw (
  ckrdp0, rdenp0, rdaddrp0, sdl_initp0, rddatap0, 
  ckwrp0, wrenp0, wraddrp0, wrdatap0,  
  rdaddrp0_fd, rdaddrp0_rd, 
  wraddrp0_fd, wraddrp0_rd, wrdatap0_fd, wrdatap0_rd);

  //Input and output pins declarations
  input ckrdp0;
  input rdenp0;
  input [6:0] rdaddrp0;
  output [199:0] rddatap0;
  input sdl_initp0;

  input ckwrp0;
  input wrenp0; 
  input [6:0] wraddrp0;
  input [199:0] wrdatap0;
 
  input rdaddrp0_fd;
  input rdaddrp0_rd;

  input wraddrp0_fd;
  input wraddrp0_rd;
  input wrdatap0_fd;
  input wrdatap0_rd;

  wire [199:0] pre_rddatap0 ;
  wire sdl_initp0_i_out;
  wire ckrd_rcb_outp0;


  //hier module
  arf198b128e1r1w0cbbehbaa4acw_hier sub_array (
     .ckrdp0           ( ckrdp0 )
    ,.rdenp0           ( rdenp0 )
    ,.rdaddrp0         ( rdaddrp0 )
    ,.pre_rddatap0     ( pre_rddatap0 )
    ,.sdl_initp0       ( sdl_initp0 )
    ,.sdl_initp0_i_out ( sdl_initp0_i_out )
    ,.ckrd_rcb_outp0   ( ckrd_rcb_outp0 )
    ,.ckwrp0           ( ckwrp0 )
    ,.wrenp0           ( wrenp0 )
    ,.wraddrp0         ( wraddrp0 )
    ,.wrdatap0         ( wrdatap0 )
    ,.rdaddrp0_fd      ( rdaddrp0_fd )
    ,.rdaddrp0_rd      ( rdaddrp0_rd )
    ,.wraddrp0_fd      ( wraddrp0_fd )
    ,.wraddrp0_rd      ( wraddrp0_rd )
    ,.wrdatap0_fd      ( wrdatap0_fd )
    ,.wrdatap0_rd      ( wrdatap0_rd )
  );

  //rddatap0
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_199 (.d(pre_rddatap0[199]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[199]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_198 (.d(pre_rddatap0[198]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[198]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_197 (.d(pre_rddatap0[197]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[197]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_196 (.d(pre_rddatap0[196]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[196]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_195 (.d(pre_rddatap0[195]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[195]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_194 (.d(pre_rddatap0[194]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[194]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_193 (.d(pre_rddatap0[193]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[193]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_192 (.d(pre_rddatap0[192]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[192]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_191 (.d(pre_rddatap0[191]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[191]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_190 (.d(pre_rddatap0[190]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[190]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_189 (.d(pre_rddatap0[189]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[189]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_188 (.d(pre_rddatap0[188]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[188]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_187 (.d(pre_rddatap0[187]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[187]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_186 (.d(pre_rddatap0[186]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[186]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_185 (.d(pre_rddatap0[185]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[185]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_184 (.d(pre_rddatap0[184]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[184]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_183 (.d(pre_rddatap0[183]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[183]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_182 (.d(pre_rddatap0[182]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[182]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_181 (.d(pre_rddatap0[181]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[181]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_180 (.d(pre_rddatap0[180]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[180]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_179 (.d(pre_rddatap0[179]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[179]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_178 (.d(pre_rddatap0[178]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[178]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_177 (.d(pre_rddatap0[177]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[177]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_176 (.d(pre_rddatap0[176]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[176]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_175 (.d(pre_rddatap0[175]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[175]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_174 (.d(pre_rddatap0[174]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[174]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_173 (.d(pre_rddatap0[173]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[173]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_172 (.d(pre_rddatap0[172]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[172]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_171 (.d(pre_rddatap0[171]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[171]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_170 (.d(pre_rddatap0[170]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[170]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_169 (.d(pre_rddatap0[169]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[169]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_168 (.d(pre_rddatap0[168]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[168]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_167 (.d(pre_rddatap0[167]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[167]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_166 (.d(pre_rddatap0[166]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[166]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_165 (.d(pre_rddatap0[165]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[165]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_164 (.d(pre_rddatap0[164]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[164]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_163 (.d(pre_rddatap0[163]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[163]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_162 (.d(pre_rddatap0[162]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[162]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_161 (.d(pre_rddatap0[161]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[161]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_160 (.d(pre_rddatap0[160]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[160]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_159 (.d(pre_rddatap0[159]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[159]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_158 (.d(pre_rddatap0[158]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[158]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_157 (.d(pre_rddatap0[157]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[157]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_156 (.d(pre_rddatap0[156]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[156]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_155 (.d(pre_rddatap0[155]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[155]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_154 (.d(pre_rddatap0[154]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[154]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_153 (.d(pre_rddatap0[153]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[153]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_152 (.d(pre_rddatap0[152]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[152]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_151 (.d(pre_rddatap0[151]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[151]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_150 (.d(pre_rddatap0[150]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[150]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_149 (.d(pre_rddatap0[149]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[149]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_148 (.d(pre_rddatap0[148]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[148]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_147 (.d(pre_rddatap0[147]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[147]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_146 (.d(pre_rddatap0[146]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[146]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_145 (.d(pre_rddatap0[145]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[145]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_144 (.d(pre_rddatap0[144]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[144]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_143 (.d(pre_rddatap0[143]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[143]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_142 (.d(pre_rddatap0[142]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[142]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_141 (.d(pre_rddatap0[141]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[141]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_140 (.d(pre_rddatap0[140]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[140]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_139 (.d(pre_rddatap0[139]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[139]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_138 (.d(pre_rddatap0[138]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[138]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_137 (.d(pre_rddatap0[137]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[137]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_136 (.d(pre_rddatap0[136]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[136]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_135 (.d(pre_rddatap0[135]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[135]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_134 (.d(pre_rddatap0[134]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[134]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_133 (.d(pre_rddatap0[133]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[133]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_132 (.d(pre_rddatap0[132]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[132]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_131 (.d(pre_rddatap0[131]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[131]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_130 (.d(pre_rddatap0[130]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[130]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_129 (.d(pre_rddatap0[129]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[129]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_128 (.d(pre_rddatap0[128]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[128]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_127 (.d(pre_rddatap0[127]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[127]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_126 (.d(pre_rddatap0[126]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[126]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_125 (.d(pre_rddatap0[125]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[125]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_124 (.d(pre_rddatap0[124]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[124]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_123 (.d(pre_rddatap0[123]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[123]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_122 (.d(pre_rddatap0[122]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[122]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_121 (.d(pre_rddatap0[121]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[121]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_120 (.d(pre_rddatap0[120]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[120]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_119 (.d(pre_rddatap0[119]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[119]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_118 (.d(pre_rddatap0[118]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[118]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_117 (.d(pre_rddatap0[117]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[117]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_116 (.d(pre_rddatap0[116]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[116]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_115 (.d(pre_rddatap0[115]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[115]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_114 (.d(pre_rddatap0[114]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[114]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_113 (.d(pre_rddatap0[113]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[113]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_112 (.d(pre_rddatap0[112]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[112]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_111 (.d(pre_rddatap0[111]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[111]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_110 (.d(pre_rddatap0[110]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[110]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_109 (.d(pre_rddatap0[109]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[109]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_108 (.d(pre_rddatap0[108]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[108]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_107 (.d(pre_rddatap0[107]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[107]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_106 (.d(pre_rddatap0[106]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[106]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_105 (.d(pre_rddatap0[105]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[105]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_104 (.d(pre_rddatap0[104]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[104]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_103 (.d(pre_rddatap0[103]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[103]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_102 (.d(pre_rddatap0[102]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[102]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_101 (.d(pre_rddatap0[101]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[101]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_100 (.d(pre_rddatap0[100]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[100]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_99 (.d(pre_rddatap0[99]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[99]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_98 (.d(pre_rddatap0[98]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[98]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_97 (.d(pre_rddatap0[97]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[97]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_96 (.d(pre_rddatap0[96]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[96]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_95 (.d(pre_rddatap0[95]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[95]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_94 (.d(pre_rddatap0[94]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[94]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_93 (.d(pre_rddatap0[93]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[93]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_92 (.d(pre_rddatap0[92]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[92]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_91 (.d(pre_rddatap0[91]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[91]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_90 (.d(pre_rddatap0[90]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[90]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_89 (.d(pre_rddatap0[89]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[89]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_88 (.d(pre_rddatap0[88]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[88]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_87 (.d(pre_rddatap0[87]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[87]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_86 (.d(pre_rddatap0[86]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[86]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_85 (.d(pre_rddatap0[85]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[85]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_84 (.d(pre_rddatap0[84]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[84]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_83 (.d(pre_rddatap0[83]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[83]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_82 (.d(pre_rddatap0[82]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[82]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_81 (.d(pre_rddatap0[81]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[81]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_80 (.d(pre_rddatap0[80]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[80]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_79 (.d(pre_rddatap0[79]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[79]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_78 (.d(pre_rddatap0[78]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[78]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_77 (.d(pre_rddatap0[77]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[77]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_76 (.d(pre_rddatap0[76]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[76]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_75 (.d(pre_rddatap0[75]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[75]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_74 (.d(pre_rddatap0[74]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[74]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_73 (.d(pre_rddatap0[73]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[73]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_72 (.d(pre_rddatap0[72]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[72]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_71 (.d(pre_rddatap0[71]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[71]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_70 (.d(pre_rddatap0[70]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[70]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_69 (.d(pre_rddatap0[69]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[69]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_68 (.d(pre_rddatap0[68]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[68]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_67 (.d(pre_rddatap0[67]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[67]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_66 (.d(pre_rddatap0[66]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[66]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_65 (.d(pre_rddatap0[65]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[65]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_64 (.d(pre_rddatap0[64]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[64]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_63 (.d(pre_rddatap0[63]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[63]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_62 (.d(pre_rddatap0[62]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[62]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_61 (.d(pre_rddatap0[61]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[61]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_60 (.d(pre_rddatap0[60]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[60]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_59 (.d(pre_rddatap0[59]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[59]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_58 (.d(pre_rddatap0[58]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[58]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_57 (.d(pre_rddatap0[57]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[57]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_56 (.d(pre_rddatap0[56]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[56]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_55 (.d(pre_rddatap0[55]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[55]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_54 (.d(pre_rddatap0[54]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[54]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_53 (.d(pre_rddatap0[53]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[53]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_52 (.d(pre_rddatap0[52]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[52]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_51 (.d(pre_rddatap0[51]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[51]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_50 (.d(pre_rddatap0[50]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[50]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_49 (.d(pre_rddatap0[49]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[49]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_48 (.d(pre_rddatap0[48]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[48]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_47 (.d(pre_rddatap0[47]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[47]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_46 (.d(pre_rddatap0[46]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[46]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_45 (.d(pre_rddatap0[45]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[45]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_44 (.d(pre_rddatap0[44]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[44]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_43 (.d(pre_rddatap0[43]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[43]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_42 (.d(pre_rddatap0[42]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[42]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_41 (.d(pre_rddatap0[41]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[41]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_40 (.d(pre_rddatap0[40]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[40]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_39 (.d(pre_rddatap0[39]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[39]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_38 (.d(pre_rddatap0[38]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[38]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_37 (.d(pre_rddatap0[37]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[37]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_36 (.d(pre_rddatap0[36]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[36]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_35 (.d(pre_rddatap0[35]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[35]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_34 (.d(pre_rddatap0[34]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[34]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_33 (.d(pre_rddatap0[33]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[33]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_32 (.d(pre_rddatap0[32]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[32]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_31 (.d(pre_rddatap0[31]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[31]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_30 (.d(pre_rddatap0[30]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[30]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_29 (.d(pre_rddatap0[29]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[29]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_28 (.d(pre_rddatap0[28]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[28]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_27 (.d(pre_rddatap0[27]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[27]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_26 (.d(pre_rddatap0[26]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[26]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_25 (.d(pre_rddatap0[25]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[25]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_24 (.d(pre_rddatap0[24]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[24]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_23 (.d(pre_rddatap0[23]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[23]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_22 (.d(pre_rddatap0[22]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[22]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_21 (.d(pre_rddatap0[21]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[21]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_20 (.d(pre_rddatap0[20]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[20]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_19 (.d(pre_rddatap0[19]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[19]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_18 (.d(pre_rddatap0[18]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[18]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_17 (.d(pre_rddatap0[17]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[17]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_16 (.d(pre_rddatap0[16]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[16]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_15 (.d(pre_rddatap0[15]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[15]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_14 (.d(pre_rddatap0[14]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[14]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_13 (.d(pre_rddatap0[13]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[13]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_12 (.d(pre_rddatap0[12]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[12]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_11 (.d(pre_rddatap0[11]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[11]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_10 (.d(pre_rddatap0[10]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[10]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_9 (.d(pre_rddatap0[9]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[9]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_8 (.d(pre_rddatap0[8]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[8]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_7 (.d(pre_rddatap0[7]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[7]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_6 (.d(pre_rddatap0[6]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[6]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_5 (.d(pre_rddatap0[5]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[5]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_4 (.d(pre_rddatap0[4]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[4]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_3 (.d(pre_rddatap0[3]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[3]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_2 (.d(pre_rddatap0[2]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[2]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_1 (.d(pre_rddatap0[1]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[1]));
  arf198b128e1r1w0cbbehbaa4acw_latch_func data_out_p0_0 (.d(pre_rddatap0[0]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[0]));

endmodule

module arf198b128e1r1w0cbbehbaa4acw_latch_func ( clk, d, rb, o );
input clk;
input d;
input rb;
output o;
wire o_tmp;

       arf198b128e1r1w0cbbehbaa4acw_lat_mem latch_inst ( o_tmp, d, rb, clk );
       assign #1 o = o_tmp;

endmodule

// async-reset active-high latch.
primitive arf198b128e1r1w0cbbehbaa4acw_lat_mem (o, d, rb, clk, notifier);
    output o;
    reg    o;
    input  d, rb, clk, notifier;

    table
    //  d   rb   clk   notifier :  ot  :   ot+1
        ?    1     0    ?        :  ?   :    - ;  // clock disabled
        ?    0     ?    ?        :  ?   :    0 ;  // async reset
        0    ?     1    ?        :  ?   :    0 ;  //clock enabled
        1    1     1    ?        :  ?   :    1 ;  //transparent data
        0    ?     x    ?        :  0   :    0 ;  // Reducing pessimism.
        1    1     x    ?        :  1   :    1 ;
        ?    x     0    ?        :  0   :    0 ;
        ?    ?     ?    *        :  ?   :    x ;  //notifier
   endtable
endprimitive
