//------------------------------------------------------------------------------
//  %header_copyright%
//
//  Collateral Description:
//  %header_collateral%
//
//  Source organization:
//  %header_organization%
//
//  Support Information:
//  %header_support%
//
//  Revision:
//  %header_tag%
//
//  Module <mTAP> :  < put your functional description here in plain text >
//
//------------------------------------------------------------------------------

//----------------------------------------------------------------------
// Intel Proprietary -- Copyright 2009 Intel -- All rights reserved
//----------------------------------------------------------------------
// NOTE: Log history is at end of file.
//----------------------------------------------------------------------
//
//    FILENAME    : mtap_defines_include.sv
//    DESIGNER    : Sunjiv Sachan
//    PROJECT     : mTAP
//    
//    
//    PURPOSE     : Declaration of `defines
//    DESCRIPTION :
//       User defined `defines. Please refer User Manual for examples.
//----------------------------------------------------------------------
   // *********************************************************************
   // `defines - WTAP
   // *********************************************************************
   `define DFX_ASSERTIONS
   `define DFX_PARAMETER_CHECKER
   //`define DFX_FPV_ENABLE
