$ip/subIP/acored/src/rtl/top/acored_top.sv
$ip/subIP/acored/src/rtl/iac_bit2byte_packer.sv
$ip/subIP/acored/src/rtl/iac_byte2dword_packer.sv
$ip/subIP/acored/src/rtl/iac_byte_expand.sv
$ip/subIP/acored/src/rtl/iac_mul_32_64.sv
$ip/subIP/acored/src/rtl/iac_crc64.sv
$ip/subIP/acored/src/rtl/iac_crc32.sv
$ip/subIP/acored/src/rtl/iac_crc32_128.sv
$ip/subIP/acored/src/rtl/iac_crc32_128_tree.sv
$ip/subIP/acored/src/rtl/iac_crc32_128_tree_1.sv
$ip/subIP/acored/src/rtl/iac_crc32_stg0.sv
$ip/subIP/acored/src/rtl/iac_crc32_stg1.sv
$ip/subIP/acored/src/rtl/iac_crc32_tree.sv
$ip/subIP/acored/src/rtl/iac_crc32_tree_1.sv
$ip/subIP/acored/src/rtl/iac_dcmp_hbuf.sv
$ip/subIP/acored/src/rtl/iac_deflate_decoder.sv
$ip/subIP/acored/src/rtl/iac_deflate_top.sv
$ip/subIP/acored/src/rtl/iac_dflt_alu.sv
$ip/subIP/acored/src/rtl/iac_dflt_cam_dist.sv
$ip/subIP/acored/src/rtl/iac_dflt_cam_dist_spec.sv
$ip/subIP/acored/src/rtl/iac_dflt_cam_len.sv
$ip/subIP/acored/src/rtl/iac_dflt_datain_buf.sv
$ip/subIP/acored/src/rtl/iac_dflt_dist_lut.sv
$ip/subIP/acored/src/rtl/iac_dflt_huff_dcd.sv
$ip/subIP/acored/src/rtl/iac_dflt_len_eb_lut.sv
$ip/subIP/acored/src/rtl/iac_dflt_ll_cam.sv
$ip/subIP/acored/src/rtl/iac_llcam_entry.sv
$ip/subIP/acored/src/rtl/iac_dflt_spec_alu.sv
$ip/subIP/acored/src/rtl/iac_dflt_nbit_alu.sv
$ip/subIP/acored/src/rtl/iac_dflt_top.sv
$ip/subIP/acored/src/rtl/iac_dflt_translate.sv
$ip/subIP/acored/src/rtl/iac_expand.sv
$ip/subIP/acored/src/rtl/iac_extract.sv
$ip/subIP/acored/src/rtl/iac_filter_input.sv
$ip/subIP/acored/src/rtl/iac_filter_pack.sv
$ip/subIP/acored/src/rtl/iac_filter_top.sv
$ip/subIP/acored/src/rtl/iac_output_aggr.sv
$ip/subIP/acored/src/rtl/iac_output_dout.sv
$ip/subIP/acored/src/rtl/iac_output_mod.sv
$ip/subIP/acored/src/rtl/iac_prle_decode.sv
$ip/subIP/acored/src/rtl/iac_rle.sv
$ip/subIP/acored/src/rtl/iac_scan.sv
$ip/subIP/acored/src/rtl/iac_select.sv
$ip/subIP/acored/src/rtl/iac_setmem.sv
$ip/subIP/acored/src/rtl/iac_setmem_large.sv
$ip/subIP/acored/src/rtl/iac_tree_cache.sv
$ip/subIP/acored/src/rtl/iac_tree_decoder.sv
$ip/subIP/acored/src/rtl/iac_crypto_top.sv
$ip/subIP/acored/src/rtl/iac_crypto_core.sv
$ip/subIP/acored/src/rtl/iac_crypto_red.sv
$ip/subIP/acored/src/rtl/iac_aes_top.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_transform128.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_transform8.sv
$ip/subIP/acored/src/rtl/iac_aes_round.sv
$ip/subIP/acored/src/rtl/iac_aes_encdec_sbox.sv
$ip/subIP/acored/src/rtl/iac_aes_xmc_32.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_inv.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_mul4x4.sv
$ip/subIP/acored/src/rtl/iac_aes_xmc_8.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_inv_transform128.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_inv_transform8.sv
$ip/subIP/acored/src/rtl/iac_aes_key_top.sv
$ip/subIP/acored/src/rtl/iac_ghash_top.sv
$ip/subIP/acored/src/rtl/iac_ghash_array.sv
$ip/subIP/acored/src/rtl/iac_aes_keygen.sv
$ip/subIP/acored/src/rtl/iac_aes_enc_sbox.sv
$ip/subIP/acored/src/rtl/rf1w1r71x2.sv
$ip/subIP/acored/src/rtl/iac_zexpand.sv
$ip/subIP/acored/src/rtl/iac_zselect.sv
$ip/subIP/acored/src/rtl/iac_zselect_v1.sv
$ip/subIP/acored/src/rtl/iac_zverify.sv
$ip/subIP/acored/src/rtl/iac_dcmp_fifo_out.sv
$ip/subIP/acored/src/rtl/iac_acored_buf.sv
$ip/subIP/acored/src/rtl/acored_eip_parity.sv
$ip/subIP/acored/src/rtl/top/acorec_top.sv
$ip/subIP/acored/src/rtl/acorec_eip_parity.sv
$ip/subIP/acored/src/rtl/iac_comp_compare.sv
$ip/subIP/acored/src/rtl/iac_comp_ht.sv
$ip/subIP/acored/src/rtl/iac_comp_la.sv
$ip/subIP/acored/src/rtl/iac_comp_lz_merge.sv
$ip/subIP/acored/src/rtl/iac_comp_top.sv
$ip/subIP/acored/src/rtl/iac_config.sv
$ip/subIP/acored/src/rtl/iac_hm_encoder.sv
$ip/subIP/acored/src/rtl/iac_rbuffer.sv
$ip/subIP/acored/src/rtl/iac_bai_buffer.sv
$ip/subIP/acored/src/rtl/rf1w1r24x8.sv
$ip/subIP/acored/src/rtl/rf1w1r66x8.sv
$ip/subIP/acored/src/rtl/iac_comp_tgen.sv
+incdir+$ip/subIP/acored/src/gen
+incdir+$ip/subIP/acored/src/rtl/common
+incdir+$ip/subIP/acored/src/rtl/include

