$ip/src/rtl/dproc/dproc_mem.sv
$ip/src/rtl/dproc/dproc_rdc.sv
$ip/src/rtl/dproc/dproc_wdc.sv
$ip/src/rtl/dproc/dproc_dpc.sv
$ip/src/rtl/dproc/dproc_crc.sv
$ip/src/rtl/dproc/dproc_dif.sv
$ip/src/rtl/dproc/dproc_alu.sv
$ip/src/rtl/dproc/dproc_pipe.sv
$ip/src/rtl/dproc/dproc_top.sv

$ip/src/rtl/common/dsa_fwft_fifo.sv
$ip/src/rtl/common/dsa_pkg.svh
$ip/src/rtl/common/dsa_macros.svh
$ip/src/rtl/dproc/dproc_pkg.svh

#ALU
$ip/src/rtl/alu/dsa_alu_pkg.svh
$ip/src/rtl/alu/conv/dsa_alu_qpupc.sv
$ip/src/rtl/alu/conv/dsa_alu_hpupc.sv
$ip/src/rtl/alu/conv/dsa_alu_spupc.sv
$ip/src/rtl/alu/conv/dsa_alu_dpupc.sv
$ip/src/rtl/alu/conv/dsa_alu_ic.sv
$ip/src/rtl/alu/conv/dsa_alu_qpdnc.sv
$ip/src/rtl/alu/conv/dsa_alu_hpdnc.sv
$ip/src/rtl/alu/conv/dsa_alu_spdnc.sv
$ip/src/rtl/alu/conv/dsa_alu_dpdnc.sv
$ip/src/rtl/alu/conv/dsa_alu_ec.sv
$ip/src/rtl/alu/op/dsa_alu_ltzd.sv
$ip/src/rtl/alu/op/dsa_alu_hcadder.sv
$ip/src/rtl/alu/op/dsa_alu_gap_adder.sv
$ip/src/rtl/alu/op/dsa_alu_fp8add.sv
$ip/src/rtl/alu/op/dsa_alu_fp16add.sv
$ip/src/rtl/alu/op/dsa_alu_spadd.sv
$ip/src/rtl/alu/op/dsa_alu_dpadd.sv
$ip/src/rtl/alu/op/dsa_alu_op.sv
$ip/src/rtl/alu/dsa_alu.sv

+incdir+$ip/src/rtl/common
+incdir+$ip/src/rtl/dproc
+incdir+$ip/src/rtl/alu
