$ip/src/rtl/top/dsa_pgd.sv
$ip/src/rtl/top/dsa_mem.sv
$ip/src/rtl/top/dsa_cfg_ctl.sv
$ip/src/rtl/top/dsa_ownership.sv
$ip/src/rtl/top/dsa_bisr.sv
$ip/src/rtl/top/dsa_crp_flr.sv
$ip/src/rtl/top/dsa_crp_misc.sv
$ip/src/rtl/top/dsa_clocks.sv
$ip/src/rtl/top/dsa_power_ctl.sv
$ip/src/rtl/top/dsa_power.sv
$ip/src/rtl/top/dsa_resets.sv
$ip/src/rtl/top/dsa_resets_clks.sv
$ip/src/rtl/top/dsa_crp.sv
$ip/src/rtl/top/dsa_sb.sv
$ip/src/rtl/top/dsa_misc.sv
$ip/src/rtl/top/dsa_genram_vram_eip.sv
$ip/src/rtl/top/dsa_aon_common.sv
$ip/src/rtl/dsa/dsa_cgc_old.sv
$ip/src/rtl/dsa/dsa_command.sv
$ip/src/rtl/dsa/dsa_enable_dev.sv
$ip/src/rtl/dsa/dsa_enable_wq.sv
$ip/src/rtl/dsa/dsa_dchk.sv
$ip/src/rtl/dsa/dsa_idchk.sv
$ip/src/rtl/dsa/dsa_wq.sv
$ip/src/rtl/dsa/dsa_wq_dbuf.sv
$ip/src/rtl/dsa/dsa_wq_core.sv
$ip/src/rtl/dsa/dsa_wq_wac.sv
$ip/src/rtl/dsa/dsa_wq_ctl.sv
$ip/src/rtl/dsa/dsa_wq_wdc.sv
$ip/src/rtl/dsa/dsa_wq_adc.sv
$ip/src/rtl/dsa/dsa_wq_arb.sv
$ip/src/rtl/dsa/dsa_wq_dfsm.sv
$ip/src/rtl/dsa/dsa_grp_bctrl.sv
$ip/src/rtl/dsa/dsa_cmp_buf.sv
$ip/src/rtl/dsa/dsa_cb_queue.sv
$ip/src/rtl/dsa/dsa_wr_buf_cmd.sv
$ip/src/rtl/dsa/dsa_wr_buf.sv
$ip/src/rtl/dsa/dsa_ci_cmd.sv
$ip/src/rtl/dsa/dsa_ci.sv
$ip/src/rtl/dsa/dsa_cfgreq.sv
$ip/src/rtl/dsa/dsa_msix.sv
$ip/src/rtl/dsa/dsa_ims.sv
$ip/src/rtl/dsa/dsa_intr.sv
$ip/src/rtl/dsa/dsa_pmon.sv
$ip/src/rtl/dsa/dsa_pmoncntr.sv
$ip/src/rtl/dsa/dsa_cdesc_qtrk.sv
$ip/src/rtl/dsa/dsa_cdesc_drain.sv
$ip/src/rtl/dsa/dsa_cdesc_top.sv
$ip/src/rtl/dsa/dsa_eng_top.sv
$ip/src/rtl/dsa/dsa_eng.sv
$ip/src/rtl/dsa/dsa_eng_axq.sv
$ip/src/rtl/dsa/dsa_eng_dexq.sv
$ip/src/rtl/dsa/dsa_eng_ipba.sv
$ip/src/rtl/dsa/dsa_eng_sglq.sv
$ip/src/rtl/dsa/dsa_eng_addrx.sv
$ip/src/rtl/dsa/dsa_eng_dataf.sv
$ip/src/rtl/dsa/dsa_eng_dprdy.sv
$ip/src/rtl/dsa/dsa_eng_dprdc.sv
$ip/src/rtl/dsa/dsa_eng_dpwdc.sv
$ip/src/rtl/dsa/dsa_eng_dcmpr.sv
$ip/src/rtl/dsa/dsa_eng_trk.sv
$ip/src/rtl/dsa/dsa_eng_desc_trk.sv
$ip/src/rtl/dsa/dsa_atc_axq.sv
$ip/src/rtl/dsa/dsa_atc_top.sv
$ip/src/rtl/dsa/dsa_devtlb_wrap.sv
$ip/src/rtl/dsa/dsa_atc_treq.sv
$ip/src/rtl/dsa/dsa_atc_etrk.sv
$ip/src/rtl/dsa/dsa_atc_fsm.sv
$ip/src/rtl/dsa/dsa_atc_areq.sv
$ip/src/rtl/dsa/dsa_atc_arsp.sv
$ip/src/rtl/dsa/dsa_atc_inv.sv
$ip/src/rtl/dsa/dsa_desc_buf.sv
$ip/src/rtl/dsa/dsa_sg_buf.sv
$ip/src/rtl/dsa/dsa_batch_queue.sv
$ip/src/rtl/dsa/dsa_eng_sgxq.sv
$ip/src/rtl/dsa/dsa_eng_sgax.sv
$ip/src/rtl/dsa/dsa_eng_sgrd.sv
$ip/src/rtl/dsa/dsa_eng_sgwd.sv
$ip/src/rtl/dsa/dsa_eng_bexq.sv
$ip/src/rtl/dsa/dsa_eng_bdax.sv
$ip/src/rtl/dsa/dsa_eng_bdrd.sv
$ip/src/rtl/dsa/dsa_eng_bdwd.sv
$ip/src/rtl/dsa/dsa_eng_bdex.sv
$ip/src/rtl/dsa/dsa_eng_dparb.sv
$ip/src/rtl/dsa/dsa_dproc.sv
$ip/src/rtl/dsa/dsa_dproc_top.sv
$ip/src/rtl/dsa/dsa_dproc_crc.sv
$ip/src/rtl/dsa/dsa_crc32_top.sv
$ip/src/rtl/dsa/dsa_crc32_gf2_mult.sv
$ip/src/rtl/dsa/dsa_crc32_reducer.sv
$ip/src/rtl/dsa/dsa_dproc_trk.sv
$ip/src/rtl/dsa/dsa_t10_gf2_32_crc_opt.v
$ip/src/rtl/dsa/dsa_t10_gf2_partial_multi.v
$ip/src/rtl/dsa/dsa_eng_bex.sv
$ip/src/rtl/dsa/dsa_eng_sgx.sv
$ip/src/rtl/dsa/dsa_eng_dex.sv

$ip/src/rtl/ipi/dsa_ipi.sv
$ip/src/rtl/ipi/dsa_ipi_gasket.sv
$ip/src/rtl/ipi/dsa_ipi_config.sv
$ip/src/rtl/ipi/dsa_ipi_credit.sv
$ip/src/rtl/ipi/dsa_ipi_lookup.sv
$ip/src/rtl/ipi/dsa_ipi_master.sv
$ip/src/rtl/ipi/dsa_ipi_master_q.sv
$ip/src/rtl/ipi/dsa_ipi_target.sv
$ip/src/rtl/ipi/dsa_ipi_order.sv
$ip/src/rtl/ipi/dsa_ipi_split.sv
$ip/src/rtl/ipi/dsa_ipi_stream.sv
$ip/src/rtl/ipi/dsa_ipi_aer.sv
$ip/src/rtl/ipi/dsa_ipi_rr_arb.sv
$ip/src/rtl/dproc/dproc_pkg.svh
$ip/src/rtl/common/dsa_pkg.svh
$ip/src/rtl/common/dsa_iosf_pkg.svh
$ip/src/rtl/common/dsa_cfg_pkg.svh
$ip/src/rtl/common/dsa_macros.svh
$ip/src/rtl/common/dsa_rrarb.sv
$ip/src/rtl/common/dsa_rrarb2.sv
$ip/src/rtl/common/dsa_array.sv
$ip/src/rtl/common/dsa_async_fifo.sv
$ip/src/rtl/common/dsa_cgc.sv
$ip/src/rtl/common/dsa_ism.sv
$ip/src/rtl/common/dsa_map.sv
$ip/src/rtl/common/dsa_rst_sync.sv
$ip/src/rtl/common/dsa_rst_full_sync.sv
$ip/src/rtl/common/dsa_rst_flop.sv
$ip/src/rtl/common/dsa_parity.sv
$ip/src/rtl/common/dsa_four_phase_rspr.sv
$ip/src/rtl/sbw/dsa_sbw_prep.sv
$ip/src/rtl/sbw/dsa_sbw_setid.sv
$ip/src/rtl/sbw/dsa_sbw_treg.sv
$ip/src/rtl/sbw/dsa_sbw_aer.sv
$ip/src/rtl/sbw/dsa_sbw_intx.sv
$ip/src/rtl/sbw/dsa_sbw_pgpok.sv
$ip/src/rtl/sbw/dsa_sbw_ltr.sv
$ip/src/rtl/sbw/dsa_sbw_ip_rdy.sv
$ip/src/rtl/sbw/dsa_sbw_sleeplvl.sv
$ip/src/rtl/sbw/dsa_sbw_iommu_seq_msg.sv

+incdir+$ip/src/rtl/common
+incdir+$ip/src/rtl/top
+incdir+$ip/src/rtl/dsa
+incdir+$ip/src/rtl/dproc
+incdir+$ip/src/rtl/ipi
+incdir+$ip/src/rtl/sbw


