
// Giving priority to incdir of visa
+incdir+$ip/subIP/visa/rtl
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/common
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/eip
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/eip/iaa3p0s64b60
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/ipi
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/sbw
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/verif
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/verif/wrappers
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/verif/wrappers/eip
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/verif/wrappers/eip/iax
+incdir+$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/verif/wrappers/eip/iax/iaa3p0s64b60

// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaa3p0s64b60.rtl.f

// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/dsa_ctech.rtl.f
$ctech_path/ctech_lib_clk_divider2.sv
$ctech_path/ctech_lib_and.sv
$ctech_path/ctech_lib_buf.sv
$ctech_path/ctech_lib_clk_and.sv
$ctech_path/ctech_lib_clk_and_en.sv
$ctech_path/ctech_lib_clk_buf.sv
$ctech_path/ctech_lib_clk_divider2_rstb.sv
$ctech_path/ctech_lib_clk_ffb.sv
$ctech_path/ctech_lib_clk_ffb_rstb.sv
$ctech_path/ctech_lib_clk_gate_and.sv
$ctech_path/ctech_lib_clk_gate_or.sv
$ctech_path/ctech_lib_clk_gate_te.sv
$ctech_path/ctech_lib_clk_gate_te_rstb.sv
$ctech_path/ctech_lib_clk_inv.sv
$ctech_path/ctech_lib_clk_mux_2to1.sv
$ctech_path/ctech_lib_clk_nand.sv
$ctech_path/ctech_lib_clk_nand_en.sv
$ctech_path/ctech_lib_clk_nor.sv
$ctech_path/ctech_lib_clk_nor_en.sv
$ctech_path/ctech_lib_clk_or.sv
$ctech_path/ctech_lib_clk_or_en.sv
$ctech_path/ctech_lib_doublesync.sv
$ctech_path/ctech_lib_doublesync_rst.sv
$ctech_path/ctech_lib_doublesync_rstb.sv
$ctech_path/ctech_lib_doublesync_set.sv
$ctech_path/ctech_lib_doublesync_setb.sv
$ctech_path/ctech_lib_inv.sv
$ctech_path/ctech_lib_latch.sv
$ctech_path/ctech_lib_latch_p.sv
$ctech_path/ctech_lib_msff_async_rstb.sv
$ctech_path/ctech_lib_msff_async_setb.sv
$ctech_path/ctech_lib_mux_2to1.sv
$ctech_path/ctech_lib_nand.sv
$ctech_path/ctech_lib_nor.sv
$ctech_path/ctech_lib_or.sv
$ctech_path/ctech_lib_triplesync.sv
$ctech_path/ctech_lib_triplesync_rst.sv
$ctech_path/ctech_lib_triplesync_rstb.sv
$ctech_path/ctech_lib_triplesync_set.sv
$ctech_path/ctech_lib_triplesync_setb.sv
$ctech_path/ctech_lib_xor.sv


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/dsa_visa_rtl_lib.rtl.f
$ip/subIP/visa/rtl/dsa_visa_globals.vh
$ip/subIP/visa/rtl/dsa_visa_active_detect.sv
$ip/subIP/visa/rtl/dsa_visa_analog_clk_deskew.sv
$ip/subIP/visa/rtl/dsa_visa_analog_data_deskew.sv
$ip/subIP/visa/rtl/dsa_visa_bypass.sv
$ip/subIP/visa/rtl/dsa_visa_bypass_cr_distribution.sv
$ip/subIP/visa/rtl/dsa_visa_bypass_cr_extraction.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_4_g_s.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_4_ng_s.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_4_s.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_g.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_g_cro_s.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_g_s.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_ng.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_ng_s.sv
$ip/subIP/visa/rtl/dsa_visa_central_mux_s.sv
$ip/subIP/visa/rtl/dsa_visa_clk_mux.sv
$ip/subIP/visa/rtl/dsa_visa_clock_en_split.sv
$ip/subIP/visa/rtl/dsa_visa_clock_latch_and_en.sv
$ip/subIP/visa/rtl/dsa_visa_clock_stepdown.sv
$ip/subIP/visa/rtl/dsa_visa_config_bridge.sv
$ip/subIP/visa/rtl/dsa_visa_controller.sv
$ip/subIP/visa/rtl/dsa_visa_deserializer.sv
$ip/subIP/visa/rtl/dsa_visa_deserializer_economical_front_end.sv
$ip/subIP/visa/rtl/dsa_visa_deserializer_secure_front_end.sv
$ip/subIP/visa/rtl/dsa_visa_flop.sv
$ip/subIP/visa/rtl/dsa_visa_flop_stage.sv
$ip/subIP/visa/rtl/dsa_visa_flop_stage_w_stepdown.sv
$ip/subIP/visa/rtl/dsa_visa_gasket.sv
$ip/subIP/visa/rtl/dsa_visa_gasket_control.sv
$ip/subIP/visa/rtl/dsa_visa_gasket_lane.sv
$ip/subIP/visa/rtl/dsa_visa_gpio_clock_stepdown.sv
$ip/subIP/visa/rtl/dsa_visa_iomapper_mux_cro_s.sv
$ip/subIP/visa/rtl/dsa_visa_lane_mux.sv
$ip/subIP/visa/rtl/dsa_visa_lane_mux_slider.sv
$ip/subIP/visa/rtl/dsa_visa_mindelay_prot_latch.sv
$ip/subIP/visa/rtl/dsa_visa_mux_master.sv
$ip/subIP/visa/rtl/dsa_visa_mux_stage.sv
$ip/subIP/visa/rtl/dsa_visa_partition_mux.sv
$ip/subIP/visa/rtl/dsa_visa_partition_mux_4_ng_s.sv
$ip/subIP/visa/rtl/dsa_visa_partition_mux_4_s.sv
$ip/subIP/visa/rtl/dsa_visa_partition_mux_ng.sv
$ip/subIP/visa/rtl/dsa_visa_partition_mux_ng_cro_s.sv
$ip/subIP/visa/rtl/dsa_visa_partition_mux_ng_s.sv
$ip/subIP/visa/rtl/dsa_visa_partition_mux_ng_xcro_s.sv
$ip/subIP/visa/rtl/dsa_visa_partition_mux_s.sv
$ip/subIP/visa/rtl/dsa_visa_patgen.sv
$ip/subIP/visa/rtl/dsa_visa_reg_mapper.sv
$ip/subIP/visa/rtl/dsa_visa_reg_select.sv
$ip/subIP/visa/rtl/dsa_visa_repeater.sv
$ip/subIP/visa/rtl/dsa_visa_repeater_4_gpio_s.sv
$ip/subIP/visa/rtl/dsa_visa_repeater_4_s.sv
$ip/subIP/visa/rtl/dsa_visa_repeater_f_s.sv
$ip/subIP/visa/rtl/dsa_visa_repeater_master.sv
$ip/subIP/visa/rtl/dsa_visa_repeater_s.sv
$ip/subIP/visa/rtl/dsa_visa_serial_cfg_bus_repeater.sv
$ip/subIP/visa/rtl/dsa_visa_snapshot.sv
$ip/subIP/visa/rtl/dsa_visa_unit_mux.sv
$ip/subIP/visa/rtl/dsa_visa_unit_mux_4_rg_s.sv
$ip/subIP/visa/rtl/dsa_visa_unit_mux_4_s.sv
$ip/subIP/visa/rtl/dsa_visa_unit_mux_cro_s.sv
$ip/subIP/visa/rtl/dsa_visa_unit_mux_rg_s.sv
$ip/subIP/visa/rtl/dsa_visa_unit_mux_rt_s.sv
$ip/subIP/visa/rtl/dsa_visa_unit_mux_s.sv
$ip/subIP/visa/rtl/dsa_visa_xbar_stage.sv
$ip/subIP/visa/rtl/dsa_vase_buffer.sv


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaxc_common_rtl_lib.rtl.f
$ip/src/rtl/iax/iax_pkg.svh
$ip/src/rtl/iax/iax_widget.sv
$ip/src/rtl/iax/iax_cgc.sv
+incdir+$ip/src/rtl/common
+incdir+$ip/src/rtl/iax

$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/verif/wrappers/eip/iax/iaa3p0s64b60/iaa3p0s64b60.sv
$ip/verif/wrappers/eip/iax/iaa3p0s64b60_ip/iaa3p0s64b60_ip.sv

// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaab3p0s64b60_rtl_lib.rtl.f

// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaxb_common_rtl_lib.rtl.f
$ip/src/rtl/iax/iax_dchk.sv
+incdir+$ip/src/rtl/iax
+incdir+$ip/src/rtl/common


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/dsa_subip_rtl_lib.rtl.f
$ip/subIP/dfxsecure/source/rtl/dfxsecure_plugin/dsa_dfxsecure_plugin.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbetregsplitter.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbendpoint.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbebulkrdwrwrapper.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbemstr.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbemstrreg.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbedoserrmstr.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbebase.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbebulkrdwr.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbetrgt.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbebytecount.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbetrgtreg.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/endpoint/dsa_sbehierinsert.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcingress.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcfifo.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcglobal_params.vm
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcheaderdecoder.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcusync.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcvram2.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcusync_clk2.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcism.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcusync_clk1.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcasyncfifo_ing.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcasyncfifoixb.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcasyncclkreq.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcstruct_local.vm
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcfunc.vm
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcport.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcegress.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcasyncfifo_egr.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbccomp.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcgcgu.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcasyncfifo.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbff.sv
$ip/subIP/iosfsbc/source/rtl/iosfsbc/common/dsa_sbcinqueue.sv
$ip/subIP/pgcb/src/rtl/pgcbunit/dsa_pgcbdfxovr.sv
$ip/subIP/pgcb/src/rtl/pgcbunit/dsa_pgcbfsm.sv
$ip/subIP/pgcb/src/rtl/pgcbunit/dsa_pgcbunit.sv
$ip/subIP/genram_bees_knees/source/rtl/dsa_genram_bees_knees.sv
$ip/subIP/devtlb/src/rtl/devtlb/dsa_devtlb.sv
+incdir+$ip/subIP/dfxsecure/source/rtl/include
+incdir+$ip/subIP/dfxsecure/source/rtl/include/assertions
+incdir+$ip/subIP/genram_bees_knees/source/rtl
+incdir+$ip/subIP/iosfsbc/source/rtl/iosfsbc/common
+incdir+$ip/subIP/pgcb/src/rtl/pgcbunit
+incdir+$ip/subIP/devtlb/src/rtl/devtlb
+incdir+$ip/subIP/devtlb/src/rtl/params


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/dsa_common_rtl_lib.rtl.f
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_pgd.sv
$ip/src/rtl/top/dsa_mem.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_cfg_ctl.sv
$ip/src/rtl/top/dsa_ownership.sv
$ip/src/rtl/top/dsa_bisr.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_crp_flr.sv
$ip/src/rtl/top/dsa_crp_misc.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_clocks.sv
$ip/src/rtl/top/dsa_power_ctl.sv
$ip/src/rtl/top/dsa_power.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_resets.sv
$ip/src/rtl/top/dsa_resets_clks.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_crp.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_sb.sv
$ip/src/rtl/top/dsa_misc.sv
$ip/src/rtl/top/dsa_genram_vram_eip.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_aon_common.sv
$ip/src/rtl/dsa/dsa_cgc_old.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_command.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_enable_dev.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_enable_wq.sv
$ip/src/rtl/dsa/dsa_dchk.sv
$ip/src/rtl/dsa/dsa_idchk.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_wq.sv
$ip/src/rtl/dsa/dsa_wq_dbuf.sv
$ip/src/rtl/dsa/dsa_wq_core.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_wq_wac.sv
$ip/src/rtl/dsa/dsa_wq_ctl.sv
$ip/src/rtl/dsa/dsa_wq_wdc.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_wq_adc.sv
$ip/src/rtl/dsa/dsa_wq_arb.sv
$ip/src/rtl/dsa/dsa_wq_dfsm.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_grp_bctrl.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_cmp_buf.sv
$ip/src/rtl/dsa/dsa_cb_queue.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_wr_buf_cmd.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_wr_buf.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_ci_cmd.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_ci.sv
$ip/src/rtl/dsa/dsa_cfgreq.sv
$ip/src/rtl/dsa/dsa_msix.sv
$ip/src/rtl/dsa/dsa_ims.sv
$ip/src/rtl/dsa/dsa_intr.sv
$ip/src/rtl/dsa/dsa_pmon.sv
$ip/src/rtl/dsa/dsa_pmoncntr.sv
$ip/src/rtl/dsa/dsa_cdesc_qtrk.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_cdesc_drain.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_cdesc_top.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng_top.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng.sv
$ip/src/rtl/dsa/dsa_eng_axq.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng_dexq.sv
$ip/src/rtl/dsa/dsa_eng_ipba.sv
$ip/src/rtl/dsa/dsa_eng_sglq.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng_addrx.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng_dataf.sv
$ip/src/rtl/dsa/dsa_eng_dprdy.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng_dprdc.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng_dpwdc.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng_dcmpr.sv
$ip/src/rtl/dsa/dsa_eng_trk.sv
$ip/src/rtl/dsa/dsa_eng_desc_trk.sv
$ip/src/rtl/dsa/dsa_atc_axq.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_atc_top.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_devtlb_wrap.sv
$ip/src/rtl/dsa/dsa_atc_treq.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_atc_etrk.sv
$ip/src/rtl/dsa/dsa_atc_fsm.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_atc_areq.sv
$ip/src/rtl/dsa/dsa_atc_arsp.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_atc_inv.sv
$ip/src/rtl/dsa/dsa_desc_buf.sv
$ip/src/rtl/dsa/dsa_sg_buf.sv
$ip/src/rtl/dsa/dsa_batch_queue.sv
$ip/src/rtl/dsa/dsa_eng_sgxq.sv
$ip/src/rtl/dsa/dsa_eng_sgax.sv
$ip/src/rtl/dsa/dsa_eng_sgrd.sv
$ip/src/rtl/dsa/dsa_eng_sgwd.sv
$ip/src/rtl/dsa/dsa_eng_bexq.sv
$ip/src/rtl/dsa/dsa_eng_bdax.sv
$ip/src/rtl/dsa/dsa_eng_bdrd.sv
$ip/src/rtl/dsa/dsa_eng_bdwd.sv
$ip/src/rtl/dsa/dsa_eng_bdex.sv
$ip/src/rtl/dsa/dsa_eng_dparb.sv
$ip/src/rtl/dsa/dsa_dproc.sv
$ip/src/rtl/dsa/dsa_dproc_top.sv
$ip/src/rtl/dsa/dsa_dproc_crc.sv
$ip/src/rtl/dsa/dsa_crc32_top.sv
$ip/src/rtl/dsa/dsa_crc32_gf2_mult.sv
$ip/src/rtl/dsa/dsa_crc32_reducer.sv
$ip/src/rtl/dsa/dsa_dproc_trk.sv
$ip/src/rtl/dsa/dsa_t10_gf2_32_crc_opt.v
$ip/src/rtl/dsa/dsa_t10_gf2_partial_multi.v
$ip/src/rtl/dsa/dsa_eng_bex.sv
$ip/src/rtl/dsa/dsa_eng_sgx.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/dsa/dsa_eng_dex.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/ipi/dsa_ipi.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/ipi/dsa_ipi_gasket.sv
$ip/src/rtl/ipi/dsa_ipi_config.sv
$ip/src/rtl/ipi/dsa_ipi_credit.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/ipi/dsa_ipi_lookup.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/ipi/dsa_ipi_master.sv
$ip/src/rtl/ipi/dsa_ipi_master_q.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/ipi/dsa_ipi_target.sv
$ip/src/rtl/ipi/dsa_ipi_order.sv
$ip/src/rtl/ipi/dsa_ipi_split.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/ipi/dsa_ipi_stream.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/ipi/dsa_ipi_aer.sv
$ip/src/rtl/ipi/dsa_ipi_rr_arb.sv
$ip/src/rtl/dproc/dproc_pkg.svh
$ip/src/rtl/common/dsa_pkg.svh
$ip/src/rtl/common/dsa_iosf_pkg.svh
$ip/src/rtl/common/dsa_cfg_pkg.svh
$ip/src/rtl/common/dsa_macros.svh
$ip/src/rtl/common/dsa_rrarb.sv
$ip/src/rtl/common/dsa_rrarb2.sv
$ip/src/rtl/common/dsa_array.sv
$ip/src/rtl/common/dsa_async_fifo.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/common/dsa_cgc.sv
$ip/src/rtl/common/dsa_ism.sv
$ip/src/rtl/common/dsa_map.sv
$ip/src/rtl/common/dsa_rst_sync.sv
$ip/src/rtl/common/dsa_rst_full_sync.sv
$ip/src/rtl/common/dsa_rst_flop.sv
$ip/src/rtl/common/dsa_parity.sv
$ip/src/rtl/common/dsa_four_phase_rspr.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/sbw/dsa_sbw_prep.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/sbw/dsa_sbw_setid.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/sbw/dsa_sbw_treg.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/sbw/dsa_sbw_aer.sv
$ip/src/rtl/sbw/dsa_sbw_intx.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/sbw/dsa_sbw_pgpok.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/sbw/dsa_sbw_ltr.sv
$ip/src/rtl/sbw/dsa_sbw_ip_rdy.sv
$ip/src/rtl/sbw/dsa_sbw_sleeplvl.sv
$ip/src/rtl/sbw/dsa_sbw_iommu_seq_msg.sv
+incdir+$ip/src/rtl/common
+incdir+$ip/src/rtl/top
+incdir+$ip/src/rtl/dsa
+incdir+$ip/src/rtl/dproc
+incdir+$ip/src/rtl/ipi
+incdir+$ip/src/rtl/sbw


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaab3p0s64b60_mem_rtl_lib.rtl.f
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ebb_intf_pipeline.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ecc_decoder.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ecc_encoder.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ecc_segment_merge.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ecc_segment_split.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ecc_wrapper.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_1024x264.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_128x264.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_1536x264.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_192x264.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_256x132.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_256x248.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_256x264.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_256x28.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_256x30.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_256x546.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_256x552.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_256x96.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_32x148.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_32x46.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_32x74.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_32x84.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_384x248.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_384x54.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_384x96.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_512x60.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_512x88.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_64x104.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_64x174.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_64x38.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_64x62.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_768x44.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_768x54.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_768x86.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1rw_s0.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1rw_s0_2048x78.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_1568x264.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_224x264.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_448x248.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_448x96.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_896x54.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_gen1r1w_s0_896x86.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_logical_memory.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_logical_memory_cam.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_logical_memory_dec.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_logical_memory_wrapper.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_mem_dslp_cnt.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_mem_pwr_seq.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_memory_pmgt.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_memory_pmgt_propagate.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_memory_pmgt_propagate_snps_n6.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_memory_solution.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_memory_solution_map.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_memory_solution_ram_wrapper.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_memory_wrapper.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ms_ecc.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ms_ecc_chk_bits_ram.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_ms_pipeline.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_segment_merge.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_segment_split.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_user_defined.sv
$ip/src/rtl/memory_solution/iaab3p0s64b60/iaab3p0s64b60_intel_intc_cmo1276d4_sram_1rw_srr2_s0.sv
+incdir+$ip/src/rtl/memory_solution/iaab3p0s64b60

$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_sfi_init.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_sfi_a2f_init.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/top/dsa_sfi_f2a_init.sv
$ip/verif/wrappers/eip/iax/iaa3p0s64b60/iaab3p0s64b60.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/eip/iaa3p0s64b60/iaab3p0s64b60_ip.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/eip/iaa3p0s64b60/iaab3p0s64b60_aon.sv
$ip/src/rtl/eip/iaa3p0s64b60/iaab3p0s64b60_csr.sv
$ip/src/rtl/eip/iaa3p0s64b60/iaab3p0s64b60_mem.sv
$ip/src/codegen/iaa3p0s64b60/crflow/rtl/iaa3p0s64b60_csr_cfg.sv
$ip/src/codegen/iaa3p0s64b60/crflow/rtl/iaa3p0s64b60_csr_mem.sv
$ip/src/rtl/ipi/dsa_ipi_mcredit.sv
+incdir+$ip/src/codegen/iaa3p0s64b60/crflow/rtl
+incdir+$ip/src/rtl/dsa
+incdir+$ip/src/rtl/iax
+incdir+$ip/src/rtl/sbw
+incdir+$ip/src/rtl/eip
+incdir+$ip/src/rtl/common


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaam3p0s64b60_rtl_lib.rtl.f

// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaam3p0s64b60_mem_rtl_lib.rtl.f
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ebb_intf_pipeline.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ecc_decoder.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ecc_encoder.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ecc_segment_merge.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ecc_segment_split.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ecc_wrapper.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen1r1w_s0.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen1r1w_s0_128x66.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen1r1w_s0_144x70.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen1r1w_s0_64x66.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen2r1w_s0.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen2r1w_s0_128x66.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen2r2w_s0.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen2r2w_s0_286x28.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_intel_intc_gen2r2w_s0_40x156.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_logical_memory.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_logical_memory_cam.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_logical_memory_dec.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_logical_memory_wrapper.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_mem_dslp_cnt.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_mem_pwr_seq.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_memory_pmgt.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_memory_pmgt_propagate.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_memory_pmgt_propagate_snps_n6.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_memory_solution.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_memory_solution_map.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_memory_solution_ram_wrapper.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_memory_wrapper.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ms_ecc.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ms_ecc_chk_bits_ram.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_ms_pipeline.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_segment_merge.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_segment_split.sv
$ip/src/rtl/memory_solution/iaam3p0s64b60/iaam3p0s64b60_user_defined.sv
+incdir+$ip/src/rtl/memory_solution/iaam3p0s64b60

$ip/verif/wrappers/eip/iax/iaa3p0s64b60/iaam3p0s64b60.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/eip/iaa3p0s64b60/iaam3p0s64b60_ip.sv
$ip/src/rtl/iax/iax_main_rxtx_new.sv
$ip/src/rtl/eip/iaa3p0s64b60/iaam3p0s64b60_mem.sv
+incdir+$ip/src/rtl/eip
+incdir+$ip/src/rtl/iax
+incdir+$ip/src/rtl/common


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaas3p0s64b60_rtl_lib.rtl.f

// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/iaas3p0s64b60_mem_rtl_lib.rtl.f
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ebb_intf_pipeline.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ecc_decoder.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ecc_encoder.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ecc_segment_merge.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ecc_segment_split.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ecc_wrapper.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen1r1w_s0.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen1r1w_s0_128x66.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen1r1w_s0_144x70.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen1r1w_s0_64x66.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen2r1w_s0.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen2r1w_s0_128x66.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen2r2w_s0.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen2r2w_s0_286x28.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_intel_intc_gen2r2w_s0_40x156.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_logical_memory.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_logical_memory_cam.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_logical_memory_dec.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_logical_memory_wrapper.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_mem_dslp_cnt.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_mem_pwr_seq.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_memory_pmgt.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_memory_pmgt_propagate.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_memory_pmgt_propagate_snps_n6.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_memory_solution.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_memory_solution_map.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_memory_solution_ram_wrapper.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_memory_wrapper.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ms_ecc.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ms_ecc_chk_bits_ram.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_ms_pipeline.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_segment_merge.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_segment_split.sv
$ip/src/rtl/memory_solution/iaas3p0s64b60/iaas3p0s64b60_user_defined.sv
+incdir+$ip/src/rtl/memory_solution/iaas3p0s64b60

$ip/verif/wrappers/eip/iax/iaa3p0s64b60/iaas3p0s64b60.sv
$ip//src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/altered/src/rtl/eip/iaa3p0s64b60/iaas3p0s64b60_ip.sv
$ip/src/rtl/iax/iax_secondary_rxtx.sv
$ip/src/rtl/eip/iaa3p0s64b60/iaas3p0s64b60_mem.sv
+incdir+$ip/src/rtl/eip
+incdir+$ip/src/rtl/iax
+incdir+$ip/src/rtl/common


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/src/codegen/iaa3p0s64b60/visa/iaa3p0s64b60/visa.f


// Processing file - /nfs/site/disks/zsc7.xne_sv_0001/tgoswami/prefv4_iaa_haps/soft_enterprise_ip.CPG_DSA_C64B60_3P0/filelists/acored.rtl.f
$ip/subIP/acored/src/rtl/top/acored_top.sv
$ip/subIP/acored/src/rtl/iac_bit2byte_packer.sv
$ip/subIP/acored/src/rtl/iac_byte2dword_packer.sv
$ip/subIP/acored/src/rtl/iac_byte_expand.sv
$ip/subIP/acored/src/rtl/iac_mul_32_64.sv
$ip/subIP/acored/src/rtl/iac_crc64.sv
$ip/subIP/acored/src/rtl/iac_crc32.sv
$ip/subIP/acored/src/rtl/iac_crc32_128.sv
$ip/subIP/acored/src/rtl/iac_crc32_128_tree.sv
$ip/subIP/acored/src/rtl/iac_crc32_128_tree_1.sv
$ip/subIP/acored/src/rtl/iac_crc32_stg0.sv
$ip/subIP/acored/src/rtl/iac_crc32_stg1.sv
$ip/subIP/acored/src/rtl/iac_crc32_tree.sv
$ip/subIP/acored/src/rtl/iac_crc32_tree_1.sv
$ip/subIP/acored/src/rtl/iac_dcmp_hbuf.sv
$ip/subIP/acored/src/rtl/iac_deflate_decoder.sv
$ip/subIP/acored/src/rtl/iac_deflate_top.sv
$ip/subIP/acored/src/rtl/iac_dflt_alu.sv
$ip/subIP/acored/src/rtl/iac_dflt_cam_dist.sv
$ip/subIP/acored/src/rtl/iac_dflt_cam_dist_spec.sv
$ip/subIP/acored/src/rtl/iac_dflt_cam_len.sv
$ip/subIP/acored/src/rtl/iac_dflt_datain_buf.sv
$ip/subIP/acored/src/rtl/iac_dflt_dist_lut.sv
$ip/subIP/acored/src/rtl/iac_dflt_huff_dcd.sv
$ip/subIP/acored/src/rtl/iac_dflt_len_eb_lut.sv
$ip/subIP/acored/src/rtl/iac_dflt_ll_cam.sv
$ip/subIP/acored/src/rtl/iac_llcam_entry.sv
$ip/subIP/acored/src/rtl/iac_dflt_spec_alu.sv
$ip/subIP/acored/src/rtl/iac_dflt_nbit_alu.sv
$ip/subIP/acored/src/rtl/iac_dflt_top.sv
$ip/subIP/acored/src/rtl/iac_dflt_translate.sv
$ip/subIP/acored/src/rtl/iac_expand.sv
$ip/subIP/acored/src/rtl/iac_extract.sv
$ip/subIP/acored/src/rtl/iac_filter_input.sv
$ip/subIP/acored/src/rtl/iac_filter_pack.sv
$ip/subIP/acored/src/rtl/iac_filter_top.sv
$ip/subIP/acored/src/rtl/iac_output_aggr.sv
$ip/subIP/acored/src/rtl/iac_output_dout.sv
$ip/subIP/acored/src/rtl/iac_output_mod.sv
$ip/subIP/acored/src/rtl/iac_prle_decode.sv
$ip/subIP/acored/src/rtl/iac_rle.sv
$ip/subIP/acored/src/rtl/iac_scan.sv
$ip/subIP/acored/src/rtl/iac_select.sv
$ip/subIP/acored/src/rtl/iac_setmem.sv
$ip/subIP/acored/src/rtl/iac_setmem_large.sv
$ip/subIP/acored/src/rtl/iac_tree_cache.sv
$ip/subIP/acored/src/rtl/iac_tree_decoder.sv
$ip/subIP/acored/src/rtl/iac_crypto_top.sv
$ip/subIP/acored/src/rtl/iac_crypto_core.sv
$ip/subIP/acored/src/rtl/iac_crypto_red.sv
$ip/subIP/acored/src/rtl/iac_aes_top.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_transform128.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_transform8.sv
$ip/subIP/acored/src/rtl/iac_aes_round.sv
$ip/subIP/acored/src/rtl/iac_aes_encdec_sbox.sv
$ip/subIP/acored/src/rtl/iac_aes_xmc_32.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_inv.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_mul4x4.sv
$ip/subIP/acored/src/rtl/iac_aes_xmc_8.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_inv_transform128.sv
$ip/subIP/acored/src/rtl/iac_aes_gf4_inv_transform8.sv
$ip/subIP/acored/src/rtl/iac_aes_key_top.sv
$ip/subIP/acored/src/rtl/iac_ghash_top.sv
$ip/subIP/acored/src/rtl/iac_ghash_array.sv
$ip/subIP/acored/src/rtl/iac_aes_keygen.sv
$ip/subIP/acored/src/rtl/iac_aes_enc_sbox.sv
$ip/subIP/acored/src/rtl/rf1w1r71x2.sv
$ip/subIP/acored/src/rtl/iac_zexpand.sv
$ip/subIP/acored/src/rtl/iac_zselect.sv
$ip/subIP/acored/src/rtl/iac_zselect_v1.sv
$ip/subIP/acored/src/rtl/iac_zverify.sv
$ip/subIP/acored/src/rtl/iac_dcmp_fifo_out.sv
$ip/subIP/acored/src/rtl/iac_acored_buf.sv
$ip/subIP/acored/src/rtl/acored_eip_parity.sv
$ip/subIP/acored/src/rtl/top/acorec_top.sv
$ip/subIP/acored/src/rtl/acorec_eip_parity.sv
$ip/subIP/acored/src/rtl/iac_comp_compare.sv
$ip/subIP/acored/src/rtl/iac_comp_ht.sv
$ip/subIP/acored/src/rtl/iac_comp_la.sv
$ip/subIP/acored/src/rtl/iac_comp_lz_merge.sv
$ip/subIP/acored/src/rtl/iac_comp_top.sv
$ip/subIP/acored/src/rtl/iac_config.sv
$ip/subIP/acored/src/rtl/iac_hm_encoder.sv
$ip/subIP/acored/src/rtl/iac_rbuffer.sv
$ip/subIP/acored/src/rtl/iac_bai_buffer.sv
$ip/subIP/acored/src/rtl/rf1w1r24x8.sv
$ip/subIP/acored/src/rtl/rf1w1r66x8.sv
$ip/subIP/acored/src/rtl/iac_comp_tgen.sv
+incdir+$ip/subIP/acored/src/gen
+incdir+$ip/subIP/acored/src/rtl/common
+incdir+$ip/subIP/acored/src/rtl/include

