-f $ip/filelists/dsa_ctech.rtl.f
-f $ip/filelists/dsa_visa_rtl_lib.rtl.f
-f $ip/filelists/eip_memory_rtl_lib.rtl.f 
-f $ip/filelists/eip_megen_rtl_lib.rtl.f
-f $ip/filelists/dsab2i32b30_rtl_lib.rtl.f
-f $ip/src/codegen/dsa2i32b30/visa/dsab2i32b30/visa.f