-tree top.mtap_tapnw_taps_inst.i_mtap0
-tree top.mtap_tapnw_taps_inst.i_stap*
-tree top.Control_if
-tree top.Primary_if
-tree top.Secondary_if
-tree top.ck_pri
-tree top.ck_sec
-tree top.i_TapTestIsland

-node top.mtap_tapnw_taps_inst.i_tapnw*.ntapnw_ftap_secsel_NC
-node top.mtap_tapnw_taps_inst.i_tapnw*.ntapnw_sslv_tdo2_NC
-node top.mtap_tapnw_taps_inst.i_tapnw*.ntapnw_sslv_tdo2_en_NC
