$MODEL_ROOT/src/rtl/common/pgcb_ctech_map.sv
$MODEL_ROOT/src/rtl/pgcbunit/pgcbfsm.sv
$MODEL_ROOT/src/rtl/pgcbunit/pgcbdfxovr.sv
$MODEL_ROOT/src/rtl/pgcbunit/pgcbunit.sv
$GLOBAL_CTECH_ROOT/source/v/ctech_lib_doublesync_rstb.sv
$GLOBAL_CTECH_ROOT/source/v/ctech_lib_doublesync_setb.sv
$GLOBAL_CTECH_ROOT/source/v/ctech_lib_mux_2to1.sv
$GLOBAL_CTECH_ROOT/source/v/ctech_lib_dq.sv
$GLOBAL_CTECH_ROOT/source/v/ctech_lib_clk_gate_te.sv
$GLOBAL_CTECH_ROOT/source/v/ctech_lib_clk_buf.sv
