#!/bin/tcsh -f

set SIP_TOOL_NAME=`echo $0 | sed -e 's/.*\///'`
##############################
# UNIX Environment setup
##############################
cd  ../../../scripts
if (! $?SIP_NO_SETUP) then
  source setup -ft
endif

cd ../tools/lec/sbendpoint

############  Setting PROCESS  & TOOLS ENV ################
setenv CAD_ROOT     /p/com/eda/dt/linux_2.6.5_x86-64
setenv SYNOPSYS_DC  /p/com/eda/synopsys/designcompiler/D-2010.03-SP5
setenv DESIGN_NAME  sbendpoint
setenv KIT_PATH     /p/kits/intel/p1271/p1271_6.2.0
setenv KIT_NAME     1271
setenv LIBRARY_TYPE b12.1
setenv bname        b12

rm -rf results
mkdir  results

lec -xl -dof sbendpoint.1271.do -nogui
