# This makefile will load a local Makefile.repo if it exists
# In Makefile.repo custom recipes and overrides can be added
MAKEFILE_LOCATION ?= /p/hdk/rtl/proj_tools/projcfg/shdk74/latest
include $(MAKEFILE_LOCATION)/Makefile

