#!/bin/csh -f
setenv VERDI_HOME /remote/vtgimages/SAFE/linux64_VERDI2019.06/release-structure/verdi
#setenv LD_LIBRARY_PATH $VERDI_HOME/platform/linux64/bin/\:$LD_LIBRARY_PATH
#setenv VC_COV_LIB_PATH /remote/vtgimages/SAFE/linux64_TD_debug_Engineer/release-structure/vcs-mx/linux64/lib
make clean
make all
#./cmpTwoVdbTgl.pl -vdb1 apb_to_uart_1stopbit.vdb -vdb2 apb_uart_rx_tx.vdb -vcapp_lib ./libCmpTwoVdbTgl.so
###./cmpTwoVdbTgl.pl -vcapp_lib ./libCmpTwoVdbTgl.so -vdb1 cov_issue/pwr_1.vdb/ -vdb2 cov_issue/pwr_2.vdb/
./cmpTwoVdbTgl.pl -vcapp_lib ./libCmpTwoVdbTgl.so -vdb1 cov_issue/pwr_1.vdb/ -vdb2 cov_issue/pwr_2.vdb/ -only_port  -scope hqm_tb_top.u_hqm.par_hqm_system.hqm_system_aon_wrap.i_hqm_sif.i_hqm_sif_core.i_hqm_iosfp_core -elfile_list el.list
