#!/usr/bin/csh -f

setenv KIT_PATH /p/kits/intel/p1271/p1271_8.2.0
setenv compName sbebase
setenv SIP_LIB_TYPE  b12
setenv SIP_LIB_VERSION 4

/p/sip/utils/bin/runATPG \
   ../../../syn/syn_1271/sbebase/rdt/outputs/sbebase_atpg.final.v \
   ../../../syn/syn_1271/sbebase/rdt/outputs/sbebase_atpg.final.spf -f \
   -lib ${KIT_PATH}/stdcells/${SIP_LIB_TYPE}.${SIP_LIB_VERSION}/default/latest/mentor/un/${SIP_LIB_TYPE}_un_core.atpglib \
   -lib ${KIT_PATH}/stdcells/${SIP_LIB_TYPE}.${SIP_LIB_VERSION}/default/latest/mentor/ln/${SIP_LIB_TYPE}_ln_core.atpglib \
   -lib ${KIT_PATH}/stdcells/${SIP_LIB_TYPE}.${SIP_LIB_VERSION}/default/latest/mentor/nn/${SIP_LIB_TYPE}_nn_core.atpglib \
   -lib ${KIT_PATH}/stdcells/${SIP_LIB_TYPE}.${SIP_LIB_VERSION}/default/latest/mentor/primitives/primitive.atpglib \
   -lib ${KIT_PATH}/stdcells/${SIP_LIB_TYPE}.${SIP_LIB_VERSION}/default/latest/mentor/primitives/udp.atpglib

