#!/bin/csh -f
set category = `echo $1`;

echo "Running Category ----> " $category
set file = `echo $category | sed -e 's/\//_/g;s/\s/_/g'`
/p/hdk/rtl/proj_tools/zircon/master/2.10.07/bin/zirconQA -dssmsid 136342 -verbose   -ovf tools/zirconqa/inputs/zirconqa_overrides_2.10.ini -alias 'stap' -cat "$category" -verbose > "$IP_ROOT/tools/zirconqa/outputs/zircon_$file.log"

