#!/usr/intel/bin/tcsh
setenv MODEL_ROOT $cwd
cd $MODEL_ROOT/

\cp ace/stap_hdl.udf_bak  ace/stap_hdl.udf

simbuild -dut stap -ace_args source tools/cdc/TGL/run_cdc_1274 -ace_args- -1c -CUST TGL -1c-

\cp ace/stap_hdl.udf_default  ace/stap_hdl.udf

