#!/usr/intel/bin/tcsh
cd $MODEL_ROOT/

#Set up the environment and source appropriate environment before running the below commands
simbuild -dut stap -1c -CUST ADL -1c- -s all +s sgcdc_build -sgcdc_build "-ASSIGN -mc=sgcdc_stap_model"
simbuild -dut stap -1c -CUST ADL -1c- -s all +s sgcdc_test -sgcdc_test "-t spyglasscdc/stap/"


##Simbuild command to run SGCDC Gui is below, to check Errors. You need to run the flow once again and uncomment the below line to open GUI 
#simbuild -dut stap -1c -CUST ADL -1c- -s all +s sgcdc_test -sgcdc_test "-t spyglasscdc/stap/ -spyglass_debug"

#If not possible to open GUI in xterm, to open GUI in Konsole, use the following command,
#Osetup spyglass
#spyglass -project <prj_name.prj> &
