#!/bin/csh -f

echo "running tests in run_config_default"
echo "Status for run_config_default Follows:"                               
source $IP_ROOT/scripts/run_config_default > config_default.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_old_default"
echo "Status for run_config_old_default Follows:"                           
source $IP_ROOT/scripts/run_config_old_default > config_old_default.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_max"
echo "Status for run_config_max Follows:"                                   
source $IP_ROOT/scripts/run_config_max > config_max.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_tapnw"
echo "Status for run_config_tapnw Follows:"                                 
source $IP_ROOT/scripts/run_config_tapnw > config_tapnw.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_tapnw_with_1_tap"
echo "Status for run_config_tapnw_with_1_tap Follows:"                      
source $IP_ROOT/scripts/run_config_tapnw_with_1_tap > config_tapnw_with_1_tap.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_wtapnw_parallel"
echo "Status for run_config_wtapnw_parallel Follows:"                       
source $IP_ROOT/scripts/run_config_wtapnw_parallel > config_wtapnw_parallel.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_wtapnw_parallel_with_1_tap"
echo "Status for run_config_wtapnw_parallel_with_1_tap Follows:"            
source $IP_ROOT/scripts/run_config_wtapnw_parallel_with_1_tap > config_wtapnw_parallel_with_1_tap.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_wtapnw_serial"
echo "Status for run_config_wtapnw_serial Follows:"                         
source $IP_ROOT/scripts/run_config_wtapnw_serial > config_wtapnw_serial.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_progrst"
echo "Status for run_config_progrst Follows:"                               
source $IP_ROOT/scripts/run_config_progrst > config_progrst.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_tdo_posedge"
echo "Status for run_config_tdo_posedge Follows:"                           
source $IP_ROOT/scripts/run_config_tdo_pose_edge > config_tdo_pose_edge.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                          
echo "running tests in run_all_configs_swcomp"
echo "Status for run_all_configs_swcomp Follows:"                               
source $IP_ROOT/scripts/run_all_configs_swcomp
echo "****************************************************************"     
echo "\n\n\n\n\n"     

echo "running tests in run_all_configs_swcomp_isol_en"
echo "Status for run_all_configs_swcomp Follows:"                               
source $IP_ROOT/scripts/run_config_swcomp_isol_en
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                         
