#!/bin/csh -f

echo "running tests in run_config_default"
echo "Status for run_config_default Follows:"                               
source $IP_ROOT/scripts/run_config_default_swcomp > config_default_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_old_default"
echo "Status for run_config_old_default Follows:"                           
source $IP_ROOT/scripts/run_config_old_default_swcomp > config_old_default_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_max"
echo "Status for run_config_max Follows:"                                   
source $IP_ROOT/scripts/run_config_max_swcomp > config_max_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_tapnw"
echo "Status for run_config_tapnw Follows:"                                 
source $IP_ROOT/scripts/run_config_tapnw_swcomp > config_tapnw_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_tapnw_with_1_tap"
echo "Status for run_config_tapnw_with_1_tap Follows:"                      
source $IP_ROOT/scripts/run_config_tapnw_with_1_tap_swcomp > config_tapnw_with_1_tap_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_wtapnw_parallel"
echo "Status for run_config_wtapnw_parallel Follows:"                       
source $IP_ROOT/scripts/run_config_wtapnw_parallel_swcomp > config_wtapnw_parallel_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_wtapnw_parallel_with_1_tap"
echo "Status for run_config_wtapnw_parallel_with_1_tap Follows:"            
source $IP_ROOT/scripts/run_config_wtapnw_parallel_with_1_tap_swcomp > config_wtapnw_parallel_with_1_tap_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_wtapnw_serial"
echo "Status for run_config_wtapnw_serial Follows:"                         
source $IP_ROOT/scripts/run_config_wtapnw_serial_swcomp > config_wtapnw_serial_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
echo "running tests in run_config_progrst"
echo "Status for run_config_progrst Follows:"                               
source $IP_ROOT/scripts/run_config_progrst_swcomp > config_progrst_swcomp.log
echo "****************************************************************"     
echo "\n\n\n\n\n"                                                           
#echo "running tests in run_config_tdo_posedge"
#echo "Status for run_config_tdo_posedge Follows:"                           
#source $IP_ROOT/scripts/run_config_tdo_pose_edge_swcomp > config_tdo_pose_edge_swcomp.log
#echo "****************************************************************"     
#echo "\n\n\n\n\n"                                                           
