#!/bin/csh -f

cd $IP_ROOT
mkdir -p $IP_ROOT/pwa/sim

echo "running tests in run_config_default"
echo "Status for run_config_default Follows:"                  
source $IP_ROOT/scripts/run_config_default > config_default.log                   
echo "running tests in run_config_use1_feature1"
echo "Status for run_config_use1_feature1 Follows:"            
source $IP_ROOT/scripts/run_config_use1_feature1  >   config_use1_feature1.log          
echo "running tests in run_config_use0"
echo "Status for run_config_use0 Follows:"                     
source $IP_ROOT/scripts/run_config_use0  > config_use0.log                    
echo "running tests in run_config_use1"
echo "Status for run_config_use1 Follows:"                     
source $IP_ROOT/scripts/run_config_use1 > config_use1.log                       
echo "running tests in run_config_sideband_policy"
echo "Status for run_config_sideband_policy Follows:"          
source $IP_ROOT/scripts/run_config_sideband_policy  > config_sideband_policy.log           
