# design information
set CTECH_TYPE ec0
set CTECH_VARIANT ln

set G_REF_UPF_LIST ""
set G_TAR_UPF_LIST ""
set G_COMPARE_POWER_INTENT 0
set G_COMPARE_POWER_GRID 0
set G_COMPARE_PST 0
set G_COMPARE_POWER_CONSISTENCY 0

# flow configurations
set G_CONF_MAP 1
set G_CONF_COMPARE_TYPE "WRITE_HIER"
set G_CONF_DYNAMIC_HIER 1

set G_PRESERVE_ADDITIONAL_LINK_LIBRARIES 1

set G_FV_LP 0

set G_CONF_ANALYZE_ABORT 0
set G_CONF_DP_WORDLEVEL 0
set G_CONF_DP 1
set G_CONF_DC_RESOURCE_FILE "$env(WARD)/syn/reports/${G_DESIGN_NAME}.syn_final.resources"
