#!/bin/csh -f
echo "rm -rf ${IP_ROOT}/verif/results .acetestinfo.log ~/.ace_SB"
if ($?IP_ROOT) then
    /bin/rm -rf ${IP_ROOT}/verif/results      \
                ${IP_ROOT}/verif/.acetestinfo.log \
                ~/.ace_IOSF_SBC_*
else
    /bin/rm -rf ${IP_ROOT}/verif/results .acetestinfo.log ~/.ace_IOSF_SBC_*
endif
