#!/usr/intel/bin/tcsh
source /p/hdk/rtl/hdk.rc -cfg sip -cleanenv
source /p/hdk/rtl/hdk.rc -cfg sip
setenv MODEL_ROOT $cwd
cd $MODEL_ROOT/

source $MODEL_ROOT/tools/collage/generate_all
source $MODEL_ROOT/scripts/buildme_sgcdc 
cd $MODEL_ROOT/
