
//  INTEL CONFIDENTIAL
//
//  Copyright 2023 Intel Corporation All Rights Reserved.
//
//  The source code contained or described herein and all documents related
//  to the source code ("Material") are owned by Intel Corporation or its
//  suppliers or licensors. Title to the Material remains with Intel
//  Corporation or its suppliers and licensors. The Material contains trade
//  secrets and proprietary and confidential information of Intel or its
//  suppliers and licensors. The Material is protected by worldwide copyright
//  and trade secret laws and treaty provisions. No part of the Material may
//  be used, copied, reproduced, modified, published, uploaded, posted,
//  transmitted, distributed, or disclosed in any way without Intel's prior
//  express written permission.
//
//  No license under any patent, copyright, trade secret or other intellectual
//  property right is granted to or conferred upon you by disclosure or
//  delivery of the Materials, either expressly, by implication, inducement,
//  estoppel or otherwise. Any license under such intellectual property rights
//  must be express and approved by Intel in writing.
//

//------------------------------------------------------------------------------------------------------------------------
// Intel Proprietary        Intel Confidential        Intel Proprietary        Intel Confidential        Intel Proprietary
//------------------------------------------------------------------------------------------------------------------------
// Generated by                  : cudoming
// Generated on                  : April 18, 2023
//------------------------------------------------------------------------------------------------------------------------
// General Information:
// ------------------------------
// 2r2w0c standard array for SDG server designs.
// Behavioral modeling of a parameterized register file core with no DFX features.
// RTL is written in SystemVerilog.
//------------------------------------------------------------------------------------------------------------------------
// Detail Information:
// ------------------------------
// Addresses        : RD/WR addresses are encoded.
//                    Input addresses will be valid at the array in 1 phases after being driven.
//                    Address latency of 1 is corresponding to a B-latch.
// Enables          : RD/WR enables are used to condition the clock and wordlines.
//                  : Input enables will be valid at the array in 1 phases after being driven.
//                    Enable latency of 1 is corresponding to a B-latch.
// Write Data       : Write data will be valid at the array 2 phases after being driven.
//                    Write data latency of 2 is corresponding to a rising-edge flop. 
// Read Data        : Read data will be valid at the output of a SDL 1 phase after being read.
//                    Read data latency of 1 is corresponding to a B-latch.
// Address Offset   : 
//------------------------------------------------------------------------------------------------------------------------

//------------------------------------------------------------------------------------------------------------------------
// Other Information:
// ------------------------------
// SDG RFIP RTL Release Path:
// /p/hdk/rtl/ip_releases/shdk74/array_macro_module
//
//------------------------------------------------------------------------------------------------------------------------

////////////////////////////////////////////////////////////////
// FileName : arf156b040e2r2w0cbbehbaa4acw.v
// RAM Library Model - Top
// this module definition allows the sdl_init to be external to the atpglib 
// so that it can have a separate init attribute
////////////////////////////////////////////////////////////////

module arf156b040e2r2w0cbbehbaa4acw (
  ckrdp0, rdenp0, rdaddrp0, sdl_initp0, rddatap0, 
  ckrdp1, rdenp1, rdaddrp1, sdl_initp1, rddatap1, 
  ckwrp0, wrenp0, wraddrp0, wrdatap0, 
  ckwrp1, wrenp1, wraddrp1, wrdatap1,  
  rdaddrp0_fd, rdaddrp0_rd, 
  rdaddrp1_fd, rdaddrp1_rd, 
  wraddrp0_fd, wraddrp0_rd, wrdatap0_fd, wrdatap0_rd,
  wraddrp1_fd, wraddrp1_rd, wrdatap1_fd, wrdatap1_rd);

  //Input and output pins declarations
  input ckrdp0;
  input rdenp0;
  input [5:0] rdaddrp0;
  output [159:0] rddatap0;
  input sdl_initp0;

  input ckrdp1;
  input rdenp1;
  input [5:0] rdaddrp1;
  output [159:0] rddatap1;
  input sdl_initp1;

  input ckwrp0;
  input wrenp0; 
  input [5:0] wraddrp0;
  input [159:0] wrdatap0;

  input ckwrp1;
  input wrenp1; 
  input [5:0] wraddrp1;
  input [159:0] wrdatap1;
 
  input rdaddrp0_fd;
  input rdaddrp0_rd;

  input rdaddrp1_fd;
  input rdaddrp1_rd;

  input wraddrp0_fd;
  input wraddrp0_rd;
  input wrdatap0_fd;
  input wrdatap0_rd;

  input wraddrp1_fd;
  input wraddrp1_rd;
  input wrdatap1_fd;
  input wrdatap1_rd;

  wire [159:0] pre_rddatap0 ;
  wire sdl_initp0_i_out;
  wire ckrd_rcb_outp0;

  wire [159:0] pre_rddatap1 ;
  wire sdl_initp1_i_out;
  wire ckrd_rcb_outp1;


  //hier module
  arf156b040e2r2w0cbbehbaa4acw_hier sub_array (
     .ckrdp0           ( ckrdp0 )
    ,.rdenp0           ( rdenp0 )
    ,.rdaddrp0         ( rdaddrp0 )
    ,.pre_rddatap0     ( pre_rddatap0 )
    ,.sdl_initp0       ( sdl_initp0 )
    ,.sdl_initp0_i_out ( sdl_initp0_i_out )
    ,.ckrd_rcb_outp0   ( ckrd_rcb_outp0 )
    ,.ckrdp1           ( ckrdp1 )
    ,.rdenp1           ( rdenp1 )
    ,.rdaddrp1         ( rdaddrp1 )
    ,.pre_rddatap1     ( pre_rddatap1 )
    ,.sdl_initp1       ( sdl_initp1 )
    ,.sdl_initp1_i_out ( sdl_initp1_i_out )
    ,.ckrd_rcb_outp1   ( ckrd_rcb_outp1 )
    ,.ckwrp0           ( ckwrp0 )
    ,.wrenp0           ( wrenp0 )
    ,.wraddrp0         ( wraddrp0 )
    ,.wrdatap0         ( wrdatap0 )
    ,.ckwrp1           ( ckwrp1 )
    ,.wrenp1           ( wrenp1 )
    ,.wraddrp1         ( wraddrp1 )
    ,.wrdatap1         ( wrdatap1 )
    ,.rdaddrp0_fd      ( rdaddrp0_fd )
    ,.rdaddrp0_rd      ( rdaddrp0_rd )
    ,.rdaddrp1_fd      ( rdaddrp1_fd )
    ,.rdaddrp1_rd      ( rdaddrp1_rd )
    ,.wraddrp0_fd      ( wraddrp0_fd )
    ,.wraddrp0_rd      ( wraddrp0_rd )
    ,.wraddrp1_fd      ( wraddrp1_fd )
    ,.wraddrp1_rd      ( wraddrp1_rd )
    ,.wrdatap0_fd      ( wrdatap0_fd )
    ,.wrdatap0_rd      ( wrdatap0_rd )
    ,.wrdatap1_fd      ( wrdatap1_fd )
    ,.wrdatap1_rd      ( wrdatap1_rd )
  );

  //rddatap0
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_159 (.d(pre_rddatap0[159]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[159]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_158 (.d(pre_rddatap0[158]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[158]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_157 (.d(pre_rddatap0[157]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[157]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_156 (.d(pre_rddatap0[156]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[156]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_155 (.d(pre_rddatap0[155]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[155]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_154 (.d(pre_rddatap0[154]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[154]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_153 (.d(pre_rddatap0[153]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[153]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_152 (.d(pre_rddatap0[152]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[152]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_151 (.d(pre_rddatap0[151]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[151]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_150 (.d(pre_rddatap0[150]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[150]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_149 (.d(pre_rddatap0[149]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[149]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_148 (.d(pre_rddatap0[148]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[148]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_147 (.d(pre_rddatap0[147]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[147]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_146 (.d(pre_rddatap0[146]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[146]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_145 (.d(pre_rddatap0[145]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[145]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_144 (.d(pre_rddatap0[144]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[144]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_143 (.d(pre_rddatap0[143]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[143]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_142 (.d(pre_rddatap0[142]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[142]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_141 (.d(pre_rddatap0[141]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[141]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_140 (.d(pre_rddatap0[140]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[140]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_139 (.d(pre_rddatap0[139]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[139]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_138 (.d(pre_rddatap0[138]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[138]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_137 (.d(pre_rddatap0[137]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[137]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_136 (.d(pre_rddatap0[136]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[136]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_135 (.d(pre_rddatap0[135]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[135]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_134 (.d(pre_rddatap0[134]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[134]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_133 (.d(pre_rddatap0[133]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[133]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_132 (.d(pre_rddatap0[132]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[132]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_131 (.d(pre_rddatap0[131]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[131]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_130 (.d(pre_rddatap0[130]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[130]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_129 (.d(pre_rddatap0[129]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[129]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_128 (.d(pre_rddatap0[128]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[128]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_127 (.d(pre_rddatap0[127]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[127]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_126 (.d(pre_rddatap0[126]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[126]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_125 (.d(pre_rddatap0[125]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[125]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_124 (.d(pre_rddatap0[124]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[124]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_123 (.d(pre_rddatap0[123]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[123]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_122 (.d(pre_rddatap0[122]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[122]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_121 (.d(pre_rddatap0[121]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[121]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_120 (.d(pre_rddatap0[120]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[120]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_119 (.d(pre_rddatap0[119]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[119]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_118 (.d(pre_rddatap0[118]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[118]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_117 (.d(pre_rddatap0[117]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[117]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_116 (.d(pre_rddatap0[116]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[116]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_115 (.d(pre_rddatap0[115]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[115]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_114 (.d(pre_rddatap0[114]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[114]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_113 (.d(pre_rddatap0[113]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[113]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_112 (.d(pre_rddatap0[112]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[112]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_111 (.d(pre_rddatap0[111]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[111]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_110 (.d(pre_rddatap0[110]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[110]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_109 (.d(pre_rddatap0[109]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[109]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_108 (.d(pre_rddatap0[108]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[108]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_107 (.d(pre_rddatap0[107]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[107]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_106 (.d(pre_rddatap0[106]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[106]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_105 (.d(pre_rddatap0[105]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[105]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_104 (.d(pre_rddatap0[104]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[104]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_103 (.d(pre_rddatap0[103]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[103]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_102 (.d(pre_rddatap0[102]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[102]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_101 (.d(pre_rddatap0[101]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[101]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_100 (.d(pre_rddatap0[100]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[100]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_99 (.d(pre_rddatap0[99]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[99]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_98 (.d(pre_rddatap0[98]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[98]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_97 (.d(pre_rddatap0[97]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[97]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_96 (.d(pre_rddatap0[96]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[96]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_95 (.d(pre_rddatap0[95]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[95]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_94 (.d(pre_rddatap0[94]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[94]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_93 (.d(pre_rddatap0[93]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[93]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_92 (.d(pre_rddatap0[92]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[92]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_91 (.d(pre_rddatap0[91]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[91]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_90 (.d(pre_rddatap0[90]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[90]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_89 (.d(pre_rddatap0[89]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[89]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_88 (.d(pre_rddatap0[88]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[88]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_87 (.d(pre_rddatap0[87]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[87]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_86 (.d(pre_rddatap0[86]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[86]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_85 (.d(pre_rddatap0[85]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[85]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_84 (.d(pre_rddatap0[84]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[84]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_83 (.d(pre_rddatap0[83]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[83]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_82 (.d(pre_rddatap0[82]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[82]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_81 (.d(pre_rddatap0[81]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[81]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_80 (.d(pre_rddatap0[80]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[80]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_79 (.d(pre_rddatap0[79]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[79]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_78 (.d(pre_rddatap0[78]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[78]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_77 (.d(pre_rddatap0[77]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[77]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_76 (.d(pre_rddatap0[76]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[76]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_75 (.d(pre_rddatap0[75]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[75]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_74 (.d(pre_rddatap0[74]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[74]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_73 (.d(pre_rddatap0[73]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[73]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_72 (.d(pre_rddatap0[72]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[72]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_71 (.d(pre_rddatap0[71]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[71]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_70 (.d(pre_rddatap0[70]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[70]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_69 (.d(pre_rddatap0[69]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[69]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_68 (.d(pre_rddatap0[68]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[68]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_67 (.d(pre_rddatap0[67]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[67]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_66 (.d(pre_rddatap0[66]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[66]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_65 (.d(pre_rddatap0[65]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[65]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_64 (.d(pre_rddatap0[64]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[64]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_63 (.d(pre_rddatap0[63]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[63]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_62 (.d(pre_rddatap0[62]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[62]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_61 (.d(pre_rddatap0[61]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[61]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_60 (.d(pre_rddatap0[60]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[60]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_59 (.d(pre_rddatap0[59]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[59]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_58 (.d(pre_rddatap0[58]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[58]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_57 (.d(pre_rddatap0[57]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[57]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_56 (.d(pre_rddatap0[56]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[56]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_55 (.d(pre_rddatap0[55]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[55]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_54 (.d(pre_rddatap0[54]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[54]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_53 (.d(pre_rddatap0[53]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[53]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_52 (.d(pre_rddatap0[52]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[52]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_51 (.d(pre_rddatap0[51]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[51]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_50 (.d(pre_rddatap0[50]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[50]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_49 (.d(pre_rddatap0[49]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[49]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_48 (.d(pre_rddatap0[48]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[48]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_47 (.d(pre_rddatap0[47]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[47]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_46 (.d(pre_rddatap0[46]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[46]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_45 (.d(pre_rddatap0[45]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[45]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_44 (.d(pre_rddatap0[44]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[44]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_43 (.d(pre_rddatap0[43]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[43]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_42 (.d(pre_rddatap0[42]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[42]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_41 (.d(pre_rddatap0[41]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[41]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_40 (.d(pre_rddatap0[40]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[40]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_39 (.d(pre_rddatap0[39]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[39]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_38 (.d(pre_rddatap0[38]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[38]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_37 (.d(pre_rddatap0[37]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[37]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_36 (.d(pre_rddatap0[36]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[36]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_35 (.d(pre_rddatap0[35]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[35]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_34 (.d(pre_rddatap0[34]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[34]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_33 (.d(pre_rddatap0[33]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[33]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_32 (.d(pre_rddatap0[32]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[32]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_31 (.d(pre_rddatap0[31]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[31]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_30 (.d(pre_rddatap0[30]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[30]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_29 (.d(pre_rddatap0[29]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[29]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_28 (.d(pre_rddatap0[28]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[28]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_27 (.d(pre_rddatap0[27]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[27]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_26 (.d(pre_rddatap0[26]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[26]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_25 (.d(pre_rddatap0[25]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[25]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_24 (.d(pre_rddatap0[24]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[24]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_23 (.d(pre_rddatap0[23]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[23]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_22 (.d(pre_rddatap0[22]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[22]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_21 (.d(pre_rddatap0[21]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[21]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_20 (.d(pre_rddatap0[20]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[20]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_19 (.d(pre_rddatap0[19]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[19]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_18 (.d(pre_rddatap0[18]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[18]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_17 (.d(pre_rddatap0[17]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[17]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_16 (.d(pre_rddatap0[16]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[16]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_15 (.d(pre_rddatap0[15]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[15]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_14 (.d(pre_rddatap0[14]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[14]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_13 (.d(pre_rddatap0[13]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[13]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_12 (.d(pre_rddatap0[12]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[12]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_11 (.d(pre_rddatap0[11]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[11]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_10 (.d(pre_rddatap0[10]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[10]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_9 (.d(pre_rddatap0[9]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[9]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_8 (.d(pre_rddatap0[8]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[8]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_7 (.d(pre_rddatap0[7]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[7]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_6 (.d(pre_rddatap0[6]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[6]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_5 (.d(pre_rddatap0[5]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[5]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_4 (.d(pre_rddatap0[4]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[4]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_3 (.d(pre_rddatap0[3]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[3]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_2 (.d(pre_rddatap0[2]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[2]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_1 (.d(pre_rddatap0[1]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[1]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p0_0 (.d(pre_rddatap0[0]), .rb(sdl_initp0_i_out), .clk(ckrd_rcb_outp0), .o(rddatap0[0]));

  //rddatap1
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_159 (.d(pre_rddatap1[159]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[159]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_158 (.d(pre_rddatap1[158]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[158]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_157 (.d(pre_rddatap1[157]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[157]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_156 (.d(pre_rddatap1[156]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[156]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_155 (.d(pre_rddatap1[155]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[155]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_154 (.d(pre_rddatap1[154]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[154]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_153 (.d(pre_rddatap1[153]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[153]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_152 (.d(pre_rddatap1[152]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[152]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_151 (.d(pre_rddatap1[151]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[151]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_150 (.d(pre_rddatap1[150]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[150]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_149 (.d(pre_rddatap1[149]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[149]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_148 (.d(pre_rddatap1[148]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[148]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_147 (.d(pre_rddatap1[147]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[147]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_146 (.d(pre_rddatap1[146]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[146]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_145 (.d(pre_rddatap1[145]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[145]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_144 (.d(pre_rddatap1[144]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[144]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_143 (.d(pre_rddatap1[143]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[143]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_142 (.d(pre_rddatap1[142]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[142]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_141 (.d(pre_rddatap1[141]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[141]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_140 (.d(pre_rddatap1[140]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[140]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_139 (.d(pre_rddatap1[139]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[139]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_138 (.d(pre_rddatap1[138]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[138]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_137 (.d(pre_rddatap1[137]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[137]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_136 (.d(pre_rddatap1[136]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[136]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_135 (.d(pre_rddatap1[135]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[135]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_134 (.d(pre_rddatap1[134]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[134]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_133 (.d(pre_rddatap1[133]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[133]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_132 (.d(pre_rddatap1[132]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[132]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_131 (.d(pre_rddatap1[131]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[131]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_130 (.d(pre_rddatap1[130]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[130]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_129 (.d(pre_rddatap1[129]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[129]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_128 (.d(pre_rddatap1[128]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[128]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_127 (.d(pre_rddatap1[127]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[127]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_126 (.d(pre_rddatap1[126]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[126]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_125 (.d(pre_rddatap1[125]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[125]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_124 (.d(pre_rddatap1[124]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[124]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_123 (.d(pre_rddatap1[123]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[123]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_122 (.d(pre_rddatap1[122]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[122]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_121 (.d(pre_rddatap1[121]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[121]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_120 (.d(pre_rddatap1[120]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[120]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_119 (.d(pre_rddatap1[119]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[119]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_118 (.d(pre_rddatap1[118]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[118]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_117 (.d(pre_rddatap1[117]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[117]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_116 (.d(pre_rddatap1[116]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[116]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_115 (.d(pre_rddatap1[115]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[115]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_114 (.d(pre_rddatap1[114]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[114]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_113 (.d(pre_rddatap1[113]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[113]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_112 (.d(pre_rddatap1[112]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[112]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_111 (.d(pre_rddatap1[111]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[111]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_110 (.d(pre_rddatap1[110]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[110]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_109 (.d(pre_rddatap1[109]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[109]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_108 (.d(pre_rddatap1[108]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[108]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_107 (.d(pre_rddatap1[107]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[107]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_106 (.d(pre_rddatap1[106]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[106]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_105 (.d(pre_rddatap1[105]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[105]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_104 (.d(pre_rddatap1[104]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[104]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_103 (.d(pre_rddatap1[103]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[103]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_102 (.d(pre_rddatap1[102]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[102]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_101 (.d(pre_rddatap1[101]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[101]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_100 (.d(pre_rddatap1[100]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[100]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_99 (.d(pre_rddatap1[99]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[99]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_98 (.d(pre_rddatap1[98]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[98]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_97 (.d(pre_rddatap1[97]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[97]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_96 (.d(pre_rddatap1[96]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[96]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_95 (.d(pre_rddatap1[95]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[95]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_94 (.d(pre_rddatap1[94]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[94]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_93 (.d(pre_rddatap1[93]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[93]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_92 (.d(pre_rddatap1[92]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[92]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_91 (.d(pre_rddatap1[91]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[91]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_90 (.d(pre_rddatap1[90]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[90]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_89 (.d(pre_rddatap1[89]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[89]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_88 (.d(pre_rddatap1[88]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[88]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_87 (.d(pre_rddatap1[87]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[87]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_86 (.d(pre_rddatap1[86]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[86]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_85 (.d(pre_rddatap1[85]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[85]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_84 (.d(pre_rddatap1[84]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[84]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_83 (.d(pre_rddatap1[83]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[83]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_82 (.d(pre_rddatap1[82]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[82]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_81 (.d(pre_rddatap1[81]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[81]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_80 (.d(pre_rddatap1[80]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[80]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_79 (.d(pre_rddatap1[79]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[79]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_78 (.d(pre_rddatap1[78]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[78]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_77 (.d(pre_rddatap1[77]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[77]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_76 (.d(pre_rddatap1[76]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[76]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_75 (.d(pre_rddatap1[75]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[75]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_74 (.d(pre_rddatap1[74]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[74]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_73 (.d(pre_rddatap1[73]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[73]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_72 (.d(pre_rddatap1[72]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[72]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_71 (.d(pre_rddatap1[71]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[71]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_70 (.d(pre_rddatap1[70]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[70]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_69 (.d(pre_rddatap1[69]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[69]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_68 (.d(pre_rddatap1[68]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[68]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_67 (.d(pre_rddatap1[67]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[67]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_66 (.d(pre_rddatap1[66]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[66]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_65 (.d(pre_rddatap1[65]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[65]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_64 (.d(pre_rddatap1[64]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[64]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_63 (.d(pre_rddatap1[63]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[63]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_62 (.d(pre_rddatap1[62]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[62]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_61 (.d(pre_rddatap1[61]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[61]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_60 (.d(pre_rddatap1[60]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[60]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_59 (.d(pre_rddatap1[59]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[59]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_58 (.d(pre_rddatap1[58]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[58]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_57 (.d(pre_rddatap1[57]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[57]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_56 (.d(pre_rddatap1[56]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[56]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_55 (.d(pre_rddatap1[55]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[55]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_54 (.d(pre_rddatap1[54]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[54]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_53 (.d(pre_rddatap1[53]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[53]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_52 (.d(pre_rddatap1[52]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[52]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_51 (.d(pre_rddatap1[51]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[51]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_50 (.d(pre_rddatap1[50]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[50]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_49 (.d(pre_rddatap1[49]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[49]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_48 (.d(pre_rddatap1[48]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[48]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_47 (.d(pre_rddatap1[47]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[47]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_46 (.d(pre_rddatap1[46]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[46]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_45 (.d(pre_rddatap1[45]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[45]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_44 (.d(pre_rddatap1[44]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[44]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_43 (.d(pre_rddatap1[43]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[43]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_42 (.d(pre_rddatap1[42]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[42]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_41 (.d(pre_rddatap1[41]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[41]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_40 (.d(pre_rddatap1[40]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[40]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_39 (.d(pre_rddatap1[39]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[39]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_38 (.d(pre_rddatap1[38]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[38]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_37 (.d(pre_rddatap1[37]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[37]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_36 (.d(pre_rddatap1[36]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[36]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_35 (.d(pre_rddatap1[35]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[35]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_34 (.d(pre_rddatap1[34]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[34]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_33 (.d(pre_rddatap1[33]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[33]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_32 (.d(pre_rddatap1[32]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[32]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_31 (.d(pre_rddatap1[31]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[31]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_30 (.d(pre_rddatap1[30]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[30]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_29 (.d(pre_rddatap1[29]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[29]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_28 (.d(pre_rddatap1[28]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[28]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_27 (.d(pre_rddatap1[27]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[27]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_26 (.d(pre_rddatap1[26]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[26]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_25 (.d(pre_rddatap1[25]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[25]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_24 (.d(pre_rddatap1[24]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[24]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_23 (.d(pre_rddatap1[23]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[23]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_22 (.d(pre_rddatap1[22]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[22]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_21 (.d(pre_rddatap1[21]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[21]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_20 (.d(pre_rddatap1[20]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[20]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_19 (.d(pre_rddatap1[19]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[19]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_18 (.d(pre_rddatap1[18]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[18]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_17 (.d(pre_rddatap1[17]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[17]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_16 (.d(pre_rddatap1[16]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[16]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_15 (.d(pre_rddatap1[15]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[15]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_14 (.d(pre_rddatap1[14]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[14]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_13 (.d(pre_rddatap1[13]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[13]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_12 (.d(pre_rddatap1[12]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[12]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_11 (.d(pre_rddatap1[11]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[11]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_10 (.d(pre_rddatap1[10]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[10]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_9 (.d(pre_rddatap1[9]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[9]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_8 (.d(pre_rddatap1[8]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[8]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_7 (.d(pre_rddatap1[7]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[7]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_6 (.d(pre_rddatap1[6]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[6]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_5 (.d(pre_rddatap1[5]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[5]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_4 (.d(pre_rddatap1[4]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[4]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_3 (.d(pre_rddatap1[3]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[3]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_2 (.d(pre_rddatap1[2]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[2]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_1 (.d(pre_rddatap1[1]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[1]));
  arf156b040e2r2w0cbbehbaa4acw_latch_func data_out_p1_0 (.d(pre_rddatap1[0]), .rb(sdl_initp1_i_out), .clk(ckrd_rcb_outp1), .o(rddatap1[0]));

endmodule

module arf156b040e2r2w0cbbehbaa4acw_latch_func ( clk, d, rb, o );
input clk;
input d;
input rb;
output o;
wire o_tmp;

       arf156b040e2r2w0cbbehbaa4acw_lat_mem latch_inst ( o_tmp, d, rb, clk );
       assign #1 o = o_tmp;

endmodule

// async-reset active-high latch.
primitive arf156b040e2r2w0cbbehbaa4acw_lat_mem (o, d, rb, clk, notifier);
    output o;
    reg    o;
    input  d, rb, clk, notifier;

    table
    //  d   rb   clk   notifier :  ot  :   ot+1
        ?    1     0    ?        :  ?   :    - ;  // clock disabled
        ?    0     ?    ?        :  ?   :    0 ;  // async reset
        0    ?     1    ?        :  ?   :    0 ;  //clock enabled
        1    1     1    ?        :  ?   :    1 ;  //transparent data
        0    ?     x    ?        :  0   :    0 ;  // Reducing pessimism.
        1    1     x    ?        :  1   :    1 ;
        ?    x     0    ?        :  0   :    0 ;
        ?    ?     ?    *        :  ?   :    x ;  //notifier
   endtable
endprimitive
