#!/bin/tcsh -f

#####################################
#                                   #
#     Clean backend data area       #
#                                   #
#####################################
echo "### Cleaning all router designs from source/rtl/iosfsbc/* areas"
if (-d "../../source/rtl/iosfsbc/router" ) then
/usr/bin/find ../../source/rtl/iosfsbc/router -type f ! \( -iname "sbcarbiter.sv" -o -iname "sbcpwrgt.sv" -o -iname "sbcvirtport.sv" -o -iname "sbcclkgaterst.sv" -o -iname "sbcxbarbiter.sv" -o -iname "sbcegressarb.sv" -o -iname "sbcxbportarb.sv" \) -exec /bin/rm -f {} \;
endif

if ( -d "../../tools" ) then
   echo "### Cleaning all previous tools/syn/* areas"
   if ( -d "../../tools/syn" ) then
      if ( -d "../../tools/syn/syn_1271" ) then
         /usr/bin/find ../../tools/syn/syn_1271/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if ( -d "../../tools/syn/syn_1271/sbendpoint/rdt" && -d "../../tools/syn/syn_1271/sbebase/rdt") then
            /usr/bin/find ../../tools/syn/syn_1271/sbendpoint/rdt/ -mindepth 1 -maxdepth 1 -type d -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1271/sbendpoint/rdt/ -mindepth 1 -maxdepth 1 -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1271/sbebase/rdt/ -mindepth 1 -maxdepth 1 -type d -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1271/sbebase/rdt/ -mindepth 1 -maxdepth 1 -not -iname "scripts" -exec /bin/rm -rf {} \;
         endif
      endif
      if ( -d "../../tools/syn/syn_1273" ) then
         /usr/bin/find ../../tools/syn/syn_1273/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if ( -d "../../tools/syn/syn_1273/sbendpoint/rdt" && -d "../../tools/syn/syn_1273/sbebase/rdt") then
            /usr/bin/find ../../tools/syn/syn_1273/sbendpoint/rdt/ -mindepth 1 -maxdepth 1 -type d -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1273/sbendpoint/rdt/ -mindepth 1 -maxdepth 1 -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1273/sbebase/rdt/ -mindepth 1 -maxdepth 1 -type d -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1273/sbebase/rdt/ -mindepth 1 -maxdepth 1 -not -iname "scripts" -exec /bin/rm -rf {} \;
         endif
      endif
      if ( -d "../../tools/syn/syn_1274" ) then
         /usr/bin/find ../../tools/syn/syn_1274/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if ( -d "../../tools/syn/syn_1274/sbendpoint/rdt" && -d "../../tools/syn/syn_1274/sbebase/rdt") then
            /usr/bin/find ../../tools/syn/syn_1274/sbendpoint/rdt/ -mindepth 1 -maxdepth 1 -type d -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1274/sbendpoint/rdt/ -mindepth 1 -maxdepth 1 -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1274/sbebase/rdt/ -mindepth 1 -maxdepth 1 -type d -not -iname "scripts" -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/syn/syn_1274/sbebase/rdt/ -mindepth 1 -maxdepth 1 -not -iname "scripts" -exec /bin/rm -rf {} \;
         endif
      endif
    endif

   echo "### Cleaning LINT files tools/lintra/* areas"
   if ( -d "../../tools/lintra" ) then
      /usr/bin/find ../../tools/lintra/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -and -not -iname "HDK" -exec /bin/rm -rf {} \;
   endif

   echo "### Cleaning CDC files tools/cdc/tests/* areas"
   if ( -d "../../tools/cdc" ) then
      if ( -d "../../tools/cdc/tests" ) then
         /usr/bin/find ../../tools/cdc/tests/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
      endif 
      /bin/rm -rf ../../tools/cdc/results
   endif

   echo "### Cleaning ATPG files tools/atpg/* areas"
   if ( -d "../../tools/atpg" ) then
      if ( -d "../../tools/atpg/atpg_1271" ) then
         /usr/bin/find ../../tools/atpg/atpg_1271/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if ( -d "../../tools/atpg/atpg_1271/sbendpoint" && -d "../../tools/atpg/atpg_1271/sbebase") then
            /usr/bin/find ../../tools/atpg/atpg_1271/sbendpoint -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/atpg/atpg_1271/sbebase -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
         endif
      endif
      if (-d "../../tools/atpg/atpg_1273" ) then
         /usr/bin/find ../../tools/atpg/atpg_1273/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if (-d "../../tools/atpg/atpg_1273/sbendpoint" && -d "../../tools/atpg/atpg_1273/sbebase") then
            /usr/bin/find ../../tools/atpg/atpg_1273/sbendpoint -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/atpg/atpg_1273/sbebase -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
         endif
      endif
      if (-d "../../tools/atpg/atpg_1274" ) then
         /usr/bin/find ../../tools/atpg/atpg_1274/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if (-d "../../tools/atpg/atpg_1274/sbendpoint" && -d "../../tools/atpg/atpg_1274/sbebase") then
            /usr/bin/find ../../tools/atpg/atpg_1274/sbendpoint -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/atpg/atpg_1274/sbebase -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
         endif
      endif
    endif

   echo "### Cleaning LEC files tools/lec/* areas"
   if (-d "../../tools/lec" ) then
      if (-d "../../tools/lec/lec_1271" ) then
         /usr/bin/find ../../tools/lec/lec_1271/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if (-d "../../tools/lec/lec_1271/sbendpoint" && -d "../../tools/lec/lec_1271/sbebase") then
            /usr/bin/find ../../tools/lec/lec_1271/sbendpoint -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/lec/lec_1271/sbebase -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
         endif
      endif
      if (-d "../../tools/lec/lec_1273" ) then
         /usr/bin/find ../../tools/lec/lec_1273/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if (-d "../../tools/lec/lec_1273/sbendpoint" && -d "../../tools/lec/lec_1273/sbebase") then
            /usr/bin/find ../../tools/lec/lec_1273/sbendpoint -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/lec/lec_1273/sbebase -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
         endif
      endif
      if (-d "../../tools/lec/lec_1274" ) then
         /usr/bin/find ../../tools/lec/lec_1274/ -mindepth 1 -maxdepth 1 -type d -not -iname "sbendpoint" -and -not -iname "sbebase" -exec /bin/rm -rf {} \;
         if (-d "../../tools/lec/lec_1274/sbendpoint" && -d "../../tools/lec/lec_1274/sbebase") then
            /usr/bin/find ../../tools/lec/lec_1274/sbendpoint -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
            /usr/bin/find ../../tools/lec/lec_1274/sbebase -mindepth 1 -maxdepth 1 -type d -exec /bin/rm -rf {} \;
         endif
      endif
    endif

echo "### Cleaning sbr.array file"
/usr/bin/find . -mindepth 1 -maxdepth 1 -name "sbr.array" -exec /bin/rm -rf {} \;


echo "### Cleaning all previous tools/logs/* areas"
if (-d "../../tools/logs" ) then
/bin/rm  -f ../../tools/logs/*
endif

echo "### Cleaning UPF files from tools/upf/router"
if (-d "../../tools/upf/router" ) then
/usr/bin/find ../../tools/upf/router -mindepth 1 -maxdepth 1 -iname "*.upf" -exec /bin/rm -rf {} \;
/usr/bin/find ../../tools/upf/router -mindepth 1 -maxdepth 1 -iname "run_*" -exec /bin/rm -rf {} \;
endif

echo "### Cleaning tools/visa area"
if (-d "../../tools/visa" ) then

# Find and remove all the Endpoint runs
/usr/bin/find ../../tools/visa -maxdepth 1 -type d -name "run_*" -exec /bin/rm -rf {} \;

if (-d "../../tools/visa/router" ) then
/usr/bin/find ../../tools/visa/router -mindepth 1 -maxdepth 1 -iname "*visa.cfg" -exec /bin/rm -rf {} \;
endif

if (-d "../../tools/visa/run" ) then
/usr/bin/find ../../tools/visa/run -name "*.cfg.visa" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/run -name "*.v" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/run -name "*.sv" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/run -name "*.cfg" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/run -name "*.log" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/run -name "*.xml" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/run -name ".visa_commit" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/run -name "*.f" -exec /bin/rm -f {} \;
endif

if (-d "../../tools/visa/sim" ) then
/usr/bin/find ../../tools/visa/sim -name "*.log" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/sim -name "ucli.key" -exec /bin/rm -f {} \;
/usr/bin/find ../../tools/visa/sim -maxdepth 1 -name "simv.*" -exec /bin/rm -rf {} \;
/usr/bin/find ../../tools/visa/sim -maxdepth 1 -name "csrc" -exec /bin/rm -rf {} \;
endif

/usr/bin/find ../../tools/visa -name "*.sv_visaInserted" -exec /bin/rm -f {} \;
endif

echo "### Cleaning all scripts from the tools area"
/usr/bin/find ../../tools/ -maxdepth 1 -iname "*_run*" -exec /bin/rm -f {} \;
endif

echo "### Cleaning template files from the unsupported/export directory"
if (-d "../../unsupported/export" ) then
/usr/bin/find ../../unsupported/export/ -maxdepth 1 -name "*_run_*" -exec /bin/rm -f {} \;
/usr/bin/find ../../unsupported/export/ -maxdepth 1 -name "*.tcl" -exec /bin/rm -f {} \;
/usr/bin/find ../../unsupported/export/ -maxdepth 1 -name "*.stcl" -exec /bin/rm -f {} \;
/usr/bin/find ../../unsupported/export/ -maxdepth 1 -name "*.list" -exec /bin/rm -f {} \;
/usr/bin/find ../../unsupported/export/ -maxdepth 1 -name "*setup_synthesis" -exec /bin/rm -f {} \;
/usr/bin/find ../../unsupported/export/ -maxdepth 1 -name "iosf_sbc_rtr.hdl" -exec /bin/rm -f {} \;
endif

echo "### Cleaning template files from the unsupported/gen/sbccfg executable"
if (-d "../../unsupported/gen" ) then
/usr/bin/find ../../unsupported/gen/ -maxdepth 1 -name "sbccfg" -exec /bin/rm -f {} \;
endif

echo "### Cleaning generated files from verif/tb/top_tb"
if (-d "../../verif/tb" ) then
/usr/bin/find ../../verif/tb/ -maxdepth 1 -name "top_tb" -exec /bin/rm -rf {} \;
endif


echo "### Cleaning files generated in the scripts/qa directory"
/usr/bin/find . -maxdepth 1 -name "sbr.value" -exec /bin/rm -rf {} \;


#echo "### Calling get_compName.pl"
#./get_compName.pl -conf=${SIP_CONF_NAME}

