#file_type internal
-lib DWARE ./stap/stap/SPY_DW_WORK/SPY_PRECOMPILED_LIBS/DWARE
-lib DW01 ./stap/stap/SPY_DW_WORK/SPY_PRECOMPILED_LIBS/DW_LIBS_ALL
-lib DW02 ./stap/stap/SPY_DW_WORK/SPY_PRECOMPILED_LIBS/DW_LIBS_ALL
-lib DW03 ./stap/stap/SPY_DW_WORK/SPY_PRECOMPILED_LIBS/DW_LIBS_ALL
-lib DW04 ./stap/stap/SPY_DW_WORK/SPY_PRECOMPILED_LIBS/DW_LIBS_ALL
-lib DW05 ./stap/stap/SPY_DW_WORK/SPY_PRECOMPILED_LIBS/DW_LIBS_ALL
-lib DW06 ./stap/stap/SPY_DW_WORK/SPY_PRECOMPILED_LIBS/DW_LIBS_ALL
