#!/bin/csh -f
rm -rf $IP_ROOT/$1

\cp $IP_ROOT/tools/svtb_lintra/ace_static_check.lintra.cfg $IP_ROOT/tools/lint/ace_static_check.lintra.cfg

unsetenv LINTRA
unsetenv LINTRA_VER
unsetenv LIRA
unsetenv LIRA_VER
unsetenv LINTRARULES
setenv LINTRA /p/com/eda/dt/linux_2.6.5_x86-64/lintra/15.2_prw31_shOpt64
setenv LINTRA_VER 15.2_prw31_shOpt64
source $LINTRA/bin/setup
setenv LIRA_VER 15.2_prw31_64
setenv LINTRARULES /p/com/eda/intel/Soc_Lintra_Collaterals/15.14.0

ace -ccolt -pwa $1 -lira_compile_opts "-mfcu -vcs" -lt_g="svtb" -lira_use_filter "Identity" |& tee $MODEL_ROOT/ace_ccolt.log
#ace -sc -t svtb/stap -pwa $1 -lira_use_filter Identity -trsd svtb_lint


if(-e $MODEL_ROOT/ace_ccolt.log) then
     set ccpassed = `grep -c -w "FAIL" $MODEL_ROOT/ace_ccolt.log`
     set ccerror = `grep -c -w "ERROR" $MODEL_ROOT/ace_ccolt.log`
     if( ($ccpassed != 0) || ($ccerror != 0) ) then
         echo "\n\n***** Compilation FAILED *****"
         exit 1
     else
         echo "\n\n***** Compilation PASSED *****"
 ace -sc -t svtb/stap  -pwa $1 -lira_use_filter Identity -trsd svtb_lint |& tee $MODEL_ROOT/ace_sc.log
  

     endif
 endif


 if(-e $MODEL_ROOT/ace_sc.log) then
     set scpass = `grep -c -w "CompilerFatal"  $MODEL_ROOT/ace_sc.log`
	 if ($scpass != 0) then
         echo "\n\n**Elaboration Fails with Compiler FATALS **\n \n"
		 exit 1

     else
         echo "\n\n ** Elaboration Passes without any Compiler FATALS ** \n\n"

     endif
	 endif


\cp $IP_ROOT/$1/results/tests/svtb_lint/svtb_stap/top.lintra.violations $IP_ROOT/tools/svtb_lintra/StapTop.lintra.violations
\cp $IP_ROOT/$1/results/tests/svtb_lint/svtb_stap/top_violations.xml $IP_ROOT/tools/svtb_lintra/StapTop_violations.xml
\cp $IP_ROOT/$1/results/tests/svtb_lint/svtb_stap/svtb_stap*.log $IP_ROOT/tools/svtb_lintra/run_svtb_lintra.log
\cp $IP_ROOT/$1/results/tests/svtb_lint/svtb_stap/lintra.filelist $IP_ROOT/tools/svtb_lintra/

\cp $IP_ROOT/tools/svtb_lintra/ace_static_check.lintra_default.cfg $IP_ROOT/tools/lint/ace_static_check.lintra.cfg

#git co $MODEL_ROOT/tools/lint/ace_static_check.lintra.cfg


#if(-e $IP_ROOT/tools/svtb_lintra/run_svtb_lintra.log) then
 #   set pass = `grep -c -w "Lint status PASSED" $IP_ROOT/tools/svtb_lintra/run_svtb_lintra.log`
  #  if($pass == 0) then
   #     echo "\n\nLint status FAILED"
    #    exit 1
    #else
     #   echo "\n\nLint status PASSED"
    #endif
#endif
