#!/bin/csh -f
\cp $IP_ROOT/tools/svtb_lintra/ace_static_check.lintra.cfg $IP_ROOT/tools/lint/ace_static_check.lintra.cfg

unsetenv LINTRA
unsetenv LINTRA_VER
unsetenv LIRA
unsetenv LIRA_VER
unsetenv LINTRARULES
setenv LINTRA /p/com/eda/dt/linux_2.6.5_x86-64/lintra/15.2_prw31_shOpt64
setenv LINTRA_VER 15.2_prw31_shOpt64
source $LINTRA/bin/setup
setenv LIRA_VER 15.2_prw31_64
setenv LINTRARULES /p/com/eda/intel/Soc_Lintra_Collaterals/15.14.0

lintra_gui
