#!/bin/csh -f
#Script by badithya
#Usage technique.
#Example: source scripts/jtagbfm_version_update "/nfs/iind/badithya/disks"


set prefix=$1

setenv MODEL_ROOT $cwd
cd $MODEL_ROOT/
sed -i "s|.*setenv JTAG_BFM_VER.*|setenv JTAG_BFM_VER $prefix  |g"  cfg/ace/templates/custom_post.env.template



