#! usr/bin/tcsh
cd $IP_ROOT
//rm -rf pwa/results .acetestinfo.log

\cp source/rtl/include/configs/stap_params_include_max_swcomp.inc     source/rtl/include/stap_params_include.inc
\cp verif/tb/include/configs/tb_param_max_swcomp.inc                 verif/tb/include/tb_param.inc            
\cp verif/tb/include/configs/STapTop_swcomp_isol_en.sv         verif/tb/STapTop.sv  

ace -cc -epi -epa -pwa pwa_swcomp_isol_en
ace -x Rd_tdr_isol_en_test \
-pwa pwa_swcomp_isol_en -nb -nbmon

grep -ir status pwa/results/tests/*/postsim.log

