#!/usr/intel/bin/tcsh
#desc: source  uniquifyme <prefix>
#source  uniquifyme for STAP IP
#Author : Mahesh Kota
#Date   : 07-Jul-2016
set prefix=$1 
set ipname=$2
set collage_ver=$3

set work_dir=`pwd`
# since this script is written for ICL, we have hardcoded to ICL as cust
setenv ONECFG_CUST ICL
if( $prefix == "" ) then
    echo "Error:You must specify a prefix"
    echo "uniquifyme <prefix>"
    exit 1
endif

set ip_model_root = `find . -name stap.sv | head -n 1`
#set ip_root_dir = `realpath $ip_model_root | perl -pe 's/source\/rtl\/stap\/stap.sv//'`
set ip_root_dir = `realpath $ip_model_root | perl -pe 's/source\/rtl\/stap\/stap.sv//'`
setenv MODEL_ROOT $ip_root_dir
setenv IP_ROOT $MODEL_ROOT
setenv RTL_PROJ_TOOLS /p/hdk/rtl/proj_tools
set uniquify_version = "16.04.02"
set uniquify_path = "$RTL_PROJ_TOOLS/uniquify/$uniquify_version"

# uniquify script has hardcoded paths to src and we have source, just can't win
# so create a temporary link to src and then remove it when done
$uniquify_path/uniquify -top  $prefix \
                        -dirs source+subIP/DfxSecurePlugin/source/rtl/ \
                        -prefix $prefix -nogitmv -rtl_libs scripts/liblist -skiplist obsolete+tools/cdc


echo "-------------------------------------------------"
echo "Info:Finished Uniquifing RTL files with prefix: $prefix"
echo "Info:Starting Uniquifing  TB_TOP  with  prefix: $prefix"
echo "-------------------------------------------------"

#sed -i "s/'stap'/$prefix\'_stap'/g"                         cfg/ToolData.pm
sed -i "s/stap/$prefix\_stap/g"                             verif/tb/STapTop.sv
sed -i "s/\<stap\>/$prefix\_stap/g"                         tools/collage/Makefile
sed -i "s/\<IpBuilder_stap\>/IpBuilder_$prefix\_stap/g"     tools/collage/Makefile
mv tools/collage/build/builder.stap.tcl                        tools/collage/build/builder.$prefix\_stap.tcl

sed -i "s/stap_cdc_lib.stap/stap_cdc_lib.$prefix\_stap/" tools/cdc/tests/cdc_test_stap/cdc_test_stap.opt
\cp ace/stap_hdl.udf  ace/stap_hdl.udf_bak
perl -ne 'if( /\$PROJECT/ ) { s/(stap)/'$prefix'_$1/; print; } else { print; }' ace/stap_hdl.udf > t ;         mv -f t ace/stap_hdl.udf
\cp ace/stap_hdl.udf  ace/stap_hdl.udf_default
perl -ne 'if( /ip_name/ & !(/_ip_name_/)) { s/(stap)/'$prefix'_$1/; print; } else { print; }' tools/collage/build/builder.$prefix\_stap.tcl > t ; mv -f t tools/collage/build/builder.$prefix\_stap.tcl

#Shrinidhi adding to test sgcdc#
sed -i "s/stap_rtl_lib.stap/stap_rtl_lib.$prefix\_stap/g"            verif/tests/spyglasscdc/stap/stap.opt
sed -i "s/dnc_param stap/dnc_param $prefix\_stap/g"            verif/tests/spyglasscdc/stap/stap.opt


perl -ne 'if( /current_design/ ) { s/(stap)/'$prefix'_$1/; print; } else { print; }' tools/spyglass_cdc/stap/stap.sgdc > t ; mv -f t tools/spyglass_cdc/stap/stap.sgdc 
   
perl -ne 'if( /ACE_PROJECT/ ) { s/(stap)/'$prefix'_$1/; print; } else { print; }' cfg/ace/templates/custom_post.env.template > t ; mv -f t cfg/ace/templates/custom_post.env.template

perl -ne 'if( /stap =>/ ) { s/(stap)/'$prefix'_$1/; print; } else { print; }' ace/stap.acerc > t ; mv -f t ace/$prefix\_stap.acerc  
perl -ne 'if( /stap =>/ ) { s/(stap)/'$prefix'_$1/; print; } else { print; }' cfg/ace/stap/stap.acerc > t ; mv -f t cfg/ace/stap/$prefix\_stap.acerc  

perl -ne 'if( /\$PROJECT/ ) { s/(stap)/'$prefix'_$1/; print; } else { print; }' ace/stap_local_ivars.udf > t ; mv -f t ace/stap_local_ivars.udf

echo "-------------------------------------------------"
echo "Info:Finished Uniquifing TB & collage files with prefix: $prefix"
echo "-------------------------------------------------"
cd $MODEL_ROOT
