//------------------------------------------------------------------------------
//  %header_copyright%
//
//  Collateral Description:
//  dteg-stap
//
//  Source organization:
//  DTEG Engineering Group (DTEG)
//
//  Support Information:
//  HSD: https://hsdes.intel.com/appstore/article/#/dft_services.bugeco/create
//
//  Revision:
//  DTEG_sTAP_2020WW05_RTL1P0_PIC6_V1
//
//  Module <sTAP> :  < put your functional description here in plain text >
//
//------------------------------------------------------------------------------

//----------------------------------------------------------------------
// Intel Proprietary -- Copyright 2020 Intel -- All rights reserved
//----------------------------------------------------------------------
// NOTE: Log history is at end of file.
//----------------------------------------------------------------------
//
//    FILENAME    : stap_defines_include.sv
//    DESIGNER    : Rakesh Kandula
//    PROJECT     : sTAP
//
//    PURPOSE     : Declaration of `defines
//    DESCRIPTION :
//       User defined `defines. Please refer User Manual for examples.
//----------------------------------------------------------------------
   // *********************************************************************
   // `defines - sTAP
   // *********************************************************************
   `define DFX_ASSERTIONS
   `define DFX_PARAMETER_CHECKER
   //`define DFX_FPV_ENABLE
   //`define FEV
