$ip/subIP/signal_driver/source/signal_driver_pkg.sv
$ip/subIP/signal_driver/source/signal_driver_if.sv
$ip/subIP/signal_driver/source/signal_driver_ti.sv
$ip/source/env/chassis_reset_pkg.sv
$ip/source/tb/chassis_ti.sv
$ip/source/tb/chassis_rst_misc_ti.sv
$ip/source/tb/chassis_misc_if.sv
$ip/source/tb/chassis_group_rst_if.sv
$ip/source/tb/chassis_group_rst_ti.sv
$ip/source/tb/chassis_powergood_rst_if.sv
$ip/source/tb/chassis_deep_rst_if.sv
+incdir+$OVM_HOME/src
+incdir+$UVM_HOME/src
+incdir+$XVM_HOME/src
+incdir+$SAOLA_HOME/verilog
+incdir+$ip/
+incdir+$ip/subIP/signal_driver/source/
+incdir+$ip/source/env
