//------------------------------------------------------------------------------
//  %header_copyright%
//
//  Collateral Description:
//  %header_collateral%
//
//  Source organization:
//  %header_organization%
//
//  Support Information:
//  %header_support%
//
//  Revision:
//  %header_tag%
//
//  Module <dfxsecure_plugin> :  < put your functional description here in plain text >
//
//------------------------------------------------------------------------------

//----------------------------------------------------------------------
// Intel Proprietary -- Copyright 2015 Intel -- All rights reserved
//----------------------------------------------------------------------
// NOTE: Log history is at end of file.
//----------------------------------------------------------------------
//
//    FILENAME    : dfxsecure_defines_include.sv
//    DESIGNER    : Krishnadas B Bhagwat
//    PROJECT     : dfxsecure_plugin
//
//
//    PURPOSE     : Declaration of `defines
//    DESCRIPTION :
//       User defined `defines. Please refer User Manual for examples.
//----------------------------------------------------------------------
   // *********************************************************************
   // `defines - DSP
   // *********************************************************************
   `define DFX_ASSERTIONS
   `define DFX_PARAMETER_CHECKER
   //`define DFX_FPV_ENABLE
   //`define FEV
