#!/bin/csh -f
set rule = $1;
echo "Running Rule ----> " $rule 
set file = `echo $rule | sed -e 's/\//_/g;s/\s/_/g'`
/p/hdk/rtl/proj_tools/zircon/master/2.10.07/bin/zirconQA -ipconfigid 88364 -dssmsid 125017 -alias dfxsecure_plugin -ovf tools/zirconqa/inputs/zirconqa_overrides_2.10.ini -verbose -rule "$rule" -verbose -rule "$rule" -verbose > "$IP_ROOT/tools/zirconqa/outputs/zircon_$file.log"

