+incdir+$UVM_HOME/src
+incdir+$SAOLA_HOME/verilog
+incdir+$SAOLA_HOME/verilog_uvm
+incdir+$ip/verif/tb/devtlb
+incdir+$ip/verif/tb/env
+incdir+$ip/verif/tb/env/common
+incdir+$ip/verif/ti
+incdir+$ip/src/rtl/common
$ip/verif/ti/DsaTIPkg.sv
$ip/verif/ti/dsa_clkgen_if.sv
$ip/verif/ti/dsa_if.sv
$ip/verif/ti/dsa_ti.sv
$ip/verif/ti/dsa_cxl_ti.sv
$ip/verif/ti/dsa_sfi_ti.sv
$ip/verif/ti/dsa_base_rtl_if.sv
$ip/verif/ti/iax_base_rtl_if.sv
$ip/verif/ti/iax_primary_rtl_if.sv
$ip/verif/ti/iax_secondary_rtl_if.sv
