+incdir+$UVM_HOME/src
+incdir+$SAOLA_HOME/verilog
+incdir+$SAOLA_HOME/verilog_uvm
+incdir+$ip
+incdir+$ip/verif/tb/common/tbutils
+incdir+$ip/verif/tb/common/intdetector
+incdir+$ip/verif/tb/devtlb
+incdir+$ip/verif/tb/env
+incdir+$ip/verif/tb/env/common
+incdir+$ip/verif/tb/sequences
+incdir+$ip/verif/tb/env/sm
+incdir+$ip/verif/tb/env/ACLEnv
+incdir+$ip/verif/tb/common/mem_access
+incdir+$ip/verif/tb/common/mem_allocate
+incdir+$ip/verif/tb/env/sm/
+incdir+$ip/verif/tb/env/L3Env
+incdir+$ip/verif/tb/env/scoreboard
+incdir+$ip/verif/tb/env/ral/ral_envs

$ip/verif/tb/devtlb/devtlb_compmon.sv
$ip/verif/tb/devtlb/devtlb_sig_if.sv
$ip/verif/tb/devtlb/DevTlbScoreboardPkg.sv
$ip/verif/tb/common/saola_deprecated_api/dsa_saola_deprecated_api_pkg.sv
$ip/verif/tb/common/tbutils/TbUtilsPkg.sv
$ip/verif/tb/common/intdetector/BaseInterruptPkg.sv
$ip/verif/tb/common/intdetector/IOSFInterruptPkg.sv
$ip/verif/tb/common/intdetector/IOSFSvcInterruptPkg.sv
$ip/verif/tb/common/intdetector/IOSFPvcInterruptPkg.sv
$ip/verif/tb/env/DsaConfigPkg.sv
$ip/verif/tb/common/mem_access/MemAccessPkg.sv
$ip/verif/tb/common/mem_access/IosfMemAccessPkg.sv
$ip/verif/tb/common/mem_access/SlaMemAccessPkg.sv
$ip/verif/tb/common/mem_allocate/mem_alloc_pkg.sv
$ip/verif/tb/env/ACLEnv/DsaACLEnvPkg.sv
$ip/verif/tb/env/L3Env/DsaKernelPkg.sv
$ip/verif/tb/env/DsaEnvPkg.sv
