+define+VSIM
+define+INCLUDE_GCR
+define+SIMULATION
+define+OVM
+define+MROOT_SPACE_SIGNAL_NAME=mrs
+define+IOSFTRKCHK_NO_DEPENDENCIES
+define+TYPE1_ENABLE
+define+SPS_TR_RECORD_NEXT
+define+DISABLE_COMPMON
+define+NO_IP_SYN
+define+OVM_COMPILE
+define+ENABLE_NONUPF_ACK
+define+PSF20_TB_POK_EN
+define+INSTANTIATE_HIERDUMP
+define+DIS_BRIDGE_WB_COV
+define+FABRIC_MONITOR_ENABLE
+define+FPGA
+define+define
+define+FPGA_VERIF
+define+SLA_RAL_DATA_WIDTH=64
+define+SLA_RAL_ADDR_WIDTH=64
+define+PCIE_GOLDCREST
+define+UHFI_GMT_TOP
+define+PCIE_REFCLK_100
+define+UHFI_INDIRECT
+define+UMR_SIM
+define+UHFI_GLUE_DIFF_CLK
+define+UHFI_TB_TOP=uhfi_ref_design_tb
+define+UHFI_TI_TOP=uhfi_ref_design_tb.i_uhfi_ti
+define+UHFI_RTL_TOP=uhfi_ref_design_tb.i_uhfi_ref_top.uhfi
+define+FPGA_IP_TOP=uhfi_ref_design_tb.i_uhfi_ref_top.uhfi
+define+GTX_IP_AGT_TOP=uhfi_ref_design_tb.GTX_BRIDGE_ENABLE_GEN_BLK.gtx_ip_top_fabric
+define+SVA_OFF
+define+INTEL_SVA_OFF
+define+ASSERT_OFF
+define+INTEL_FPGA
+define+SYNTHESIS
+define+NO_FSDB_DUMP_MODULE
+define+VISA_OFF
+define+FPGA_MODE
+define+UHFI_REF_TB_PRESENT
+define+DSA_ENABLED_FPGA_MODEL
+define+IAX_ENABLED_FPGA_MODEL
+define+SPARK_VCS
+incdir+/p/com/eda/intel/saola/v20140417/verilog
+incdir+$OVM_HOME/src
+incdir+$OVM_HOME/src/macros
+incdir+$ip/subip/sip/UHFI_v4.13.0/verif/tb/include
+incdir+$ip/subip/sip/UHFI_v4.13.0/source/rtl/include
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/verif/gtx_ip/tb
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/common
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/fpga_gtx_bridge/rtl/desc2iosf_bridge
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/ttif_port
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/agent_port
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/err_handler
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/fabric_decode
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/fabric_port
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/fth
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/fth/time_stamp
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/arbiter
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/port_grp
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/port_arb
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/psf_config
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/psf_top
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/pwr_manage
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/rf_wrapper
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/psf_picr25_r1p0_v0_fpga/rtl/shadow_regs
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/fpga_gtx_bridge/rtl/gt/sb2fifo/sbendpoint/common/
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/fpga_gtx_bridge/rtl/gt/sb2fifo/sbendpoint/common/macros/
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/fpga_gtx_bridge/rtl/gt/sb2fifo/sbendpoint
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/source/fpga_gtx_bridge/rtl/gtx_ip
