+define+EMULATION_V8
+define+MEM_CTECH
+define+UHFI_TB_TOP=uhfi_ref_design_tb  
+define+UHFI_RTL_TOP=uhfi_ref_design_tb.i_uhfi_ref_top.uhfi  
#+define+CPM_TOP=haps_wrapper.i_cpm_top.cpm_2p0
+define+EMU_CPM_DID=4944
+define+CPM_NOFLOPDELAY
+define+INTEL_SVA_OFF
+define+SVA_OFF
+define+OVL_SYNTHESIS_OFF
+define+INTEL_EMULATION
+define+EMULATION
+define+CPM_ASIC_MEMS
+define+INTC_MEM_COV_OFF
+define+NOFLOPDELAY
+define+VISA_OFF
+define+XILINX=1
+define+VCS_SIM
+define+VCSSIM
+define+INTC_ADD_VSS
+define+VMOD_OVL_DISABLE
+define+EMULATION_NP8
+define+NO_PWR_PINS_disable
+define+SPARK_VCS
+incdir+$ip/subip/sip/hqm_rtl_lib/subIP/sip/AW/src/rtl
+incdir+$ip/subip/sip/hqm_rtl_lib/subip/vip/designware
+incdir+$ip/subip/sip/hqm_rtl_lib/src/rtl/system
+incdir+$ip/subip/sip/hqm_rtl_lib/src/codegen/hqm_sip/nebulon/nebulon.hqm_msix_mem_nebulon_lib/nebulon/output/sverilog
+incdir+$ip/subip/sip/hqm_rtl_lib/src/codegen/hqm_sip/nebulon/nebulon.hqm_system_csr_nebulon_lib/nebulon/output/sverilog
+incdir+$ip/subip/sip/hqm_rtl_lib/src/codegen/hqm_sip/nebulon/nebulon.hqm_sif_csr_nebulon_lib/nebulon/output/sverilog
#+incdir+/nfs/pdx/disks/epv.emu.6/gowtham1/dmr/rtls.prototyping.vep.cpm-2p0c-fpga-env/results/rtl/
#+incdir+/nfs/pdx/disks/epv.emu.6/gowtham1/dmr/rtls.prototyping.vep.cpm-2p0c-fpga-env/src/rtlchanges_includes

