+define+VSIM
+define+XILINX
+define+SIMULATION
+define+OVM
+define+MROOT_SPACE_SIGNAL_NAME=mrs
+define+IOSFTRKCHK_NO_DEPENDENCIES
+define+TYPE1_ENABLE
+define+SPS_TR_RECORD_NEXT
+define+DISABLE_COMPMON
+define+NO_IP_SYN
+define+OVM_COMPILE
+define+ENABLE_NONUPF_ACK
+define+PSF20_TB_POK_EN
+define+INSTANTIATE_HIERDUMP
+define+DIS_BRIDGE_WB_COV
+define+FABRIC_MONITOR_ENABLE
+define+FPGA
+define+define
+define+FPGA_VERIF
+define+SLA_RAL_DATA_WIDTH=64
+define+SLA_RAL_ADDR_WIDTH=64
+define+PCIE_GOLDCREST
+define+UHFI_GMT_TOP
+define+PCIE_REFCLK_100
+define+UHFI_INDIRECT
+define+UMR_SIM
+define+UHFI_GLUE_DIFF_CLK
+define+UHFI_TB_TOP=uhfi_ref_design_tb
+define+UHFI_TI_TOP=uhfi_ref_design_tb.i_uhfi_ti
+define+UHFI_RTL_TOP=uhfi_ref_design_tb.i_uhfi_ref_top.uhfi
+define+FPGA_IP_TOP=uhfi_ref_design_tb.i_uhfi_ref_top.uhfi
+define+GTX_IP_AGT_TOP=uhfi_ref_design_tb.GTX_BRIDGE_ENABLE_GEN_BLK.gtx_ip_top_fabric
+define+SVA_OFF
+define+INTEL_SVA_OFF
+define+ASSERT_OFF
+define+INTEL_FPGA
+define+SYNTHESIS
+define+NO_FSDB_DUMP_MODULE
+define+VISA_OFF
+define+FPGA_MODE
+define+UHFI_REF_TB_PRESENT
+define+DSA_ENABLED_FPGA_MODEL
+define+IAX_ENABLED_FPGA_MODEL
+define+SPARK_VCS
+incdir+/p/com/eda/intel/saola/v20140417/verilog
+incdir+$OVM_HOME/src
+incdir+$OVM_HOME/src/macros
+incdir+$ip/subip/sip/UHFI_v4.13.0/verif/tb/include
+incdir+$ip/subip/sip/UHFI_v4.13.0/source/rtl/include
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/fpga_gtx_bridge/verif/gtx_ip/tb
+incdir+$ip/subip/sip/UHFI_v4.13.0/source/rtl
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/vc/ccu_vc/source/rtl
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/LB2SB/source/rtl
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/pcie_ctrl/source/rtl
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/LB2SB/source/rtl/fip_sb/common
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/LB2SB/source/verif/ise/14.4/XilinxCoreLib
+incdir+$ip/subip/sip/UHFI_v4.13.0/subIP/pcie_ctrl/source/verif/ise/14.4/XilinxCoreLib
