#!/bin/csh

/bin/rm -rf DVEfiles
/bin/rm -rf NTI_trk.out
/bin/rm -rf csrc
/bin/rm -rf inter.vpd
/bin/rm -rf ral_monitor_reg_trk.out
/bin/rm -rf simv
/bin/rm -rf simv.daidir
/bin/rm -rf simv.vdb
/bin/rm -rf ucli.key
/bin/rm -rf vc_hdrs.h
/bin/rm -rf .restartSimSession.tcl
/bin/rm -rf .synopsys_dve_rebuild.tcl

setenv OVM_HOME /p/com/eda/ovm/ovm/2.1.1_2
tsetup vcsmx J-2014.12-SP3-B-1
tsetup ace 2.01.30
setenv LM_LICENSE_FILE 26586@anls1312.an.intel.com:26586@scylic13.sc.intel.com:26586@fmylic36a.fm.intel.com:26586@fmylic36c.fm.intel.com:26586@plxs0412.pdx.intel.com:26586@hdylic09.hd.intel.com:26586@ilic2004.iil.intel.com:26586@pgllic11.png.intel.com

echo "Specify the test case as second arugment $1"

# Specify the directory where the JTAG BFM from IRR is located.
setenv JTAG_BFM_VER /nfs/iind/disks/mg_disk1653/sudheer/repo/ip-jtag-bfm

# Set location of Converged TAP BFM.
setenv CONVERGED_TAP_BFM $JTAG_BFM_VER/verif/tb/Converged_JtagBfm

# Specify +define+DFX_TAP_PRE_AUTOMATION if using non-generated original style TAP class names.
$VCS_HOME/bin/vcs \
  -R -sverilog +v2k -debug_all -lca -notice -l log\
  -timescale=1ns/1ps \
  +OVM_TESTNAME=$1 \
  -f $JTAG_BFM_VER/scripts/filelist.f \
  #+define+SVA_OFF \
  +incdir+$JTAG_BFM_VER/subIP/ip-tap-network/verif/tb/ \
  +incdir+$JTAG_BFM_VER/subIP/ip-tap-network/verif/tests/ \
  +incdir+$JTAG_BFM_VER/subIP/ip-tap-network/verif/tb/include \
  +incdir+$JTAG_BFM_VER/subIP/ip-tap-network/verif/tb/include/configs \
  +incdir+$JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/include \
  +incdir+$JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/include/assertions \
  +incdir+$JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/common \
  +incdir+$JTAG_BFM_VER/subIP/ip-tap-network/source/rtl/include \
  +incdir+$JTAG_BFM_VER/subIP/ip-tap-network/source/rtl/include/assertions \
  +incdir+$JTAG_BFM_VER/subIP/ip-stap/source/rtl/include \
  +incdir+$JTAG_BFM_VER/subIP/ip-stap/source/rtl/include/assertions \
  +incdir+$JTAG_BFM_VER/subIP/ip-stap/source/rtl/common \
  +incdir+$ACE_HOME/lib/Verilog \
  $JTAG_BFM_VER/subIP/ip-tap-network/verif/tb/tapnw_pin_if.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/verif/tb/TapPkg.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/verif/tb/TapTestIsland.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/verif/tb/TapTop.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/verif/tests/TapNWTest.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/verif/tb/mtap_tapnw_taps.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/cltapc.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_fsm.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_irreg.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_irdecoder.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_drreg.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_tdomux.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_data_reg.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_remote_data_reg.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_decoder.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_tapnw.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_bscan.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_glue.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_wtapnw.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_visa.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_visa_reg.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/mtap/mtap_dfxsecure.sv \
  $JTAG_BFM_VER/subIP/ip-master-tap/source/rtl/ctech_lib/sipcltapc_map.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/source/rtl/tapnw/tapnw.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/source/rtl/tapnw/tapnw_mtcp.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/source/rtl/tapnw/tapnw_mtdp.sv \
  $JTAG_BFM_VER/subIP/ip-tap-network/source/rtl/ctech_lib/siptapnw_map.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_fsm.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_irreg.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_irdecoder.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_drreg.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_tdomux.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_data_reg.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_remote_data_reg.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_decoder.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_tapnw.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_bscan.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_glue.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_wtapnw.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_visa.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_visa_reg.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/stap/stap_dfxsecure.sv \
  $JTAG_BFM_VER/subIP/ip-stap/source/rtl/ctech_lib/sipstap_map.sv
