$ip/ph4/hw_mon/track/iosf_p_common_pkg.sv
$ip/ph4/hw_mon/track/iosf_p_hw_monitor.sv
$ip/ph4/compmon/lib/iosf_prim_comp_pkg.sv
$ip/ph4/compmon/primary/iosf_prim_ifc_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_request_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_completion_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_signal_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_tdecode_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_tclass_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_transaction_compliance.sv
$ip/ph4/compmon/ism/iosf_prim_fabric_ism_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_req_grnt_flow_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_request_credit_compliance.sv
$ip/ph4/compmon/primary/iosf_prim_transaction_credit_compliance.sv
$ip/ph4/compmon/ism/iosf_prim_agent_ism_compliance.sv
$ip/ph4/compmon/ism/iosf_prim_clock_gating_compliance.sv
$ip/ph4/compmon/lib/iosf_prim_lib_fifo.sv
$ip/ph4/compmon/lib/iosf_prim_lib_fifo_count.sv
$ip/ph4/compmon/lib/iosf_prim_lib_cam.sv
$ip/ph4/svlib/SvUtilsPkg.sv
$ip/ph4/tracker/iosf_trkchk_wrapper_pkg.sv
$ip/ph4/IosfPkg.sv
$ip/ph4/source/iosf_primary_intf.sv
$ip/ph4/intf/pipeline_reg.sv
$ip/ph4/source/iosf_primary_ti.sv
$ip/ph4/nti/iosf_nti_intf.sv
$ip/ph4/nti/iosf_nti_ti.sv
$ip/ph4/stf/iosf_stf_intf.sv
$ip/ph4/stf/iosf_stf_ti.sv
+incdir+$ip/ph4/
+incdir+$OVM_HOME/src
+incdir+${SAOLA_HOME}/verilog
+incdir+${UVM_HOME}/src
+incdir+${XVM_HOME}/src
+incdir+${XVM_HOME}/src/macros
+incdir+$ip/ph4/source
+incdir+$ip/ph4/compmon/primary
+incdir+$ip/ph4/compmon/lib
+incdir+$ip/ph4/compmon/ism

+incdir+$ip/ph4/hw_mon/track
+incdir+$ip/ph4/svlib
+incdir+$ip/ph4/source
+incdir+$ip/ph4/common
+incdir+$ip/ph4/agent
+incdir+$ip/ph4/fabric
+incdir+$ip/ph4/monitor
+incdir+$ip/ph4/cover
+incdir+$ip/ph4/quickcov
+incdir+$ip/ph4/intf
+incdir+$ip/ph4/nti
+incdir+$ip/ph4/stf
+incdir+$ip/ph4/seq_old
+incdir+$ip/ph4/tracker
+incdir+$ip/ph4/compmon/lib
#Phase 3 compatibility
+incdir+$ip/ph4/ph3_compat
