
+incdir+$ip/src/rtl/params
+incdir+$ip/src/rtl/devtlb

$ip/src/rtl/devtlb/devtlb.sv
#/p/hdk/cad/stdcells/g1m/21ww03.5_p1276d31_g1m_h.3.p2/v/bn/g1m_bn.v

#-f $ip/filelists/ctech.f
$ctech_path/ctech_lib_clk_divider2.sv
$ctech_path/ctech_lib_and.sv
$ctech_path/ctech_lib_buf.sv
$ctech_path/ctech_lib_clk_and.sv
$ctech_path/ctech_lib_clk_and_en.sv
$ctech_path/ctech_lib_clk_buf.sv
$ctech_path/ctech_lib_clk_divider2_rstb.sv
$ctech_path/ctech_lib_clk_ffb.sv
$ctech_path/ctech_lib_clk_ffb_rstb.sv
$ctech_path/ctech_lib_clk_gate_and.sv
$ctech_path/ctech_lib_clk_gate_or.sv
$ctech_path/ctech_lib_clk_gate_te.sv
$ctech_path/ctech_lib_clk_gate_te_rstb.sv
$ctech_path/ctech_lib_clk_inv.sv
$ctech_path/ctech_lib_clk_mux_2to1.sv
$ctech_path/ctech_lib_clk_nand.sv
$ctech_path/ctech_lib_clk_nand_en.sv
$ctech_path/ctech_lib_clk_nor.sv
$ctech_path/ctech_lib_clk_nor_en.sv
$ctech_path/ctech_lib_clk_or.sv
$ctech_path/ctech_lib_clk_or_en.sv
$ctech_path/ctech_lib_doublesync.sv
$ctech_path/ctech_lib_doublesync_rst.sv
$ctech_path/ctech_lib_doublesync_rstb.sv
$ctech_path/ctech_lib_doublesync_set.sv
$ctech_path/ctech_lib_doublesync_setb.sv
$ctech_path/ctech_lib_inv.sv
$ctech_path/ctech_lib_latch.sv
$ctech_path/ctech_lib_latch_p.sv
$ctech_path/ctech_lib_msff_async_rstb.sv
$ctech_path/ctech_lib_msff_async_setb.sv
$ctech_path/ctech_lib_mux_2to1.sv
$ctech_path/ctech_lib_nand.sv
$ctech_path/ctech_lib_nor.sv
$ctech_path/ctech_lib_or.sv
$ctech_path/ctech_lib_triplesync.sv
$ctech_path/ctech_lib_triplesync_rst.sv
$ctech_path/ctech_lib_triplesync_rstb.sv
$ctech_path/ctech_lib_triplesync_set.sv
$ctech_path/ctech_lib_triplesync_setb.sv
$ctech_path/ctech_lib_xor.sv
