$ip/verif/lib/CCU_OOB/ccu_ob_pkg.sv
$ip/verif/lib/CCU_OOB/ccu_ob_intf.sv
$ip/verif/lib/CCU_OOB/ccu_ob_ti.sv
$ip/verif/lib/CCU_CRG/ccu_crg_pkg.sv
$ip/verif/lib/CCU_CRG/ccu_crg_intf.sv
$ip/verif/lib/CCU_CRG/ccu_crg_no_param_intf.sv
$ip/verif/lib/CCU_CRG/ccu_crg_ti.sv
$ip/verif/ccu-vc/ccu_intf.sv
$ip/verif/ccu-vc/ccu_np_intf.sv
$ip/verif/ccu-vc/ccu_vc_ti.sv
$ip/verif/ccu-vc/ccu_vc_pkg.sv
+incdir+$OVM_HOME/src
+incdir+$UVM_HOME/src
+incdir+$XVM_HOME/src
+incdir+$SAOLA_HOME/verilog
+incdir+$ip/source
+incdir+$ip/verif/ccu-vc
+incdir+$ip/verif/lib/CCU_OOB
+incdir+$ip/verif/lib
+incdir+$ip/verif/lib/CCU_CRG
