INSTANCE: hqm_core_tb_top.u_hqm_core.par_hqm_list_sel_pipe.i_hqm_list_sel_pipe.i_hqm_list_sel_pipe_core.i_hqm_lsp_atm_pipe
Toggle tcnt [31:0] "logic tcnt[31:0]"
Toggle fcnt [31:0] "logic fcnt[31:0]"
Toggle block_sch2rdy  "logic block_sch2rdy"
Toggle p0_ll_data_f.hqm_core_flags.ignore_cq_depth  "logic p0_ll_data_f.hqm_core_flags.ignore_cq_depth"
Toggle p0_ll_data_f.hqm_core_flags.reserved  "logic p0_ll_data_f.hqm_core_flags.reserved"
Toggle p0_ll_data_f.hqm_core_flags.write_status [0:0] "logic p0_ll_data_f.hqm_core_flags.write_status[1:0]"
Toggle p0_ll_data_f.hqm_core_flags.cq_occ  "logic p0_ll_data_f.hqm_core_flags.cq_occ"
Toggle p0_ll_data_f.hqm_core_flags.error  "logic p0_ll_data_f.hqm_core_flags.error"
Toggle p0_ll_data_f.error  "logic p0_ll_data_f.error"
Toggle p0_ll_data_f.sch_hp_parity [3:0] "logic p0_ll_data_f.sch_hp_parity[3:0]"
Toggle p0_ll_data_f.rdy_tp_parity [3:0] "logic p0_ll_data_f.rdy_tp_parity[3:0]"
Toggle p0_ll_data_f.rdy_hp_parity [3:0] "logic p0_ll_data_f.rdy_hp_parity[3:0]"
Toggle p0_ll_data_f.fid_sync  "logic p0_ll_data_f.fid_sync"
Toggle p0_ll_data_f.fid [11:11] "logic p0_ll_data_f.fid[11:0]"
Toggle p0_ll_data_f.sch_tp [11:10] "logic p0_ll_data_f.sch_tp[47:0]"
Toggle p0_ll_data_f.sch_tp [23:22] "logic p0_ll_data_f.sch_tp[47:0]"
Toggle p0_ll_data_f.sch_tp [35:34] "logic p0_ll_data_f.sch_tp[47:0]"
Toggle p0_ll_data_f.sch_tp [47:46] "logic p0_ll_data_f.sch_tp[47:0]"
Toggle p0_ll_data_f.sch_hp [47:0] "logic p0_ll_data_f.sch_hp[47:0]"
Toggle p0_ll_data_f.rdy_tp [47:0] "logic p0_ll_data_f.rdy_tp[47:0]"
Toggle p0_ll_data_f.rdy_hp [47:0] "logic p0_ll_data_f.rdy_hp[47:0]"
Toggle p0_ll_data_f.rdy_bin [1:0] "logic p0_ll_data_f.rdy_bin[1:0]"
Toggle p0_ll_data_nxt.hqm_core_flags.ignore_cq_depth  "logic p0_ll_data_nxt.hqm_core_flags.ignore_cq_depth"
Toggle p0_ll_data_nxt.hqm_core_flags.reserved  "logic p0_ll_data_nxt.hqm_core_flags.reserved"
Toggle p0_ll_data_nxt.hqm_core_flags.write_status [0:0] "logic p0_ll_data_nxt.hqm_core_flags.write_status[1:0]"
Toggle p0_ll_data_nxt.hqm_core_flags.cq_occ  "logic p0_ll_data_nxt.hqm_core_flags.cq_occ"
Toggle p0_ll_data_nxt.hqm_core_flags.error  "logic p0_ll_data_nxt.hqm_core_flags.error"
Toggle p0_ll_data_nxt.error  "logic p0_ll_data_nxt.error"
Toggle p0_ll_data_nxt.sch_hp_parity [3:0] "logic p0_ll_data_nxt.sch_hp_parity[3:0]"
Toggle p0_ll_data_nxt.rdy_tp_parity [3:0] "logic p0_ll_data_nxt.rdy_tp_parity[3:0]"
Toggle p0_ll_data_nxt.rdy_hp_parity [3:0] "logic p0_ll_data_nxt.rdy_hp_parity[3:0]"
Toggle p0_ll_data_nxt.fid_sync  "logic p0_ll_data_nxt.fid_sync"
Toggle p0_ll_data_nxt.fid [11:11] "logic p0_ll_data_nxt.fid[11:0]"
Toggle p0_ll_data_nxt.sch_tp [11:10] "logic p0_ll_data_nxt.sch_tp[47:0]"
Toggle p0_ll_data_nxt.sch_tp [23:22] "logic p0_ll_data_nxt.sch_tp[47:0]"
Toggle p0_ll_data_nxt.sch_tp [35:34] "logic p0_ll_data_nxt.sch_tp[47:0]"
Toggle p0_ll_data_nxt.sch_tp [47:46] "logic p0_ll_data_nxt.sch_tp[47:0]"
Toggle p0_ll_data_nxt.sch_hp [47:0] "logic p0_ll_data_nxt.sch_hp[47:0]"
Toggle p0_ll_data_nxt.rdy_tp [47:0] "logic p0_ll_data_nxt.rdy_tp[47:0]"
Toggle p0_ll_data_nxt.rdy_hp [47:0] "logic p0_ll_data_nxt.rdy_hp[47:0]"
Toggle p0_ll_data_nxt.rdy_bin [1:0] "logic p0_ll_data_nxt.rdy_bin[1:0]"
Toggle p1_ll_data_f.hqm_core_flags.ignore_cq_depth  "logic p1_ll_data_f.hqm_core_flags.ignore_cq_depth"
Toggle p1_ll_data_f.hqm_core_flags.reserved  "logic p1_ll_data_f.hqm_core_flags.reserved"
Toggle p1_ll_data_f.hqm_core_flags.write_status [0:0] "logic p1_ll_data_f.hqm_core_flags.write_status[1:0]"
Toggle p1_ll_data_f.hqm_core_flags.cq_occ  "logic p1_ll_data_f.hqm_core_flags.cq_occ"
Toggle p1_ll_data_f.hqm_core_flags.error  "logic p1_ll_data_f.hqm_core_flags.error"
Toggle p1_ll_data_f.error  "logic p1_ll_data_f.error"
Toggle p1_ll_data_f.sch_hp_parity [3:0] "logic p1_ll_data_f.sch_hp_parity[3:0]"
Toggle p1_ll_data_f.rdy_tp_parity [3:0] "logic p1_ll_data_f.rdy_tp_parity[3:0]"
Toggle p1_ll_data_f.rdy_hp_parity [3:0] "logic p1_ll_data_f.rdy_hp_parity[3:0]"
Toggle p1_ll_data_f.fid_sync  "logic p1_ll_data_f.fid_sync"
Toggle p1_ll_data_f.fid [11:11] "logic p1_ll_data_f.fid[11:0]"
Toggle p1_ll_data_f.sch_tp [11:11] "logic p1_ll_data_f.sch_tp[47:0]"
Toggle p1_ll_data_f.sch_tp [23:22] "logic p1_ll_data_f.sch_tp[47:0]"
Toggle p1_ll_data_f.sch_tp [35:34] "logic p1_ll_data_f.sch_tp[47:0]"
Toggle p1_ll_data_f.sch_tp [47:46] "logic p1_ll_data_f.sch_tp[47:0]"
Toggle p1_ll_data_f.sch_hp [47:0] "logic p1_ll_data_f.sch_hp[47:0]"
Toggle p1_ll_data_f.rdy_tp [47:0] "logic p1_ll_data_f.rdy_tp[47:0]"
Toggle p1_ll_data_f.rdy_hp [47:0] "logic p1_ll_data_f.rdy_hp[47:0]"
Toggle p1_ll_data_f.rdy_bin [1:0] "logic p1_ll_data_f.rdy_bin[1:0]"
Toggle p1_ll_data_nxt.hqm_core_flags.ignore_cq_depth  "logic p1_ll_data_nxt.hqm_core_flags.ignore_cq_depth"
Toggle p1_ll_data_nxt.hqm_core_flags.reserved  "logic p1_ll_data_nxt.hqm_core_flags.reserved"
Toggle p1_ll_data_nxt.hqm_core_flags.write_status [0:0] "logic p1_ll_data_nxt.hqm_core_flags.write_status[1:0]"
Toggle p1_ll_data_nxt.hqm_core_flags.cq_occ  "logic p1_ll_data_nxt.hqm_core_flags.cq_occ"
Toggle p1_ll_data_nxt.hqm_core_flags.error  "logic p1_ll_data_nxt.hqm_core_flags.error"
Toggle p1_ll_data_nxt.error  "logic p1_ll_data_nxt.error"
Toggle p1_ll_data_nxt.sch_hp_parity [3:0] "logic p1_ll_data_nxt.sch_hp_parity[3:0]"
Toggle p1_ll_data_nxt.rdy_tp_parity [3:0] "logic p1_ll_data_nxt.rdy_tp_parity[3:0]"
Toggle p1_ll_data_nxt.rdy_hp_parity [3:0] "logic p1_ll_data_nxt.rdy_hp_parity[3:0]"
Toggle p1_ll_data_nxt.fid_sync  "logic p1_ll_data_nxt.fid_sync"
Toggle p1_ll_data_nxt.fid [11:11] "logic p1_ll_data_nxt.fid[11:0]"
Toggle p1_ll_data_nxt.sch_tp [11:11] "logic p1_ll_data_nxt.sch_tp[47:0]"
Toggle p1_ll_data_nxt.sch_tp [23:22] "logic p1_ll_data_nxt.sch_tp[47:0]"
Toggle p1_ll_data_nxt.sch_tp [35:34] "logic p1_ll_data_nxt.sch_tp[47:0]"
Toggle p1_ll_data_nxt.sch_tp [47:46] "logic p1_ll_data_nxt.sch_tp[47:0]"
Toggle p1_ll_data_nxt.sch_hp [47:0] "logic p1_ll_data_nxt.sch_hp[47:0]"
Toggle p1_ll_data_nxt.rdy_tp [47:0] "logic p1_ll_data_nxt.rdy_tp[47:0]"
Toggle p1_ll_data_nxt.rdy_hp [47:0] "logic p1_ll_data_nxt.rdy_hp[47:0]"
Toggle p1_ll_data_nxt.rdy_bin [1:0] "logic p1_ll_data_nxt.rdy_bin[1:0]"
Toggle p2_ll_data_f.hqm_core_flags.ignore_cq_depth  "logic p2_ll_data_f.hqm_core_flags.ignore_cq_depth"
Toggle p2_ll_data_f.hqm_core_flags.reserved  "logic p2_ll_data_f.hqm_core_flags.reserved"
Toggle p2_ll_data_f.hqm_core_flags.write_status [0:0] "logic p2_ll_data_f.hqm_core_flags.write_status[1:0]"
Toggle p2_ll_data_f.hqm_core_flags.cq_occ  "logic p2_ll_data_f.hqm_core_flags.cq_occ"
Toggle p2_ll_data_f.hqm_core_flags.error  "logic p2_ll_data_f.hqm_core_flags.error"
Toggle p2_ll_data_f.error  "logic p2_ll_data_f.error"
Toggle p2_ll_data_f.sch_hp_parity [3:0] "logic p2_ll_data_f.sch_hp_parity[3:0]"
Toggle p2_ll_data_f.rdy_tp_parity [3:0] "logic p2_ll_data_f.rdy_tp_parity[3:0]"
Toggle p2_ll_data_f.rdy_hp_parity [3:0] "logic p2_ll_data_f.rdy_hp_parity[3:0]"
Toggle p2_ll_data_f.fid_sync  "logic p2_ll_data_f.fid_sync"
Toggle p2_ll_data_f.fid [11:11] "logic p2_ll_data_f.fid[11:0]"
Toggle p2_ll_data_f.sch_tp [11:11] "logic p2_ll_data_f.sch_tp[47:0]"
Toggle p2_ll_data_f.sch_tp [23:22] "logic p2_ll_data_f.sch_tp[47:0]"
Toggle p2_ll_data_f.sch_tp [35:34] "logic p2_ll_data_f.sch_tp[47:0]"
Toggle p2_ll_data_f.sch_tp [47:46] "logic p2_ll_data_f.sch_tp[47:0]"
Toggle p2_ll_data_f.sch_hp [47:0] "logic p2_ll_data_f.sch_hp[47:0]"
Toggle p2_ll_data_f.rdy_tp [47:0] "logic p2_ll_data_f.rdy_tp[47:0]"
Toggle p2_ll_data_f.rdy_hp [47:0] "logic p2_ll_data_f.rdy_hp[47:0]"
Toggle p2_ll_data_f.rdy_bin [1:0] "logic p2_ll_data_f.rdy_bin[1:0]"
Toggle p2_ll_data_nxt.hqm_core_flags.ignore_cq_depth  "logic p2_ll_data_nxt.hqm_core_flags.ignore_cq_depth"
Toggle p2_ll_data_nxt.hqm_core_flags.reserved  "logic p2_ll_data_nxt.hqm_core_flags.reserved"
Toggle p2_ll_data_nxt.hqm_core_flags.write_status [0:0] "logic p2_ll_data_nxt.hqm_core_flags.write_status[1:0]"
Toggle p2_ll_data_nxt.hqm_core_flags.cq_occ  "logic p2_ll_data_nxt.hqm_core_flags.cq_occ"
Toggle p2_ll_data_nxt.hqm_core_flags.error  "logic p2_ll_data_nxt.hqm_core_flags.error"
Toggle p2_ll_data_nxt.error  "logic p2_ll_data_nxt.error"
Toggle p2_ll_data_nxt.sch_hp_parity [3:0] "logic p2_ll_data_nxt.sch_hp_parity[3:0]"
Toggle p2_ll_data_nxt.rdy_tp_parity [3:0] "logic p2_ll_data_nxt.rdy_tp_parity[3:0]"
Toggle p2_ll_data_nxt.rdy_hp_parity [3:0] "logic p2_ll_data_nxt.rdy_hp_parity[3:0]"
Toggle p2_ll_data_nxt.fid_sync  "logic p2_ll_data_nxt.fid_sync"
Toggle p2_ll_data_nxt.fid [11:11] "logic p2_ll_data_nxt.fid[11:0]"
Toggle p2_ll_data_nxt.sch_tp [11:11] "logic p2_ll_data_nxt.sch_tp[47:0]"
Toggle p2_ll_data_nxt.sch_tp [23:22] "logic p2_ll_data_nxt.sch_tp[47:0]"
Toggle p2_ll_data_nxt.sch_tp [35:34] "logic p2_ll_data_nxt.sch_tp[47:0]"
Toggle p2_ll_data_nxt.sch_tp [47:46] "logic p2_ll_data_nxt.sch_tp[47:0]"
Toggle p2_ll_data_nxt.sch_hp [47:0] "logic p2_ll_data_nxt.sch_hp[47:0]"
Toggle p2_ll_data_nxt.rdy_tp [47:0] "logic p2_ll_data_nxt.rdy_tp[47:0]"
Toggle p2_ll_data_nxt.rdy_hp [47:0] "logic p2_ll_data_nxt.rdy_hp[47:0]"
Toggle p2_ll_data_nxt.rdy_bin [1:0] "logic p2_ll_data_nxt.rdy_bin[1:0]"
Toggle p3_ll_data_f.hqm_core_flags.ignore_cq_depth  "logic p3_ll_data_f.hqm_core_flags.ignore_cq_depth"
Toggle p3_ll_data_f.hqm_core_flags.reserved  "logic p3_ll_data_f.hqm_core_flags.reserved"
Toggle p3_ll_data_f.hqm_core_flags.write_status [0:0] "logic p3_ll_data_f.hqm_core_flags.write_status[1:0]"
Toggle p3_ll_data_f.hqm_core_flags.cq_occ  "logic p3_ll_data_f.hqm_core_flags.cq_occ"
Toggle p3_ll_data_f.hqm_core_flags.error  "logic p3_ll_data_f.hqm_core_flags.error"
Toggle p3_ll_data_f.error  "logic p3_ll_data_f.error"
Toggle p3_ll_data_f.fid_sync  "logic p3_ll_data_f.fid_sync"
Toggle p3_ll_data_f.fid [11:11] "logic p3_ll_data_f.fid[11:0]"
Toggle p3_ll_data_f.sch_tp [11:11] "logic p3_ll_data_f.sch_tp[47:0]"
Toggle p3_ll_data_f.sch_tp [23:22] "logic p3_ll_data_f.sch_tp[47:0]"
Toggle p3_ll_data_f.sch_tp [35:34] "logic p3_ll_data_f.sch_tp[47:0]"
Toggle p3_ll_data_f.sch_tp [47:46] "logic p3_ll_data_f.sch_tp[47:0]"
Toggle p3_ll_data_f.sch_hp [11:11] "logic p3_ll_data_f.sch_hp[47:0]"
Toggle p3_ll_data_f.sch_hp [23:22] "logic p3_ll_data_f.sch_hp[47:0]"
Toggle p3_ll_data_f.sch_hp [35:34] "logic p3_ll_data_f.sch_hp[47:0]"
Toggle p3_ll_data_f.sch_hp [47:46] "logic p3_ll_data_f.sch_hp[47:0]"
Toggle p3_ll_data_f.rdy_tp [11:11] "logic p3_ll_data_f.rdy_tp[47:0]"
Toggle p3_ll_data_f.rdy_tp [23:22] "logic p3_ll_data_f.rdy_tp[47:0]"
Toggle p3_ll_data_f.rdy_tp [35:34] "logic p3_ll_data_f.rdy_tp[47:0]"
Toggle p3_ll_data_f.rdy_tp [47:46] "logic p3_ll_data_f.rdy_tp[47:0]"
Toggle p3_ll_data_f.rdy_hp [11:11] "logic p3_ll_data_f.rdy_hp[47:0]"
Toggle p3_ll_data_f.rdy_hp [23:22] "logic p3_ll_data_f.rdy_hp[47:0]"
Toggle p3_ll_data_f.rdy_hp [35:34] "logic p3_ll_data_f.rdy_hp[47:0]"
Toggle p3_ll_data_f.rdy_hp [47:46] "logic p3_ll_data_f.rdy_hp[47:0]"
Toggle p3_ll_data_f.rdy_bin [1:0] "logic p3_ll_data_f.rdy_bin[1:0]"
Toggle p3_ll_data_nxt.hqm_core_flags.ignore_cq_depth  "logic p3_ll_data_nxt.hqm_core_flags.ignore_cq_depth"
Toggle p3_ll_data_nxt.hqm_core_flags.reserved  "logic p3_ll_data_nxt.hqm_core_flags.reserved"
Toggle p3_ll_data_nxt.hqm_core_flags.write_status [0:0] "logic p3_ll_data_nxt.hqm_core_flags.write_status[1:0]"
Toggle p3_ll_data_nxt.hqm_core_flags.cq_occ  "logic p3_ll_data_nxt.hqm_core_flags.cq_occ"
Toggle p3_ll_data_nxt.hqm_core_flags.error  "logic p3_ll_data_nxt.hqm_core_flags.error"
Toggle p3_ll_data_nxt.error  "logic p3_ll_data_nxt.error"
Toggle p3_ll_data_nxt.fid_sync  "logic p3_ll_data_nxt.fid_sync"
Toggle p3_ll_data_nxt.fid [11:11] "logic p3_ll_data_nxt.fid[11:0]"
Toggle p3_ll_data_nxt.sch_tp [11:11] "logic p3_ll_data_nxt.sch_tp[47:0]"
Toggle p3_ll_data_nxt.sch_tp [23:22] "logic p3_ll_data_nxt.sch_tp[47:0]"
Toggle p3_ll_data_nxt.sch_tp [35:34] "logic p3_ll_data_nxt.sch_tp[47:0]"
Toggle p3_ll_data_nxt.sch_tp [47:46] "logic p3_ll_data_nxt.sch_tp[47:0]"
Toggle p3_ll_data_nxt.sch_hp [11:11] "logic p3_ll_data_nxt.sch_hp[47:0]"
Toggle p3_ll_data_nxt.sch_hp [23:22] "logic p3_ll_data_nxt.sch_hp[47:0]"
Toggle p3_ll_data_nxt.sch_hp [35:34] "logic p3_ll_data_nxt.sch_hp[47:0]"
Toggle p3_ll_data_nxt.sch_hp [47:46] "logic p3_ll_data_nxt.sch_hp[47:0]"
Toggle p3_ll_data_nxt.rdy_tp [11:11] "logic p3_ll_data_nxt.rdy_tp[47:0]"
Toggle p3_ll_data_nxt.rdy_tp [23:22] "logic p3_ll_data_nxt.rdy_tp[47:0]"
Toggle p3_ll_data_nxt.rdy_tp [35:34] "logic p3_ll_data_nxt.rdy_tp[47:0]"
Toggle p3_ll_data_nxt.rdy_tp [47:46] "logic p3_ll_data_nxt.rdy_tp[47:0]"
Toggle p3_ll_data_nxt.rdy_hp [11:11] "logic p3_ll_data_nxt.rdy_hp[47:0]"
Toggle p3_ll_data_nxt.rdy_hp [23:22] "logic p3_ll_data_nxt.rdy_hp[47:0]"
Toggle p3_ll_data_nxt.rdy_hp [35:34] "logic p3_ll_data_nxt.rdy_hp[47:0]"
Toggle p3_ll_data_nxt.rdy_hp [47:46] "logic p3_ll_data_nxt.rdy_hp[47:0]"
Toggle p3_ll_data_nxt.rdy_bin [1:0] "logic p3_ll_data_nxt.rdy_bin[1:0]"
Toggle p4_ll_data_f.hqm_core_flags.ignore_cq_depth  "logic p4_ll_data_f.hqm_core_flags.ignore_cq_depth"
Toggle p4_ll_data_f.hqm_core_flags.reserved  "logic p4_ll_data_f.hqm_core_flags.reserved"
Toggle p4_ll_data_f.hqm_core_flags.write_status [0:0] "logic p4_ll_data_f.hqm_core_flags.write_status[1:0]"
Toggle p4_ll_data_f.hqm_core_flags.cq_occ  "logic p4_ll_data_f.hqm_core_flags.cq_occ"
Toggle p4_ll_data_f.hqm_core_flags.error  "logic p4_ll_data_f.hqm_core_flags.error"
Toggle p4_ll_data_f.error  "logic p4_ll_data_f.error"
Toggle p4_ll_data_f.fid_sync  "logic p4_ll_data_f.fid_sync"
Toggle p4_ll_data_f.fid [11:11] "logic p4_ll_data_f.fid[11:0]"
Toggle p4_ll_data_f.sch_tp [11:11] "logic p4_ll_data_f.sch_tp[47:0]"
Toggle p4_ll_data_f.sch_tp [23:22] "logic p4_ll_data_f.sch_tp[47:0]"
Toggle p4_ll_data_f.sch_tp [35:34] "logic p4_ll_data_f.sch_tp[47:0]"
Toggle p4_ll_data_f.sch_tp [47:46] "logic p4_ll_data_f.sch_tp[47:0]"
Toggle p4_ll_data_f.sch_hp [11:11] "logic p4_ll_data_f.sch_hp[47:0]"
Toggle p4_ll_data_f.sch_hp [23:22] "logic p4_ll_data_f.sch_hp[47:0]"
Toggle p4_ll_data_f.sch_hp [35:34] "logic p4_ll_data_f.sch_hp[47:0]"
Toggle p4_ll_data_f.sch_hp [47:46] "logic p4_ll_data_f.sch_hp[47:0]"
Toggle p4_ll_data_f.rdy_tp [11:11] "logic p4_ll_data_f.rdy_tp[47:0]"
Toggle p4_ll_data_f.rdy_tp [23:22] "logic p4_ll_data_f.rdy_tp[47:0]"
Toggle p4_ll_data_f.rdy_tp [35:34] "logic p4_ll_data_f.rdy_tp[47:0]"
Toggle p4_ll_data_f.rdy_tp [47:46] "logic p4_ll_data_f.rdy_tp[47:0]"
Toggle p4_ll_data_f.rdy_hp [11:11] "logic p4_ll_data_f.rdy_hp[47:0]"
Toggle p4_ll_data_f.rdy_hp [23:22] "logic p4_ll_data_f.rdy_hp[47:0]"
Toggle p4_ll_data_f.rdy_hp [35:34] "logic p4_ll_data_f.rdy_hp[47:0]"
Toggle p4_ll_data_f.rdy_hp [47:46] "logic p4_ll_data_f.rdy_hp[47:0]"
Toggle p4_ll_data_f.rdy_bin [1:0] "logic p4_ll_data_f.rdy_bin[1:0]"
Toggle p4_ll_data_nxt.hqm_core_flags.ignore_cq_depth  "logic p4_ll_data_nxt.hqm_core_flags.ignore_cq_depth"
Toggle p4_ll_data_nxt.hqm_core_flags.reserved  "logic p4_ll_data_nxt.hqm_core_flags.reserved"
Toggle p4_ll_data_nxt.hqm_core_flags.write_status [0:0] "logic p4_ll_data_nxt.hqm_core_flags.write_status[1:0]"
Toggle p4_ll_data_nxt.hqm_core_flags.cq_occ  "logic p4_ll_data_nxt.hqm_core_flags.cq_occ"
Toggle p4_ll_data_nxt.hqm_core_flags.error  "logic p4_ll_data_nxt.hqm_core_flags.error"
Toggle p4_ll_data_nxt.error  "logic p4_ll_data_nxt.error"
Toggle p4_ll_data_nxt.fid_sync  "logic p4_ll_data_nxt.fid_sync"
Toggle p4_ll_data_nxt.fid [11:11] "logic p4_ll_data_nxt.fid[11:0]"
Toggle p4_ll_data_nxt.sch_tp [11:11] "logic p4_ll_data_nxt.sch_tp[47:0]"
Toggle p4_ll_data_nxt.sch_tp [23:22] "logic p4_ll_data_nxt.sch_tp[47:0]"
Toggle p4_ll_data_nxt.sch_tp [35:34] "logic p4_ll_data_nxt.sch_tp[47:0]"
Toggle p4_ll_data_nxt.sch_tp [47:46] "logic p4_ll_data_nxt.sch_tp[47:0]"
Toggle p4_ll_data_nxt.sch_hp [11:11] "logic p4_ll_data_nxt.sch_hp[47:0]"
Toggle p4_ll_data_nxt.sch_hp [23:22] "logic p4_ll_data_nxt.sch_hp[47:0]"
Toggle p4_ll_data_nxt.sch_hp [35:34] "logic p4_ll_data_nxt.sch_hp[47:0]"
Toggle p4_ll_data_nxt.sch_hp [47:46] "logic p4_ll_data_nxt.sch_hp[47:0]"
Toggle p4_ll_data_nxt.rdy_tp [11:11] "logic p4_ll_data_nxt.rdy_tp[47:0]"
Toggle p4_ll_data_nxt.rdy_tp [23:22] "logic p4_ll_data_nxt.rdy_tp[47:0]"
Toggle p4_ll_data_nxt.rdy_tp [35:34] "logic p4_ll_data_nxt.rdy_tp[47:0]"
Toggle p4_ll_data_nxt.rdy_tp [47:46] "logic p4_ll_data_nxt.rdy_tp[47:0]"
Toggle p4_ll_data_nxt.rdy_hp [11:11] "logic p4_ll_data_nxt.rdy_hp[47:0]"
Toggle p4_ll_data_nxt.rdy_hp [23:22] "logic p4_ll_data_nxt.rdy_hp[47:0]"
Toggle p4_ll_data_nxt.rdy_hp [35:34] "logic p4_ll_data_nxt.rdy_hp[47:0]"
Toggle p4_ll_data_nxt.rdy_hp [47:46] "logic p4_ll_data_nxt.rdy_hp[47:0]"
Toggle p4_ll_data_nxt.rdy_bin [1:0] "logic p4_ll_data_nxt.rdy_bin[1:0]"
Toggle p5_ll_data_f.hqm_core_flags.ignore_cq_depth  "logic p5_ll_data_f.hqm_core_flags.ignore_cq_depth"
Toggle p5_ll_data_f.hqm_core_flags.reserved  "logic p5_ll_data_f.hqm_core_flags.reserved"
Toggle p5_ll_data_f.hqm_core_flags.write_status [0:0] "logic p5_ll_data_f.hqm_core_flags.write_status[1:0]"
Toggle p5_ll_data_f.hqm_core_flags.cq_occ  "logic p5_ll_data_f.hqm_core_flags.cq_occ"
Toggle p5_ll_data_f.hqm_core_flags.error  "logic p5_ll_data_f.hqm_core_flags.error"
Toggle p5_ll_data_f.error  "logic p5_ll_data_f.error"
Toggle p5_ll_data_f.fid_sync  "logic p5_ll_data_f.fid_sync"
Toggle p5_ll_data_f.fid [11:11] "logic p5_ll_data_f.fid[11:0]"
Toggle p5_ll_data_f.sch_tp [11:11] "logic p5_ll_data_f.sch_tp[47:0]"
Toggle p5_ll_data_f.sch_tp [23:22] "logic p5_ll_data_f.sch_tp[47:0]"
Toggle p5_ll_data_f.sch_tp [35:34] "logic p5_ll_data_f.sch_tp[47:0]"
Toggle p5_ll_data_f.sch_tp [47:46] "logic p5_ll_data_f.sch_tp[47:0]"
Toggle p5_ll_data_f.sch_hp [11:11] "logic p5_ll_data_f.sch_hp[47:0]"
Toggle p5_ll_data_f.sch_hp [23:22] "logic p5_ll_data_f.sch_hp[47:0]"
Toggle p5_ll_data_f.sch_hp [35:34] "logic p5_ll_data_f.sch_hp[47:0]"
Toggle p5_ll_data_f.sch_hp [47:46] "logic p5_ll_data_f.sch_hp[47:0]"
Toggle p5_ll_data_f.rdy_tp [11:11] "logic p5_ll_data_f.rdy_tp[47:0]"
Toggle p5_ll_data_f.rdy_tp [23:22] "logic p5_ll_data_f.rdy_tp[47:0]"
Toggle p5_ll_data_f.rdy_tp [35:34] "logic p5_ll_data_f.rdy_tp[47:0]"
Toggle p5_ll_data_f.rdy_tp [47:46] "logic p5_ll_data_f.rdy_tp[47:0]"
Toggle p5_ll_data_f.rdy_hp [11:11] "logic p5_ll_data_f.rdy_hp[47:0]"
Toggle p5_ll_data_f.rdy_hp [23:22] "logic p5_ll_data_f.rdy_hp[47:0]"
Toggle p5_ll_data_f.rdy_hp [35:34] "logic p5_ll_data_f.rdy_hp[47:0]"
Toggle p5_ll_data_f.rdy_hp [47:46] "logic p5_ll_data_f.rdy_hp[47:0]"
Toggle p5_ll_data_f.rdy_bin [1:0] "logic p5_ll_data_f.rdy_bin[1:0]"
Toggle p5_ll_data_nxt.hqm_core_flags.ignore_cq_depth  "logic p5_ll_data_nxt.hqm_core_flags.ignore_cq_depth"
Toggle p5_ll_data_nxt.hqm_core_flags.reserved  "logic p5_ll_data_nxt.hqm_core_flags.reserved"
Toggle p5_ll_data_nxt.hqm_core_flags.write_status [0:0] "logic p5_ll_data_nxt.hqm_core_flags.write_status[1:0]"
Toggle p5_ll_data_nxt.hqm_core_flags.cq_occ  "logic p5_ll_data_nxt.hqm_core_flags.cq_occ"
Toggle p5_ll_data_nxt.hqm_core_flags.error  "logic p5_ll_data_nxt.hqm_core_flags.error"
Toggle p5_ll_data_nxt.error  "logic p5_ll_data_nxt.error"
Toggle p5_ll_data_nxt.fid_sync  "logic p5_ll_data_nxt.fid_sync"
Toggle p5_ll_data_nxt.fid [11:11] "logic p5_ll_data_nxt.fid[11:0]"
Toggle p5_ll_data_nxt.sch_tp [11:11] "logic p5_ll_data_nxt.sch_tp[47:0]"
Toggle p5_ll_data_nxt.sch_tp [23:22] "logic p5_ll_data_nxt.sch_tp[47:0]"
Toggle p5_ll_data_nxt.sch_tp [35:34] "logic p5_ll_data_nxt.sch_tp[47:0]"
Toggle p5_ll_data_nxt.sch_tp [47:46] "logic p5_ll_data_nxt.sch_tp[47:0]"
Toggle p5_ll_data_nxt.sch_hp [11:11] "logic p5_ll_data_nxt.sch_hp[47:0]"
Toggle p5_ll_data_nxt.sch_hp [23:22] "logic p5_ll_data_nxt.sch_hp[47:0]"
Toggle p5_ll_data_nxt.sch_hp [35:34] "logic p5_ll_data_nxt.sch_hp[47:0]"
Toggle p5_ll_data_nxt.sch_hp [47:46] "logic p5_ll_data_nxt.sch_hp[47:0]"
Toggle p5_ll_data_nxt.rdy_tp [11:11] "logic p5_ll_data_nxt.rdy_tp[47:0]"
Toggle p5_ll_data_nxt.rdy_tp [23:22] "logic p5_ll_data_nxt.rdy_tp[47:0]"
Toggle p5_ll_data_nxt.rdy_tp [35:34] "logic p5_ll_data_nxt.rdy_tp[47:0]"
Toggle p5_ll_data_nxt.rdy_tp [47:46] "logic p5_ll_data_nxt.rdy_tp[47:0]"
Toggle p5_ll_data_nxt.rdy_hp [11:11] "logic p5_ll_data_nxt.rdy_hp[47:0]"
Toggle p5_ll_data_nxt.rdy_hp [23:22] "logic p5_ll_data_nxt.rdy_hp[47:0]"
Toggle p5_ll_data_nxt.rdy_hp [35:34] "logic p5_ll_data_nxt.rdy_hp[47:0]"
Toggle p5_ll_data_nxt.rdy_hp [47:46] "logic p5_ll_data_nxt.rdy_hp[47:0]"
Toggle p5_ll_data_nxt.rdy_bin [1:0] "logic p5_ll_data_nxt.rdy_bin[1:0]"
Toggle p6_ll_data_f.hqm_core_flags.ignore_cq_depth  "logic p6_ll_data_f.hqm_core_flags.ignore_cq_depth"
Toggle p6_ll_data_f.hqm_core_flags.reserved  "logic p6_ll_data_f.hqm_core_flags.reserved"
Toggle p6_ll_data_f.hqm_core_flags.write_status [0:0] "logic p6_ll_data_f.hqm_core_flags.write_status[1:0]"
Toggle p6_ll_data_f.hqm_core_flags.cq_occ  "logic p6_ll_data_f.hqm_core_flags.cq_occ"
Toggle p6_ll_data_f.hqm_core_flags.error  "logic p6_ll_data_f.hqm_core_flags.error"
Toggle p6_ll_data_f.error  "logic p6_ll_data_f.error"
Toggle p6_ll_data_f.fid_sync  "logic p6_ll_data_f.fid_sync"
Toggle p6_ll_data_f.fid [11:11] "logic p6_ll_data_f.fid[11:0]"
Toggle p6_ll_data_f.sch_tp [11:11] "logic p6_ll_data_f.sch_tp[47:0]"
Toggle p6_ll_data_f.sch_tp [23:22] "logic p6_ll_data_f.sch_tp[47:0]"
Toggle p6_ll_data_f.sch_tp [35:34] "logic p6_ll_data_f.sch_tp[47:0]"
Toggle p6_ll_data_f.sch_tp [47:46] "logic p6_ll_data_f.sch_tp[47:0]"
Toggle p6_ll_data_f.sch_hp [11:11] "logic p6_ll_data_f.sch_hp[47:0]"
Toggle p6_ll_data_f.sch_hp [23:22] "logic p6_ll_data_f.sch_hp[47:0]"
Toggle p6_ll_data_f.sch_hp [35:34] "logic p6_ll_data_f.sch_hp[47:0]"
Toggle p6_ll_data_f.sch_hp [47:46] "logic p6_ll_data_f.sch_hp[47:0]"
Toggle p6_ll_data_f.rdy_tp [11:11] "logic p6_ll_data_f.rdy_tp[47:0]"
Toggle p6_ll_data_f.rdy_tp [23:22] "logic p6_ll_data_f.rdy_tp[47:0]"
Toggle p6_ll_data_f.rdy_tp [35:34] "logic p6_ll_data_f.rdy_tp[47:0]"
Toggle p6_ll_data_f.rdy_tp [47:46] "logic p6_ll_data_f.rdy_tp[47:0]"
Toggle p6_ll_data_f.rdy_hp [11:11] "logic p6_ll_data_f.rdy_hp[47:0]"
Toggle p6_ll_data_f.rdy_hp [23:22] "logic p6_ll_data_f.rdy_hp[47:0]"
Toggle p6_ll_data_f.rdy_hp [35:34] "logic p6_ll_data_f.rdy_hp[47:0]"
Toggle p6_ll_data_f.rdy_hp [47:46] "logic p6_ll_data_f.rdy_hp[47:0]"
Toggle p6_ll_data_nxt.hqm_core_flags.ignore_cq_depth  "logic p6_ll_data_nxt.hqm_core_flags.ignore_cq_depth"
Toggle p6_ll_data_nxt.hqm_core_flags.reserved  "logic p6_ll_data_nxt.hqm_core_flags.reserved"
Toggle p6_ll_data_nxt.hqm_core_flags.write_status [0:0] "logic p6_ll_data_nxt.hqm_core_flags.write_status[1:0]"
Toggle p6_ll_data_nxt.hqm_core_flags.cq_occ  "logic p6_ll_data_nxt.hqm_core_flags.cq_occ"
Toggle p6_ll_data_nxt.hqm_core_flags.error  "logic p6_ll_data_nxt.hqm_core_flags.error"
Toggle p6_ll_data_nxt.error  "logic p6_ll_data_nxt.error"
Toggle p6_ll_data_nxt.fid_sync  "logic p6_ll_data_nxt.fid_sync"
Toggle p6_ll_data_nxt.fid [11:11] "logic p6_ll_data_nxt.fid[11:0]"
Toggle p6_ll_data_nxt.sch_tp [11:11] "logic p6_ll_data_nxt.sch_tp[47:0]"
Toggle p6_ll_data_nxt.sch_tp [23:22] "logic p6_ll_data_nxt.sch_tp[47:0]"
Toggle p6_ll_data_nxt.sch_tp [35:34] "logic p6_ll_data_nxt.sch_tp[47:0]"
Toggle p6_ll_data_nxt.sch_tp [47:46] "logic p6_ll_data_nxt.sch_tp[47:0]"
Toggle p6_ll_data_nxt.sch_hp [11:11] "logic p6_ll_data_nxt.sch_hp[47:0]"
Toggle p6_ll_data_nxt.sch_hp [23:22] "logic p6_ll_data_nxt.sch_hp[47:0]"
Toggle p6_ll_data_nxt.sch_hp [35:34] "logic p6_ll_data_nxt.sch_hp[47:0]"
Toggle p6_ll_data_nxt.sch_hp [47:46] "logic p6_ll_data_nxt.sch_hp[47:0]"
Toggle p6_ll_data_nxt.rdy_tp [11:11] "logic p6_ll_data_nxt.rdy_tp[47:0]"
Toggle p6_ll_data_nxt.rdy_tp [23:22] "logic p6_ll_data_nxt.rdy_tp[47:0]"
Toggle p6_ll_data_nxt.rdy_tp [35:34] "logic p6_ll_data_nxt.rdy_tp[47:0]"
Toggle p6_ll_data_nxt.rdy_tp [47:46] "logic p6_ll_data_nxt.rdy_tp[47:0]"
Toggle p6_ll_data_nxt.rdy_hp [11:11] "logic p6_ll_data_nxt.rdy_hp[47:0]"
Toggle p6_ll_data_nxt.rdy_hp [23:22] "logic p6_ll_data_nxt.rdy_hp[47:0]"
Toggle p6_ll_data_nxt.rdy_hp [35:34] "logic p6_ll_data_nxt.rdy_hp[47:0]"
Toggle p6_ll_data_nxt.rdy_hp [47:46] "logic p6_ll_data_nxt.rdy_hp[47:0]"


Toggle cfg_bcast_reg_pnc.cfg_vf_reset_cmd [2:0] "logic cfg_bcast_reg_pnc.cfg_vf_reset_cmd[2:0]"
Toggle cfg_bcast_reg_pnc.cfg_vf_reset_type [2:2] "logic cfg_bcast_reg_pnc.cfg_vf_reset_type[3:0]"
Toggle cfg_bcast_reg_pnc.cfg_vf_reset_type [3:3] "logic cfg_bcast_reg_pnc.cfg_vf_reset_type[3:0]"
Toggle cfg_bcast_reg_pnc.cfg_vf_reset_id [23:6] "logic cfg_bcast_reg_pnc.cfg_vf_reset_id[23:0]"
Toggle cfg_bcast_reg_pnc.cfg_timout_threshold [18:0] "logic cfg_bcast_reg_pnc.cfg_timout_threshold[19:0]"
Toggle cfg_bcast_reg_pnc.cfg_timout_threshold [19:19] "logic cfg_bcast_reg_pnc.cfg_timout_threshold[19:0]"
Toggle cfg_bcast_reg_pnc.rsvd_2 [10:0] "logic cfg_bcast_reg_pnc.rsvd_2[10:0]"
Toggle cfg_bcast_reg_pnc.cfg_timout_enable  "logic cfg_bcast_reg_pnc.cfg_timout_enable"
Toggle cfg_bcast_reg_pnc.rsvd_1 [55:0] "logic cfg_bcast_reg_pnc.rsvd_1[55:0]"
Toggle cfg_bcast_reg_pnc.version [2:0] "logic cfg_bcast_reg_pnc.version[7:0]"
Toggle cfg_bcast_reg_pnc.version [3:3] "logic cfg_bcast_reg_pnc.version[7:0]"
Toggle cfg_bcast_reg_pnc.version [4:4] "logic cfg_bcast_reg_pnc.version[7:0]"
Toggle cfg_bcast_reg_pnc.version [7:5] "logic cfg_bcast_reg_pnc.version[7:0]"

Toggle smon_v [15:0] "logic smon_v[15:0]"
Toggle smon_v_f [15:0] "logic smon_v_f[15:0]"
Toggle smon_comp [511:0] "logic smon_comp[511:0]"
Toggle smon_comp_f [511:0] "logic smon_comp_f[511:0]"
Toggle smon_val [511:0] "logic smon_val[511:0]"
Toggle smon_val_f [511:0] "logic smon_val_f[511:0]"
Toggle smon_interrupt_nc  "logic smon_interrupt_nc"
Toggle smon_enabled  "logic smon_enabled"

Toggle fifo_ap_aqed_error_of  "logic fifo_ap_aqed_error_of"
Toggle fifo_ap_aqed_error_uf  "logic fifo_ap_aqed_error_uf"
Toggle fifo_ap_aqed_push_data.spare  "logic fifo_ap_aqed_push_data.spare"
Toggle fifo_ap_aqed_push_data.hqm_core_flags.ignore_cq_depth  "logic fifo_ap_aqed_push_data.hqm_core_flags.ignore_cq_depth"
Toggle fifo_ap_aqed_push_data.hqm_core_flags.reserved  "logic fifo_ap_aqed_push_data.hqm_core_flags.reserved"
Toggle fifo_ap_aqed_push_data.hqm_core_flags.write_status [0:0] "logic fifo_ap_aqed_push_data.hqm_core_flags.write_status[1:0]"
Toggle fifo_ap_aqed_push_data.hqm_core_flags.cq_occ  "logic fifo_ap_aqed_push_data.hqm_core_flags.cq_occ"
Toggle fifo_ap_aqed_push_data.hqm_core_flags.error  "logic fifo_ap_aqed_push_data.hqm_core_flags.error"
Toggle fifo_ap_aqed_push_data.flid [11:11] "logic fifo_ap_aqed_push_data.flid[11:0]"
Toggle fifo_ap_aqed_push_data.cq [7:6] "logic fifo_ap_aqed_push_data.cq[7:0]"
Toggle fifo_ap_aqed_push_data.cmd [1:0] "logic fifo_ap_aqed_push_data.cmd[1:0]"
Toggle fifo_ap_aqed_pop_data.spare  "logic fifo_ap_aqed_pop_data.spare"
Toggle fifo_ap_aqed_pop_data.hqm_core_flags.ignore_cq_depth  "logic fifo_ap_aqed_pop_data.hqm_core_flags.ignore_cq_depth"
Toggle fifo_ap_aqed_pop_data.hqm_core_flags.reserved  "logic fifo_ap_aqed_pop_data.hqm_core_flags.reserved"
Toggle fifo_ap_aqed_pop_data.hqm_core_flags.write_status [1:0] "logic fifo_ap_aqed_pop_data.hqm_core_flags.write_status[1:0]"
Toggle fifo_ap_aqed_pop_data.hqm_core_flags.is_ldb  "logic fifo_ap_aqed_pop_data.hqm_core_flags.is_ldb"
Toggle fifo_ap_aqed_pop_data.hqm_core_flags.cq_occ  "logic fifo_ap_aqed_pop_data.hqm_core_flags.cq_occ"
Toggle fifo_ap_aqed_pop_data.hqm_core_flags.error  "logic fifo_ap_aqed_pop_data.hqm_core_flags.error"
Toggle fifo_ap_aqed_pop_data.hqm_core_flags.parity  "logic fifo_ap_aqed_pop_data.hqm_core_flags.parity"
Toggle fifo_ap_aqed_pop_data.flid [11:11] "logic fifo_ap_aqed_pop_data.flid[11:0]"
Toggle fifo_ap_aqed_pop_data.cq [7:6] "logic fifo_ap_aqed_pop_data.cq[7:0]"
Toggle fifo_ap_aqed_pop_data.cmd [1:0] "logic fifo_ap_aqed_pop_data.cmd[1:0]"
Toggle fifo_ap_aqed_full  "logic fifo_ap_aqed_full"
Toggle fifo_ap_aqed_afull  "logic fifo_ap_aqed_afull"
Toggle fifo_aqed_ap_enq_error_of  "logic fifo_aqed_ap_enq_error_of"
Toggle fifo_aqed_ap_enq_error_uf  "logic fifo_aqed_ap_enq_error_uf"
Toggle fifo_aqed_ap_enq_push_data.flid [11:11] "logic fifo_aqed_ap_enq_push_data.flid[11:0]"
Toggle fifo_aqed_ap_enq_pop_data.flid [11:11] "logic fifo_aqed_ap_enq_pop_data.flid[11:0]"
Toggle fifo_ap_lsp_enq_error_of  "logic fifo_ap_lsp_enq_error_of"
Toggle fifo_ap_lsp_enq_error_uf  "logic fifo_ap_lsp_enq_error_uf"
Toggle fifo_ap_lsp_enq_full  "logic fifo_ap_lsp_enq_full"
Toggle fifo_ap_lsp_enq_afull  "logic fifo_ap_lsp_enq_afull"

Toggle cfg_control0_f [31:0] "logic cfg_control0_f[31:0]"
Toggle cfg_control0_nxt [31:0] "logic cfg_control0_nxt[31:0]"
Toggle cfg_control1_f [31:0] "logic cfg_control1_f[31:0]"
Toggle cfg_control1_nxt [31:0] "logic cfg_control1_nxt[31:0]"
Toggle cfg_control2_f [31:0] "logic cfg_control2_f[31:0]"
Toggle cfg_control2_nxt [31:0] "logic cfg_control2_nxt[31:0]"
Toggle cfg_control3_f [31:0] "logic cfg_control3_f[31:0]"
Toggle cfg_control3_nxt [31:0] "logic cfg_control3_nxt[31:0]"
Toggle cfg_control4_f [31:0] "logic cfg_control4_f[31:0]"
Toggle cfg_control4_nxt [31:0] "logic cfg_control4_nxt[31:0]"
Toggle cfg_control5_f [31:0] "logic cfg_control5_f[31:0]"
Toggle cfg_control5_nxt [31:0] "logic cfg_control5_nxt[31:0]"
Toggle cfg_control6_f [31:0] "logic cfg_control6_f[31:0]"
Toggle cfg_control6_nxt [31:0] "logic cfg_control6_nxt[31:0]"
Toggle cfg_control7_f [31:0] "logic cfg_control7_f[31:0]"
Toggle cfg_control7_nxt [31:0] "logic cfg_control7_nxt[31:0]"
Toggle cfg_control8_f [31:0] "logic cfg_control8_f[31:0]"
Toggle cfg_control8_nxt [31:0] "logic cfg_control8_nxt[31:0]"
Toggle cfg_pipe_health_valid_00_f [31:16] "logic cfg_pipe_health_valid_00_f[31:0]"
Toggle cfg_pipe_health_valid_00_nxt [31:16] "logic cfg_pipe_health_valid_00_nxt[31:0]"
Toggle cfg_pipe_health_valid_01_f [31:0] "logic cfg_pipe_health_valid_01_f[31:0]"
Toggle cfg_pipe_health_valid_01_nxt [31:0] "logic cfg_pipe_health_valid_01_nxt[31:0]"
Toggle cfg_error_inj_f [31:0] "logic cfg_error_inj_f[31:0]"
Toggle cfg_error_inj_nxt [31:0] "logic cfg_error_inj_nxt[31:0]"

Toggle cfg_counter_enqueue_hcw_f [15:15] "logic cfg_counter_enqueue_hcw_f[31:0]"
Toggle cfg_counter_enqueue_hcw_f [31:16] "logic cfg_counter_enqueue_hcw_f[31:0]"
Toggle cfg_counter_enqueue_hcw_nxt [15:15] "logic cfg_counter_enqueue_hcw_nxt[31:0]"
Toggle cfg_counter_enqueue_hcw_nxt [31:16] "logic cfg_counter_enqueue_hcw_nxt[31:0]"
Toggle cfg_counter_dequeue_hcw_f [15:15] "logic cfg_counter_dequeue_hcw_f[31:0]"
Toggle cfg_counter_dequeue_hcw_f [31:16] "logic cfg_counter_dequeue_hcw_f[31:0]"
Toggle cfg_counter_dequeue_hcw_nxt [15:15] "logic cfg_counter_dequeue_hcw_nxt[31:0]"
Toggle cfg_counter_dequeue_hcw_nxt [31:16] "logic cfg_counter_dequeue_hcw_nxt[31:0]"
Toggle cfg_counter_completion_hcw_f [15:15] "logic cfg_counter_completion_hcw_f[31:0]"
Toggle cfg_counter_completion_hcw_f [31:16] "logic cfg_counter_completion_hcw_f[31:0]"
Toggle cfg_counter_completion_hcw_nxt [15:15] "logic cfg_counter_completion_hcw_nxt[31:0]"
Toggle cfg_counter_completion_hcw_nxt [31:16] "logic cfg_counter_completion_hcw_nxt[31:0]"

Toggle reset_pf_counter_0_nxt [12:12] "logic reset_pf_counter_0_nxt[15:0]"
Toggle reset_pf_counter_0_nxt [15:13] "logic reset_pf_counter_0_nxt[15:0]"
Toggle reset_pf_counter_0_f [12:12] "logic reset_pf_counter_0_f[15:0]"
Toggle reset_pf_counter_0_f [15:13] "logic reset_pf_counter_0_f[15:0]"
Toggle reset_pf_counter_1_nxt [12:12] "logic reset_pf_counter_1_nxt[15:0]"
Toggle reset_pf_counter_1_nxt [15:13] "logic reset_pf_counter_1_nxt[15:0]"
Toggle reset_pf_counter_1_f [12:12] "logic reset_pf_counter_1_f[15:0]"
Toggle reset_pf_counter_1_f [15:13] "logic reset_pf_counter_1_f[15:0]"
Toggle reset_active_0_nxt  "logic reset_active_0_nxt"
Toggle reset_active_1_nxt  "logic reset_active_1_nxt"

Toggle error_ap_lsp  "logic error_ap_lsp"
Toggle error_headroom [1:0] "logic error_headroom[1:0]"
Toggle error_vfreset_cfg  "logic error_vfreset_cfg"
Toggle error_nopri  "logic error_nopri"
Toggle error_enq_cnt_r_of_nnc  "logic error_enq_cnt_r_of_nnc"
Toggle error_enq_cnt_r_uf_nnc  "logic error_enq_cnt_r_uf_nnc"
Toggle error_enq_cnt_s_of_nnc  "logic error_enq_cnt_s_of_nnc"
Toggle error_enq_cnt_s_uf_nnc  "logic error_enq_cnt_s_uf_nnc"
Toggle error_rlst_cnt_of_nnc  "logic error_rlst_cnt_of_nnc"
Toggle error_rlst_cnt_uf_nnc  "logic error_rlst_cnt_uf_nnc"
Toggle error_sch_cnt_of_nnc  "logic error_sch_cnt_of_nnc"
Toggle error_sch_cnt_uf_nnc  "logic error_sch_cnt_uf_nnc"
Toggle error_slst_cnt_of_nnc [3:0] "logic error_slst_cnt_of_nnc[3:0]"
Toggle error_slst_cnt_uf_nnc [3:0] "logic error_slst_cnt_uf_nnc[3:0]"
Toggle report_error_enq_cnt_r_of  "logic report_error_enq_cnt_r_of"
Toggle report_error_enq_cnt_r_uf  "logic report_error_enq_cnt_r_uf"
Toggle report_error_enq_cnt_s_of  "logic report_error_enq_cnt_s_of"
Toggle report_error_enq_cnt_s_uf  "logic report_error_enq_cnt_s_uf"
Toggle report_error_rlst_cnt_of  "logic report_error_rlst_cnt_of"
Toggle report_error_rlst_cnt_uf  "logic report_error_rlst_cnt_uf"
Toggle report_error_sch_cnt_of  "logic report_error_sch_cnt_of"
Toggle report_error_sch_cnt_uf  "logic report_error_sch_cnt_uf"
Toggle report_error_slst_cnt_of [3:0] "logic report_error_slst_cnt_of[3:0]"
Toggle report_error_slst_cnt_uf [3:0] "logic report_error_slst_cnt_uf[3:0]"

Toggle rst_ring_n  "logic rst_ring_n"
Toggle rst_n  "logic rst_n"
Toggle rst_n_trigger0_f  "logic rst_n_trigger0_f"
Toggle rst_n_trigger0_nxt  "logic rst_n_trigger0_nxt"
Toggle rst_n_trigger1_f  "logic rst_n_trigger1_f"
Toggle rst_n_trigger1_nxt  "logic rst_n_trigger1_nxt"
Toggle rst_n_done0_f  "logic rst_n_done0_f"
Toggle rst_n_done0_nxt  "logic rst_n_done0_nxt"
Toggle rst_n_done1_f  "logic rst_n_done1_f"
Toggle rst_n_done1_nxt  "logic rst_n_done1_nxt"
Toggle rst_n_done2_f  "logic rst_n_done2_f"
Toggle rst_n_done2_nxt  "logic rst_n_done2_nxt"
Toggle rst_n_done3_0_f  "logic rst_n_done3_0_f"
Toggle rst_n_done3_0_nxt  "logic rst_n_done3_0_nxt"
Toggle rst_n_done3_1_f  "logic rst_n_done3_1_f"
Toggle rst_n_done3_1_nxt  "logic rst_n_done3_1_nxt"
Toggle rst_n_done_0  "logic rst_n_done_0"
Toggle rst_n_done_1  "logic rst_n_done_1"

