INSTANCE: hqm_core_tb_top.u_hqm_core.par_hqm_credit_hist_pipe.i_hqm_credit_hist_pipe.i_hqm_credit_hist_pipe_core
Toggle reset_ring_n  "logic reset_ring_n"
Toggle reset_unit_n  "logic reset_unit_n"
Toggle disable_smon  "logic disable_smon"
Toggle hqm_reset_active  "logic hqm_reset_active"
Toggle hqm_reset_done  "logic hqm_reset_done"
Toggle chp_reset_done  "logic chp_reset_done"
Toggle chp_cfg_req_up.addr.offset [15:14] "logic chp_cfg_req_up.addr.offset[15:0]"
Toggle chp_cfg_req_up.addr.target [7:7] "logic chp_cfg_req_up.addr.target[15:0]"
Toggle chp_cfg_req_up.addr.target [12:12] "logic chp_cfg_req_up.addr.target[15:0]"
Toggle chp_cfg_req_up.cfg_ignore_pipe_busy  "logic chp_cfg_req_up.cfg_ignore_pipe_busy"
Toggle chp_cfg_rsp_up_ack  "logic chp_cfg_rsp_up_ack"
Toggle chp_cfg_rsp_up.uid [3:0] "logic chp_cfg_rsp_up.uid[3:0]"
Toggle chp_cfg_rsp_up.rdata [31:0] "logic chp_cfg_rsp_up.rdata[31:0]"
Toggle chp_cfg_rsp_up.rdata_par  "logic chp_cfg_rsp_up.rdata_par"
Toggle chp_cfg_rsp_up.err_slv_par  "logic chp_cfg_rsp_up.err_slv_par"
Toggle chp_cfg_rsp_up.err  "logic chp_cfg_rsp_up.err"
Toggle chp_cfg_req_down.addr.offset [15:7] "logic chp_cfg_req_down.addr.offset[15:0]"
Toggle chp_cfg_req_down.addr.target [7:7] "logic chp_cfg_req_down.addr.target[15:0]"
Toggle chp_cfg_req_down.addr.target [12:12] "logic chp_cfg_req_down.addr.target[15:0]"
Toggle chp_cfg_req_down.cfg_ignore_pipe_busy  "logic chp_cfg_req_down.cfg_ignore_pipe_busy"
Toggle chp_cfg_rsp_down.uid [3:0] "logic chp_cfg_rsp_down.uid[3:0]"
Toggle chp_cfg_rsp_down.err_slv_par  "logic chp_cfg_rsp_down.err_slv_par"
Toggle chp_alarm_up_data.rid [7:3] "logic chp_alarm_up_data.rid[7:0]"
Toggle chp_alarm_up_data.rtype [1:0] "logic chp_alarm_up_data.rtype[1:0]"
Toggle chp_alarm_up_data.msix_map [2:0] "logic chp_alarm_up_data.msix_map[2:0]"
Toggle chp_alarm_up_data.cls [1:0] "logic chp_alarm_up_data.cls[1:0]"
Toggle chp_alarm_up_data.aid [5:0] "logic chp_alarm_up_data.aid[5:0]"
Toggle chp_alarm_up_data.unit [3:0] "logic chp_alarm_up_data.unit[3:0]"
Toggle chp_alarm_down_data.rid [6:6] "logic chp_alarm_down_data.rid[7:0]"
Toggle chp_alarm_down_data.rtype [1:0] "logic chp_alarm_down_data.rtype[1:0]"
Toggle chp_alarm_down_data.cls [1:0] "logic chp_alarm_down_data.cls[1:0]"
Toggle chp_alarm_down_data.aid [5:4] "logic chp_alarm_down_data.aid[5:0]"
Toggle chp_alarm_down_data.unit [0:0] "logic chp_alarm_down_data.unit[3:0]"
Toggle chp_alarm_down_data.unit [3:2] "logic chp_alarm_down_data.unit[3:0]"
Toggle hcw_enq_aw_req.user.pp [7:7] "logic hcw_enq_aw_req.user.pp[7:0]"
Toggle hcw_enq_aw_req.addr [11:0] "logic hcw_enq_aw_req.addr[11:0]"
Toggle hcw_enq_aw_req.id [5:4] "logic hcw_enq_aw_req.id[5:0]"
Toggle hcw_enq_w_req.user [5:0] "logic hcw_enq_w_req.user[5:0]"
Toggle hcw_enq_w_req.data.ptr [63:63] "logic hcw_enq_w_req.data.ptr[63:0]"
Toggle hcw_enq_w_req.id [5:0] "logic hcw_enq_w_req.id[5:0]"
Toggle hcw_enq_b_req.user [5:0] "logic hcw_enq_b_req.user[5:0]"
Toggle hcw_enq_b_req.resp [1:0] "logic hcw_enq_b_req.resp[1:0]"
Toggle hcw_enq_b_req.id [5:4] "logic hcw_enq_b_req.id[5:0]"
Toggle hcw_enq_b_req_ready  "logic hcw_enq_b_req_ready"
Toggle hcw_sched_aw_req.user.cq [7:7] "logic hcw_sched_aw_req.user.cq[7:0]"
Toggle hcw_sched_aw_req.user.addr [10:10] "logic hcw_sched_aw_req.user.addr[10:0]"
Toggle hcw_sched_aw_req.user.hqm_core_flags.ignore_cq_depth  "logic hcw_sched_aw_req.user.hqm_core_flags.ignore_cq_depth"
Toggle hcw_sched_aw_req.user.hqm_core_flags.reserved  "logic hcw_sched_aw_req.user.hqm_core_flags.reserved"
Toggle hcw_sched_aw_req.user.hqm_core_flags.write_status [1:1] "logic hcw_sched_aw_req.user.hqm_core_flags.write_status[1:0]"
Toggle hcw_sched_aw_req.user.hqm_core_flags.cq_occ  "logic hcw_sched_aw_req.user.hqm_core_flags.cq_occ"
Toggle hcw_sched_aw_req.addr [13:0] "logic hcw_sched_aw_req.addr[13:0]"
Toggle hcw_sched_aw_req.id [5:0] "logic hcw_sched_aw_req.id[5:0]"
Toggle hcw_sched_w_req.user [5:0] "logic hcw_sched_w_req.user[5:0]"
Toggle hcw_sched_w_req.data.msg_info.qid [7:7] "logic hcw_sched_w_req.data.msg_info.qid[7:0]"
Toggle hcw_sched_w_req.data.msg_info.msgtype [2:1] "logic hcw_sched_w_req.data.msg_info.msgtype[2:0]"
Toggle hcw_sched_w_req.data.pp [7:7] "logic hcw_sched_w_req.data.pp[7:0]"
Toggle hcw_sched_w_req.data.rsvd0 [1:0] "logic hcw_sched_w_req.data.rsvd0[1:0]"
Toggle hcw_sched_w_req.data.rsvd1 [2:0] "logic hcw_sched_w_req.data.rsvd1[2:0]"
Toggle hcw_sched_w_req.data.rsvd2  "logic hcw_sched_w_req.data.rsvd2"
Toggle hcw_sched_w_req.data.debug [3:0] "logic hcw_sched_w_req.data.debug[7:0]"
Toggle hcw_sched_w_req.data.qid_depth  "logic hcw_sched_w_req.data.qid_depth"
Toggle hcw_sched_w_req.data.hqmrsvd [1:0] "logic hcw_sched_w_req.data.hqmrsvd[1:0]"
Toggle hcw_sched_w_req.id [5:0] "logic hcw_sched_w_req.id[5:0]"
Toggle hcw_sched_w_req_ready  "logic hcw_sched_w_req_ready"
Toggle hcw_sched_b_req.resp [1:0] "logic hcw_sched_b_req.resp[1:0]"
Toggle hcw_sched_b_req.id [5:0] "logic hcw_sched_b_req.id[5:0]"
Toggle hcw_sched_b_req_ready  "logic hcw_sched_b_req_ready"
Toggle push_ptr_aw_req.user.pp [7:7] "logic push_ptr_aw_req.user.pp[7:0]"
Toggle push_ptr_aw_req.user.reserved [5:0] "logic push_ptr_aw_req.user.reserved[5:0]"
Toggle push_ptr_aw_req.len [7:0] "logic push_ptr_aw_req.len[7:0]"
Toggle push_ptr_w_req.data.ptr [31:15] "logic push_ptr_w_req.data.ptr[31:0]"
Toggle push_ptr_w_req.data.pad [95:0] "logic push_ptr_w_req.data.pad[95:0]"
Toggle push_ptr_w_req_ready  "logic push_ptr_w_req_ready"
Toggle interrupt_w_req.cq_occ_cq [6:6] "logic interrupt_w_req.cq_occ_cq[6:0]"
Toggle cwdi_interrupt_w_req.cq [6:2] "logic cwdi_interrupt_w_req.cq[6:0]"
Toggle chp_rop_hcw_data.cq_hcw.pp [7:7] "logic chp_rop_hcw_data.cq_hcw.pp[7:0]"
Toggle chp_rop_hcw_data.cq_hcw.error  "logic chp_rop_hcw_data.cq_hcw.error"
Toggle chp_rop_hcw_data.flid [14:14] "logic chp_rop_hcw_data.flid[14:0]"
Toggle chp_lsp_cmp_data.pp [7:6] "logic chp_lsp_cmp_data.pp[7:0]"
Toggle chp_lsp_token_data.cq [7:7] "logic chp_lsp_token_data.cq[7:0]"
Toggle qed_chp_sch_data.cq_hcw.ptr [29:29] "logic qed_chp_sch_data.cq_hcw.ptr[63:0]"
Toggle qed_chp_sch_data.cq_hcw.msg_info.qid [7:7] "logic qed_chp_sch_data.cq_hcw.msg_info.qid[7:0]"
Toggle qed_chp_sch_data.cq_hcw.msg_info.msgtype [2:1] "logic qed_chp_sch_data.cq_hcw.msg_info.msgtype[2:0]"
Toggle qed_chp_sch_data.cq_hcw.pp [7:7] "logic qed_chp_sch_data.cq_hcw.pp[7:0]"
Toggle qed_chp_sch_data.hqm_core_flags.reserved  "logic qed_chp_sch_data.hqm_core_flags.reserved"
Toggle qed_chp_sch_data.hqm_core_flags.cq_occ  "logic qed_chp_sch_data.hqm_core_flags.cq_occ"
Toggle qed_chp_sch_data.flid [14:14] "logic qed_chp_sch_data.flid[14:0]"
Toggle qed_chp_sch_data.cq [7:6] "logic qed_chp_sch_data.cq[7:0]"
Toggle dqed_chp_sch_data.cq_hcw.ptr [29:29] "logic dqed_chp_sch_data.cq_hcw.ptr[63:0]"
Toggle dqed_chp_sch_data.cq_hcw.msg_info.qid [7:7] "logic dqed_chp_sch_data.cq_hcw.msg_info.qid[7:0]"
Toggle dqed_chp_sch_data.cq_hcw.msg_info.qtype [1:0] "logic dqed_chp_sch_data.cq_hcw.msg_info.qtype[1:0]"
Toggle dqed_chp_sch_data.cq_hcw.msg_info.msgtype [2:0] "logic dqed_chp_sch_data.cq_hcw.msg_info.msgtype[2:0]"
Toggle dqed_chp_sch_data.cq_hcw.pp [7:7] "logic dqed_chp_sch_data.cq_hcw.pp[7:0]"
Toggle dqed_chp_sch_data.cq_hcw.user  "logic dqed_chp_sch_data.cq_hcw.user"
Toggle dqed_chp_sch_data.cq_hcw.fid_dir_info [9:7] "logic dqed_chp_sch_data.cq_hcw.fid_dir_info[15:0]"
Toggle dqed_chp_sch_data.cq_hcw.fid_dir_info [15:13] "logic dqed_chp_sch_data.cq_hcw.fid_dir_info[15:0]"
Toggle dqed_chp_sch_data.hqm_core_flags.reserved  "logic dqed_chp_sch_data.hqm_core_flags.reserved"
Toggle dqed_chp_sch_data.hqm_core_flags.is_ldb  "logic dqed_chp_sch_data.hqm_core_flags.is_ldb"
Toggle dqed_chp_sch_data.hqm_core_flags.cq_occ  "logic dqed_chp_sch_data.hqm_core_flags.cq_occ"
Toggle dqed_chp_sch_data.flid [14:12] "logic dqed_chp_sch_data.flid[14:0]"
Toggle dqed_chp_sch_data.cq [7:7] "logic dqed_chp_sch_data.cq[7:0]"
Toggle aqed_chp_sch_data.spare [2:0] "logic aqed_chp_sch_data.spare[2:0]"
Toggle aqed_chp_sch_data.cq_hcw.ptr [29:29] "logic aqed_chp_sch_data.cq_hcw.ptr[63:0]"
Toggle aqed_chp_sch_data.cq_hcw.msg_info.qid [7:7] "logic aqed_chp_sch_data.cq_hcw.msg_info.qid[7:0]"
Toggle aqed_chp_sch_data.cq_hcw.msg_info.qtype [1:0] "logic aqed_chp_sch_data.cq_hcw.msg_info.qtype[1:0]"
Toggle aqed_chp_sch_data.cq_hcw.msg_info.msgtype [2:0] "logic aqed_chp_sch_data.cq_hcw.msg_info.msgtype[2:0]"
Toggle aqed_chp_sch_data.cq_hcw.pp [7:7] "logic aqed_chp_sch_data.cq_hcw.pp[7:0]"
Toggle aqed_chp_sch_data.hqm_core_flags.reserved  "logic aqed_chp_sch_data.hqm_core_flags.reserved"
Toggle aqed_chp_sch_data.hqm_core_flags.cq_occ  "logic aqed_chp_sch_data.hqm_core_flags.cq_occ"
Toggle aqed_chp_sch_data.fid [11:11] "logic aqed_chp_sch_data.fid[11:0]"
Toggle aqed_chp_sch_data.cq [7:6] "logic aqed_chp_sch_data.cq[7:0]"
Toggle visa_str_chp_lsp_cmp_data  "logic visa_str_chp_lsp_cmp_data"
Toggle chp_LV_TM_rf  "logic chp_LV_TM_rf"
Toggle chp_LV_WRSTN_rf  "logic chp_LV_WRSTN_rf"
Toggle chp_LV_WRCK_rf  "logic chp_LV_WRCK_rf"
Toggle chp_LV_WSI_rf  "logic chp_LV_WSI_rf"
Toggle chp_LV_UpdateWR_rf  "logic chp_LV_UpdateWR_rf"
Toggle chp_LV_ShiftWR_rf  "logic chp_LV_ShiftWR_rf"
Toggle chp_LV_CaptureWR_rf  "logic chp_LV_CaptureWR_rf"
Toggle chp_LV_SelectWIR_rf  "logic chp_LV_SelectWIR_rf"
Toggle chp_LV_EnableWR_rf  "logic chp_LV_EnableWR_rf"
Toggle chp_LV_WSO_rf  "logic chp_LV_WSO_rf"
Toggle chp_LV_AuxEn_rf  "logic chp_LV_AuxEn_rf"
Toggle chp_LV_AuxOut_rf  "logic chp_LV_AuxOut_rf"
Toggle chp_LV_TM_sram  "logic chp_LV_TM_sram"
Toggle chp_LV_WRSTN_sram  "logic chp_LV_WRSTN_sram"
Toggle chp_LV_WRCK_sram  "logic chp_LV_WRCK_sram"
Toggle chp_LV_WSI_sram  "logic chp_LV_WSI_sram"
Toggle chp_LV_UpdateWR_sram  "logic chp_LV_UpdateWR_sram"
Toggle chp_LV_ShiftWR_sram  "logic chp_LV_ShiftWR_sram"
Toggle chp_LV_CaptureWR_sram  "logic chp_LV_CaptureWR_sram"
Toggle chp_LV_SelectWIR_sram  "logic chp_LV_SelectWIR_sram"
Toggle chp_LV_EnableWR_sram  "logic chp_LV_EnableWR_sram"
Toggle chp_LV_WSO_sram  "logic chp_LV_WSO_sram"
Toggle chp_LV_AuxEn_sram  "logic chp_LV_AuxEn_sram"
Toggle chp_LV_AuxOut_sram  "logic chp_LV_AuxOut_sram"
Toggle fary_ffuse_rf_trim [5:0] "logic fary_ffuse_rf_trim[5:0]"
Toggle fary_ffuse_ssa_trim [19:0] "logic fary_ffuse_ssa_trim[19:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr1_5 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr1_5[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en1_5  "logic repair_fuses_chp.ssa.qed_freelist.row_en1_5"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr0_5 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr0_5[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en0_5  "logic repair_fuses_chp.ssa.qed_freelist.row_en0_5"
Toggle repair_fuses_chp.ssa.qed_freelist.col_addr_5 [2:0] "logic repair_fuses_chp.ssa.qed_freelist.col_addr_5[2:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.col_en_5  "logic repair_fuses_chp.ssa.qed_freelist.col_en_5"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr1_4 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr1_4[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en1_4  "logic repair_fuses_chp.ssa.qed_freelist.row_en1_4"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr0_4 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr0_4[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en0_4  "logic repair_fuses_chp.ssa.qed_freelist.row_en0_4"
Toggle repair_fuses_chp.ssa.qed_freelist.col_addr_4 [2:0] "logic repair_fuses_chp.ssa.qed_freelist.col_addr_4[2:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.col_en_4  "logic repair_fuses_chp.ssa.qed_freelist.col_en_4"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr1_3 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr1_3[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en1_3  "logic repair_fuses_chp.ssa.qed_freelist.row_en1_3"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr0_3 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr0_3[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en0_3  "logic repair_fuses_chp.ssa.qed_freelist.row_en0_3"
Toggle repair_fuses_chp.ssa.qed_freelist.col_addr_3 [2:0] "logic repair_fuses_chp.ssa.qed_freelist.col_addr_3[2:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.col_en_3  "logic repair_fuses_chp.ssa.qed_freelist.col_en_3"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr1_2 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr1_2[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en1_2  "logic repair_fuses_chp.ssa.qed_freelist.row_en1_2"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr0_2 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr0_2[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en0_2  "logic repair_fuses_chp.ssa.qed_freelist.row_en0_2"
Toggle repair_fuses_chp.ssa.qed_freelist.col_addr_2 [2:0] "logic repair_fuses_chp.ssa.qed_freelist.col_addr_2[2:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.col_en_2  "logic repair_fuses_chp.ssa.qed_freelist.col_en_2"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr1_1 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr1_1[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en1_1  "logic repair_fuses_chp.ssa.qed_freelist.row_en1_1"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr0_1 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr0_1[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en0_1  "logic repair_fuses_chp.ssa.qed_freelist.row_en0_1"
Toggle repair_fuses_chp.ssa.qed_freelist.col_addr_1 [2:0] "logic repair_fuses_chp.ssa.qed_freelist.col_addr_1[2:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.col_en_1  "logic repair_fuses_chp.ssa.qed_freelist.col_en_1"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr1_0 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr1_0[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en1_0  "logic repair_fuses_chp.ssa.qed_freelist.row_en1_0"
Toggle repair_fuses_chp.ssa.qed_freelist.row_addr0_0 [8:0] "logic repair_fuses_chp.ssa.qed_freelist.row_addr0_0[8:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.row_en0_0  "logic repair_fuses_chp.ssa.qed_freelist.row_en0_0"
Toggle repair_fuses_chp.ssa.qed_freelist.col_addr_0 [2:0] "logic repair_fuses_chp.ssa.qed_freelist.col_addr_0[2:0]"
Toggle repair_fuses_chp.ssa.qed_freelist.col_en_0  "logic repair_fuses_chp.ssa.qed_freelist.col_en_0"
Toggle repair_fuses_chp.ssa.dqed_freelist.row_addr1_0 [8:0] "logic repair_fuses_chp.ssa.dqed_freelist.row_addr1_0[8:0]"
Toggle repair_fuses_chp.ssa.dqed_freelist.row_en1_0  "logic repair_fuses_chp.ssa.dqed_freelist.row_en1_0"
Toggle repair_fuses_chp.ssa.dqed_freelist.row_addr0_0 [8:0] "logic repair_fuses_chp.ssa.dqed_freelist.row_addr0_0[8:0]"
Toggle repair_fuses_chp.ssa.dqed_freelist.row_en0_0  "logic repair_fuses_chp.ssa.dqed_freelist.row_en0_0"
Toggle repair_fuses_chp.ssa.dqed_freelist.col_addr_0 [4:0] "logic repair_fuses_chp.ssa.dqed_freelist.col_addr_0[4:0]"
Toggle repair_fuses_chp.ssa.dqed_freelist.col_en_0  "logic repair_fuses_chp.ssa.dqed_freelist.col_en_0"
Toggle repair_fuses_chp.ssa.hist_list.row_addr1_2 [9:0] "logic repair_fuses_chp.ssa.hist_list.row_addr1_2[9:0]"
Toggle repair_fuses_chp.ssa.hist_list.row_en1_2  "logic repair_fuses_chp.ssa.hist_list.row_en1_2"
Toggle repair_fuses_chp.ssa.hist_list.row_addr0_2 [9:0] "logic repair_fuses_chp.ssa.hist_list.row_addr0_2[9:0]"
Toggle repair_fuses_chp.ssa.hist_list.row_en0_2  "logic repair_fuses_chp.ssa.hist_list.row_en0_2"
Toggle repair_fuses_chp.ssa.hist_list.col_addr_2 [4:0] "logic repair_fuses_chp.ssa.hist_list.col_addr_2[4:0]"
Toggle repair_fuses_chp.ssa.hist_list.col_en_2  "logic repair_fuses_chp.ssa.hist_list.col_en_2"
Toggle repair_fuses_chp.ssa.hist_list.row_addr1_1 [9:0] "logic repair_fuses_chp.ssa.hist_list.row_addr1_1[9:0]"
Toggle repair_fuses_chp.ssa.hist_list.row_en1_1  "logic repair_fuses_chp.ssa.hist_list.row_en1_1"
Toggle repair_fuses_chp.ssa.hist_list.row_addr0_1 [9:0] "logic repair_fuses_chp.ssa.hist_list.row_addr0_1[9:0]"
Toggle repair_fuses_chp.ssa.hist_list.row_en0_1  "logic repair_fuses_chp.ssa.hist_list.row_en0_1"
Toggle repair_fuses_chp.ssa.hist_list.col_addr_1 [4:0] "logic repair_fuses_chp.ssa.hist_list.col_addr_1[4:0]"
Toggle repair_fuses_chp.ssa.hist_list.col_en_1  "logic repair_fuses_chp.ssa.hist_list.col_en_1"
Toggle repair_fuses_chp.ssa.hist_list.row_addr1_0 [9:0] "logic repair_fuses_chp.ssa.hist_list.row_addr1_0[9:0]"
Toggle repair_fuses_chp.ssa.hist_list.row_en1_0  "logic repair_fuses_chp.ssa.hist_list.row_en1_0"
Toggle repair_fuses_chp.ssa.hist_list.row_addr0_0 [9:0] "logic repair_fuses_chp.ssa.hist_list.row_addr0_0[9:0]"
Toggle repair_fuses_chp.ssa.hist_list.row_en0_0  "logic repair_fuses_chp.ssa.hist_list.row_en0_0"
Toggle repair_fuses_chp.ssa.hist_list.col_addr_0 [4:0] "logic repair_fuses_chp.ssa.hist_list.col_addr_0[4:0]"
Toggle repair_fuses_chp.ssa.hist_list.col_en_0  "logic repair_fuses_chp.ssa.hist_list.col_en_0"
Toggle fdfx_lbist_test_mode  "logic fdfx_lbist_test_mode"
Toggle fdfx_sync_rst  "logic fdfx_sync_rst"
Toggle fscan_mode  "logic fscan_mode"
Toggle fscan_rstbypen  "logic fscan_rstbypen"
Toggle fscan_byprst_b  "logic fscan_byprst_b"
Toggle fscan_ram_wrdis_b  "logic fscan_ram_wrdis_b"
Toggle fscan_ram_rddis_b  "logic fscan_ram_rddis_b"
Toggle fscan_ram_odis_b  "logic fscan_ram_odis_b"
Toggle fscan_ram_awt_mode  "logic fscan_ram_awt_mode"
Toggle fscan_ram_awt_ren  "logic fscan_ram_awt_ren"
Toggle fscan_ram_awt_wen  "logic fscan_ram_awt_wen"
Toggle fscan_ram_bypsel  "logic fscan_ram_bypsel"
Toggle fscan_ram_init_val  "logic fscan_ram_init_val"
Toggle fscan_ram_init_en  "logic fscan_ram_init_en"
Toggle fsta_dfxact_afd  "logic fsta_dfxact_afd"
Toggle fsta_afd_en  "logic fsta_afd_en"
Toggle aary_mbist_diag_done [1:0] "logic aary_mbist_diag_done[1:0]"
