INSTANCE: hqm_core_tb_top.u_hqm_core.par_hqm_dir_pipe.i_hqm_dir_pipe.i_hqm_dir_pipe_core
Toggle disable_smon  "logic disable_smon"
Toggle dp_cfg_req_up.addr.offset [15:7] "logic dp_cfg_req_up.addr.offset[15:0]"
Toggle dp_cfg_req_up.addr.target [7:4] "logic dp_cfg_req_up.addr.target[15:0]"
Toggle dp_cfg_req_up.addr.target [10:10] "logic dp_cfg_req_up.addr.target[15:0]"
Toggle dp_cfg_req_up.addr.target [12:12] "logic dp_cfg_req_up.addr.target[15:0]"
Toggle dp_cfg_req_up.cfg_ignore_pipe_busy  "logic dp_cfg_req_up.cfg_ignore_pipe_busy"
Toggle dp_cfg_rsp_up.uid [3:3] "logic dp_cfg_rsp_up.uid[3:0]"
Toggle dp_cfg_rsp_up.err_slv_par  "logic dp_cfg_rsp_up.err_slv_par"
Toggle dp_cfg_req_down.addr.offset [15:7] "logic dp_cfg_req_down.addr.offset[15:0]"
Toggle dp_cfg_req_down.addr.target [7:4] "logic dp_cfg_req_down.addr.target[15:0]"
Toggle dp_cfg_req_down.addr.target [10:10] "logic dp_cfg_req_down.addr.target[15:0]"
Toggle dp_cfg_req_down.addr.target [12:12] "logic dp_cfg_req_down.addr.target[15:0]"
Toggle dp_cfg_req_down.addr.node [1:1] "logic dp_cfg_req_down.addr.node[3:0]"
Toggle dp_cfg_req_down.cfg_ignore_pipe_busy  "logic dp_cfg_req_down.cfg_ignore_pipe_busy"
Toggle dp_cfg_rsp_down.uid [3:3] "logic dp_cfg_rsp_down.uid[3:0]"
Toggle dp_cfg_rsp_down.err_slv_par  "logic dp_cfg_rsp_down.err_slv_par"
Toggle dp_alarm_up_v  "logic dp_alarm_up_v"
Toggle dp_alarm_up_ready  "logic dp_alarm_up_ready"
Toggle dp_alarm_up_data.rid [7:0] "logic dp_alarm_up_data.rid[7:0]"
Toggle dp_alarm_up_data.rtype [1:0] "logic dp_alarm_up_data.rtype[1:0]"
Toggle dp_alarm_up_data.msix_map [2:0] "logic dp_alarm_up_data.msix_map[2:0]"
Toggle dp_alarm_up_data.cls [1:0] "logic dp_alarm_up_data.cls[1:0]"
Toggle dp_alarm_up_data.aid [5:0] "logic dp_alarm_up_data.aid[5:0]"
Toggle dp_alarm_up_data.unit [3:0] "logic dp_alarm_up_data.unit[3:0]"
Toggle dp_alarm_down_v  "logic dp_alarm_down_v"
Toggle dp_alarm_down_ready  "logic dp_alarm_down_ready"
Toggle dp_alarm_down_data.rid [7:0] "logic dp_alarm_down_data.rid[7:0]"
Toggle dp_alarm_down_data.rtype [1:0] "logic dp_alarm_down_data.rtype[1:0]"
Toggle dp_alarm_down_data.msix_map [2:0] "logic dp_alarm_down_data.msix_map[2:0]"
Toggle dp_alarm_down_data.cls [1:0] "logic dp_alarm_down_data.cls[1:0]"
Toggle dp_alarm_down_data.aid [5:0] "logic dp_alarm_down_data.aid[5:0]"
Toggle dp_alarm_down_data.unit [3:0] "logic dp_alarm_down_data.unit[3:0]"
Toggle dp_LV_TM_rf  "logic dp_LV_TM_rf"
Toggle dp_LV_WRSTN_rf  "logic dp_LV_WRSTN_rf"
Toggle dp_LV_WRCK_rf  "logic dp_LV_WRCK_rf"
Toggle dp_LV_WSI_rf  "logic dp_LV_WSI_rf"
Toggle dp_LV_UpdateWR_rf  "logic dp_LV_UpdateWR_rf"
Toggle dp_LV_ShiftWR_rf  "logic dp_LV_ShiftWR_rf"
Toggle dp_LV_CaptureWR_rf  "logic dp_LV_CaptureWR_rf"
Toggle dp_LV_SelectWIR_rf  "logic dp_LV_SelectWIR_rf"
Toggle dp_LV_EnableWR_rf  "logic dp_LV_EnableWR_rf"
Toggle dp_LV_WSO_rf  "logic dp_LV_WSO_rf"
Toggle dp_LV_AuxEn_rf  "logic dp_LV_AuxEn_rf"
Toggle dp_LV_AuxOut_rf  "logic dp_LV_AuxOut_rf"
Toggle dp_LV_TM_sram  "logic dp_LV_TM_sram"
Toggle dp_LV_WRSTN_sram  "logic dp_LV_WRSTN_sram"
Toggle dp_LV_WRCK_sram  "logic dp_LV_WRCK_sram"
Toggle dp_LV_WSI_sram  "logic dp_LV_WSI_sram"
Toggle dp_LV_UpdateWR_sram  "logic dp_LV_UpdateWR_sram"
Toggle dp_LV_ShiftWR_sram  "logic dp_LV_ShiftWR_sram"
Toggle dp_LV_CaptureWR_sram  "logic dp_LV_CaptureWR_sram"
Toggle dp_LV_SelectWIR_sram  "logic dp_LV_SelectWIR_sram"
Toggle dp_LV_EnableWR_sram  "logic dp_LV_EnableWR_sram"
Toggle dp_LV_WSO_sram  "logic dp_LV_WSO_sram"
Toggle dp_LV_AuxEn_sram  "logic dp_LV_AuxEn_sram"
Toggle dp_LV_AuxOut_sram  "logic dp_LV_AuxOut_sram"
Toggle fary_ffuse_rf_trim [5:0] "logic fary_ffuse_rf_trim[5:0]"
Toggle fary_ffuse_ssa_trim [19:0] "logic fary_ffuse_ssa_trim[19:0]"
Toggle repair_fuses_dp.ssa.dir_nxthp.row_addr1_0 [8:0] "logic repair_fuses_dp.ssa.dir_nxthp.row_addr1_0[8:0]"
Toggle repair_fuses_dp.ssa.dir_nxthp.row_en1_0  "logic repair_fuses_dp.ssa.dir_nxthp.row_en1_0"
Toggle repair_fuses_dp.ssa.dir_nxthp.row_addr0_0 [8:0] "logic repair_fuses_dp.ssa.dir_nxthp.row_addr0_0[8:0]"
Toggle repair_fuses_dp.ssa.dir_nxthp.row_en0_0  "logic repair_fuses_dp.ssa.dir_nxthp.row_en0_0"
Toggle repair_fuses_dp.ssa.dir_nxthp.col_addr_0 [3:0] "logic repair_fuses_dp.ssa.dir_nxthp.col_addr_0[3:0]"
Toggle repair_fuses_dp.ssa.dir_nxthp.col_en_0  "logic repair_fuses_dp.ssa.dir_nxthp.col_en_0"
Toggle repair_fuses_dp.rf.replay_tp.col_addr_0 [3:0] "logic repair_fuses_dp.rf.replay_tp.col_addr_0[3:0]"
Toggle repair_fuses_dp.rf.replay_tp.col_en_0  "logic repair_fuses_dp.rf.replay_tp.col_en_0"
Toggle repair_fuses_dp.rf.replay_hp.col_addr_0 [3:0] "logic repair_fuses_dp.rf.replay_hp.col_addr_0[3:0]"
Toggle repair_fuses_dp.rf.replay_hp.col_en_0  "logic repair_fuses_dp.rf.replay_hp.col_en_0"
Toggle repair_fuses_dp.rf.replay_cnt.col_addr_0 [6:0] "logic repair_fuses_dp.rf.replay_cnt.col_addr_0[6:0]"
Toggle repair_fuses_dp.rf.replay_cnt.col_en_0  "logic repair_fuses_dp.rf.replay_cnt.col_en_0"
Toggle repair_fuses_dp.rf.dir_tp.col_addr_0 [3:0] "logic repair_fuses_dp.rf.dir_tp.col_addr_0[3:0]"
Toggle repair_fuses_dp.rf.dir_tp.col_en_0  "logic repair_fuses_dp.rf.dir_tp.col_en_0"
Toggle repair_fuses_dp.rf.dir_hp.col_addr_0 [3:0] "logic repair_fuses_dp.rf.dir_hp.col_addr_0[3:0]"
Toggle repair_fuses_dp.rf.dir_hp.col_en_0  "logic repair_fuses_dp.rf.dir_hp.col_en_0"
Toggle repair_fuses_dp.rf.dir_cnt.col_addr_0 [6:0] "logic repair_fuses_dp.rf.dir_cnt.col_addr_0[6:0]"
Toggle repair_fuses_dp.rf.dir_cnt.col_en_0  "logic repair_fuses_dp.rf.dir_cnt.col_en_0"
Toggle fdfx_lbist_test_mode  "logic fdfx_lbist_test_mode"
Toggle fdfx_sync_rst  "logic fdfx_sync_rst"
Toggle fscan_mode  "logic fscan_mode"
Toggle fscan_rstbypen  "logic fscan_rstbypen"
Toggle fscan_byprst_b  "logic fscan_byprst_b"
Toggle fscan_ram_wrdis_b  "logic fscan_ram_wrdis_b"
Toggle fscan_ram_rddis_b  "logic fscan_ram_rddis_b"
Toggle fscan_ram_odis_b  "logic fscan_ram_odis_b"
Toggle fscan_ram_awt_mode  "logic fscan_ram_awt_mode"
Toggle fscan_ram_awt_ren  "logic fscan_ram_awt_ren"
Toggle fscan_ram_awt_wen  "logic fscan_ram_awt_wen"
Toggle fscan_ram_bypsel  "logic fscan_ram_bypsel"
Toggle fscan_ram_init_val  "logic fscan_ram_init_val"
Toggle fscan_ram_init_en  "logic fscan_ram_init_en"
Toggle fsta_dfxact_afd  "logic fsta_dfxact_afd"
Toggle fsta_afd_en  "logic fsta_afd_en"
Toggle aary_mbist_diag_done [1:0] "logic aary_mbist_diag_done[1:0]"
