INSTANCE: hqm_core_tb_top.u_hqm_core.i_hqm_core_core.i_hqm_master.i_hqm_master_core.i_sys2cfg
Toggle paddr_f [1:0] "logic paddr_f[31:0]"
Toggle cfg_req_addr_nxt.offset [15:14] "logic cfg_req_addr_nxt.offset[15:0]"
Toggle cfg_req_addr_nxt.target [7:7] "logic cfg_req_addr_nxt.target[15:0]"
Toggle cfg_req_addr_nxt.target [12:12] "logic cfg_req_addr_nxt.target[15:0]"
Toggle cfg_req_addr_f.offset [15:14] "logic cfg_req_addr_f.offset[15:0]"
Toggle cfg_req_addr_f.target [7:7] "logic cfg_req_addr_f.target[15:0]"
Toggle cfg_req_addr_f.target [12:12] "logic cfg_req_addr_f.target[15:0]"
Toggle cfg_req_up_read_f  "logic cfg_req_up_read_f"
Toggle cfg_req_up_read_f_nc  "logic cfg_req_up_read_f_nc"
Toggle cfg_req_up_nc.addr.offset [15:0] "logic cfg_req_up_nc.addr.offset[15:0]"
Toggle cfg_req_up_nc.addr.target [15:0] "logic cfg_req_up_nc.addr.target[15:0]"
Toggle cfg_req_up_nc.addr.node [3:0] "logic cfg_req_up_nc.addr.node[3:0]"
Toggle cfg_req_up_nc.addr.mode [1:0] "logic cfg_req_up_nc.addr.mode[1:0]"
Toggle cfg_req_up_nc.addr_par  "logic cfg_req_up_nc.addr_par"
Toggle err_cfg_req_up_miss_nxt  "logic err_cfg_req_up_miss_nxt"
Toggle err_cfg_req_up_miss_f  "logic err_cfg_req_up_miss_f"
Toggle cfg_rsp_up_f.err_slv_par  "logic cfg_rsp_up_f.err_slv_par"
Toggle err_cfg_req_up_unsol_nxt  "logic err_cfg_req_up_unsol_nxt"
Toggle err_cfg_req_up_unsol_f  "logic err_cfg_req_up_unsol_f"
Toggle err_cfg_rsp_up_rdata_par_nxt  "logic err_cfg_rsp_up_rdata_par_nxt"
Toggle err_rdata_par_f  "logic err_rdata_par_f"
Toggle err_cfg_protocol_nxt  "logic err_cfg_protocol_nxt"
Toggle err_cfg_protocol_f  "logic err_cfg_protocol_f"
Toggle err_slv_par_nxt  "logic err_slv_par_nxt"
Toggle err_slv_par_f  "logic err_slv_par_f"
Toggle downcount_nxt [19:9] "logic downcount_nxt[19:0]"
Toggle downcount_f [19:9] "logic downcount_f[19:0]"
Toggle cfg_rsp_internal_f.rdata [14:9] "logic cfg_rsp_internal_f.rdata[31:0]"
Toggle cfg_rsp_internal_f.rdata [30:25] "logic cfg_rsp_internal_f.rdata[31:0]"
Toggle cfg_rsp_internal_f.err_slv_par  "logic cfg_rsp_internal_f.err_slv_par"
Toggle cfg_rsp_internal_f.err  "logic cfg_rsp_internal_f.err"
