INSTANCE: hqm_core_tb_top.u_hqm_core.i_hqm_core_core.i_hqm_master.i_hqm_master_core.i_sys2cfg
Toggle inj_par_err_rdata  "logic inj_par_err_rdata"
Toggle inj_par_err_wdata  "logic inj_par_err_wdata"
Toggle inj_par_err_addr  "logic inj_par_err_addr"
Toggle err_timeout  "logic err_timeout"
Toggle err_cfg_protocol  "logic err_cfg_protocol"
Toggle err_cfg_req_up_miss  "logic err_cfg_req_up_miss"
Toggle err_slv_par  "logic err_slv_par"
Toggle err_rdata_par  "logic err_rdata_par"
Toggle paddr [1:0] "logic paddr[31:0]"
Toggle pslverr  "logic pslverr"
Toggle cfg_req_internal.wdata [28:0] "logic cfg_req_internal.wdata[31:0]"
Toggle cfg_req_internal.addr.offset [15:0] "logic cfg_req_internal.addr.offset[15:0]"
Toggle cfg_req_internal.addr.target [0:0] "logic cfg_req_internal.addr.target[15:0]"
Toggle cfg_req_internal.addr.target [7:2] "logic cfg_req_internal.addr.target[15:0]"
Toggle cfg_req_internal.addr.target [14:9] "logic cfg_req_internal.addr.target[15:0]"
Toggle cfg_req_internal.addr.node [2:2] "logic cfg_req_internal.addr.node[3:0]"
Toggle cfg_req_internal.addr.mode [0:0] "logic cfg_req_internal.addr.mode[1:0]"
Toggle cfg_req_internal.user.bcast  "logic cfg_req_internal.user.bcast"
Toggle cfg_rsp_internal.rdata [14:9] "logic cfg_rsp_internal.rdata[31:0]"
Toggle cfg_rsp_internal.rdata [30:25] "logic cfg_rsp_internal.rdata[31:0]"
Toggle cfg_rsp_internal.err_slv_par  "logic cfg_rsp_internal.err_slv_par"
Toggle cfg_rsp_internal.err  "logic cfg_rsp_internal.err"
Toggle cfg_req_down.addr.offset [15:14] "logic cfg_req_down.addr.offset[15:0]"
Toggle cfg_req_down.addr.target [7:7] "logic cfg_req_down.addr.target[15:0]"
Toggle cfg_req_down.addr.target [12:12] "logic cfg_req_down.addr.target[15:0]"
Toggle cfg_req_up_read  "logic cfg_req_up_read"
Toggle cfg_req_up.addr.offset [15:0] "logic cfg_req_up.addr.offset[15:0]"
Toggle cfg_req_up.addr.mode [1:0] "logic cfg_req_up.addr.mode[1:0]"
Toggle cfg_req_up.addr_par  "logic cfg_req_up.addr_par"
