INSTANCE: hqm_core_tb_top.u_hqm_core.par_hqm_nalb_pipe.i_hqm_nalb_pipe.i_hqm_nalb_pipe_core
Toggle nalb_cfg_req_up.addr.offset [15:7] "logic nalb_cfg_req_up.addr.offset[15:0]"
Toggle nalb_cfg_req_up.addr.target [7:5] "logic nalb_cfg_req_up.addr.target[15:0]"
Toggle nalb_cfg_req_up.addr.target [12:12] "logic nalb_cfg_req_up.addr.target[15:0]"
Toggle nalb_cfg_req_up.cfg_ignore_pipe_busy  "logic nalb_cfg_req_up.cfg_ignore_pipe_busy"
Toggle nalb_cfg_rsp_up.uid [3:2] "logic nalb_cfg_rsp_up.uid[3:0]"
Toggle nalb_cfg_rsp_up.err_slv_par  "logic nalb_cfg_rsp_up.err_slv_par"
Toggle nalb_cfg_req_down.addr.offset [15:7] "logic nalb_cfg_req_down.addr.offset[15:0]"
Toggle nalb_cfg_req_down.addr.target [7:4] "logic nalb_cfg_req_down.addr.target[15:0]"
Toggle nalb_cfg_req_down.addr.target [12:12] "logic nalb_cfg_req_down.addr.target[15:0]"
Toggle nalb_cfg_req_down.cfg_ignore_pipe_busy  "logic nalb_cfg_req_down.cfg_ignore_pipe_busy"
Toggle nalb_cfg_rsp_down.uid [3:3] "logic nalb_cfg_rsp_down.uid[3:0]"
Toggle nalb_cfg_rsp_down.err_slv_par  "logic nalb_cfg_rsp_down.err_slv_par"
Toggle nalb_alarm_up_v  "logic nalb_alarm_up_v"
Toggle nalb_alarm_up_ready  "logic nalb_alarm_up_ready"
Toggle nalb_alarm_up_data.rid [7:0] "logic nalb_alarm_up_data.rid[7:0]"
Toggle nalb_alarm_up_data.rtype [1:0] "logic nalb_alarm_up_data.rtype[1:0]"
Toggle nalb_alarm_up_data.msix_map [2:0] "logic nalb_alarm_up_data.msix_map[2:0]"
Toggle nalb_alarm_up_data.cls [1:0] "logic nalb_alarm_up_data.cls[1:0]"
Toggle nalb_alarm_up_data.aid [5:0] "logic nalb_alarm_up_data.aid[5:0]"
Toggle nalb_alarm_up_data.unit [3:0] "logic nalb_alarm_up_data.unit[3:0]"
Toggle nalb_alarm_down_v  "logic nalb_alarm_down_v"
Toggle nalb_alarm_down_ready  "logic nalb_alarm_down_ready"
Toggle nalb_alarm_down_data.rid [7:0] "logic nalb_alarm_down_data.rid[7:0]"
Toggle nalb_alarm_down_data.rtype [1:0] "logic nalb_alarm_down_data.rtype[1:0]"
Toggle nalb_alarm_down_data.msix_map [2:0] "logic nalb_alarm_down_data.msix_map[2:0]"
Toggle nalb_alarm_down_data.cls [1:0] "logic nalb_alarm_down_data.cls[1:0]"
Toggle nalb_alarm_down_data.aid [5:0] "logic nalb_alarm_down_data.aid[5:0]"
Toggle nalb_alarm_down_data.unit [3:0] "logic nalb_alarm_down_data.unit[3:0]"
Toggle nalb_LV_TM_rf  "logic nalb_LV_TM_rf"
Toggle nalb_LV_WRSTN_rf  "logic nalb_LV_WRSTN_rf"
Toggle nalb_LV_WRCK_rf  "logic nalb_LV_WRCK_rf"
Toggle nalb_LV_WSI_rf  "logic nalb_LV_WSI_rf"
Toggle nalb_LV_UpdateWR_rf  "logic nalb_LV_UpdateWR_rf"
Toggle nalb_LV_ShiftWR_rf  "logic nalb_LV_ShiftWR_rf"
Toggle nalb_LV_CaptureWR_rf  "logic nalb_LV_CaptureWR_rf"
Toggle nalb_LV_SelectWIR_rf  "logic nalb_LV_SelectWIR_rf"
Toggle nalb_LV_EnableWR_rf  "logic nalb_LV_EnableWR_rf"
Toggle nalb_LV_WSO_rf  "logic nalb_LV_WSO_rf"
Toggle nalb_LV_AuxEn_rf  "logic nalb_LV_AuxEn_rf"
Toggle nalb_LV_AuxOut_rf  "logic nalb_LV_AuxOut_rf"
Toggle nalb_LV_TM_sram  "logic nalb_LV_TM_sram"
Toggle nalb_LV_WRSTN_sram  "logic nalb_LV_WRSTN_sram"
Toggle nalb_LV_WRCK_sram  "logic nalb_LV_WRCK_sram"
Toggle nalb_LV_WSI_sram  "logic nalb_LV_WSI_sram"
Toggle nalb_LV_UpdateWR_sram  "logic nalb_LV_UpdateWR_sram"
Toggle nalb_LV_ShiftWR_sram  "logic nalb_LV_ShiftWR_sram"
Toggle nalb_LV_CaptureWR_sram  "logic nalb_LV_CaptureWR_sram"
Toggle nalb_LV_SelectWIR_sram  "logic nalb_LV_SelectWIR_sram"
Toggle nalb_LV_EnableWR_sram  "logic nalb_LV_EnableWR_sram"
Toggle nalb_LV_WSO_sram  "logic nalb_LV_WSO_sram"
Toggle nalb_LV_AuxEn_sram  "logic nalb_LV_AuxEn_sram"
Toggle nalb_LV_AuxOut_sram  "logic nalb_LV_AuxOut_sram"
Toggle fary_ffuse_rf_trim [5:0] "logic fary_ffuse_rf_trim[5:0]"
Toggle fary_ffuse_ssa_trim [19:0] "logic fary_ffuse_ssa_trim[19:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_addr1_3 [8:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.row_addr1_3[8:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_en1_3  "logic repair_fuses_nalb.ssa.nalb_nxthp.row_en1_3"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_addr0_3 [8:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.row_addr0_3[8:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_en0_3  "logic repair_fuses_nalb.ssa.nalb_nxthp.row_en0_3"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.col_addr_3 [2:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.col_addr_3[2:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.col_en_3  "logic repair_fuses_nalb.ssa.nalb_nxthp.col_en_3"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_addr1_2 [8:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.row_addr1_2[8:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_en1_2  "logic repair_fuses_nalb.ssa.nalb_nxthp.row_en1_2"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_addr0_2 [8:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.row_addr0_2[8:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_en0_2  "logic repair_fuses_nalb.ssa.nalb_nxthp.row_en0_2"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.col_addr_2 [2:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.col_addr_2[2:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.col_en_2  "logic repair_fuses_nalb.ssa.nalb_nxthp.col_en_2"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_addr1_1 [8:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.row_addr1_1[8:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_en1_1  "logic repair_fuses_nalb.ssa.nalb_nxthp.row_en1_1"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_addr0_1 [8:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.row_addr0_1[8:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_en0_1  "logic repair_fuses_nalb.ssa.nalb_nxthp.row_en0_1"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.col_addr_1 [2:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.col_addr_1[2:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.col_en_1  "logic repair_fuses_nalb.ssa.nalb_nxthp.col_en_1"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_addr1_0 [8:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.row_addr1_0[8:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_en1_0  "logic repair_fuses_nalb.ssa.nalb_nxthp.row_en1_0"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_addr0_0 [8:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.row_addr0_0[8:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.row_en0_0  "logic repair_fuses_nalb.ssa.nalb_nxthp.row_en0_0"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.col_addr_0 [2:0] "logic repair_fuses_nalb.ssa.nalb_nxthp.col_addr_0[2:0]"
Toggle repair_fuses_nalb.ssa.nalb_nxthp.col_en_0  "logic repair_fuses_nalb.ssa.nalb_nxthp.col_en_0"
Toggle repair_fuses_nalb.rf.atq_tp.col_addr_0 [3:0] "logic repair_fuses_nalb.rf.atq_tp.col_addr_0[3:0]"
Toggle repair_fuses_nalb.rf.atq_tp.col_en_0  "logic repair_fuses_nalb.rf.atq_tp.col_en_0"
Toggle repair_fuses_nalb.rf.atq_hp.col_addr_0 [3:0] "logic repair_fuses_nalb.rf.atq_hp.col_addr_0[3:0]"
Toggle repair_fuses_nalb.rf.atq_hp.col_en_0  "logic repair_fuses_nalb.rf.atq_hp.col_en_0"
Toggle repair_fuses_nalb.rf.atq_cnt.col_addr_0 [7:0] "logic repair_fuses_nalb.rf.atq_cnt.col_addr_0[7:0]"
Toggle repair_fuses_nalb.rf.atq_cnt.col_en_0  "logic repair_fuses_nalb.rf.atq_cnt.col_en_0"
Toggle repair_fuses_nalb.rf.replay_tp.col_addr_0 [3:0] "logic repair_fuses_nalb.rf.replay_tp.col_addr_0[3:0]"
Toggle repair_fuses_nalb.rf.replay_tp.col_en_0  "logic repair_fuses_nalb.rf.replay_tp.col_en_0"
Toggle repair_fuses_nalb.rf.replay_hp.col_addr_0 [3:0] "logic repair_fuses_nalb.rf.replay_hp.col_addr_0[3:0]"
Toggle repair_fuses_nalb.rf.replay_hp.col_en_0  "logic repair_fuses_nalb.rf.replay_hp.col_en_0"
Toggle repair_fuses_nalb.rf.replay_cnt.col_addr_0 [7:0] "logic repair_fuses_nalb.rf.replay_cnt.col_addr_0[7:0]"
Toggle repair_fuses_nalb.rf.replay_cnt.col_en_0  "logic repair_fuses_nalb.rf.replay_cnt.col_en_0"
Toggle repair_fuses_nalb.rf.nalb_tp.col_addr_0 [3:0] "logic repair_fuses_nalb.rf.nalb_tp.col_addr_0[3:0]"
Toggle repair_fuses_nalb.rf.nalb_tp.col_en_0  "logic repair_fuses_nalb.rf.nalb_tp.col_en_0"
Toggle repair_fuses_nalb.rf.nalb_hp.col_addr_0 [3:0] "logic repair_fuses_nalb.rf.nalb_hp.col_addr_0[3:0]"
Toggle repair_fuses_nalb.rf.nalb_hp.col_en_0  "logic repair_fuses_nalb.rf.nalb_hp.col_en_0"
Toggle repair_fuses_nalb.rf.nalb_cnt.col_addr_0 [7:0] "logic repair_fuses_nalb.rf.nalb_cnt.col_addr_0[7:0]"
Toggle repair_fuses_nalb.rf.nalb_cnt.col_en_0  "logic repair_fuses_nalb.rf.nalb_cnt.col_en_0"
Toggle fdfx_lbist_test_mode  "logic fdfx_lbist_test_mode"
Toggle fdfx_sync_rst  "logic fdfx_sync_rst"
Toggle fscan_mode  "logic fscan_mode"
Toggle fscan_rstbypen  "logic fscan_rstbypen"
Toggle fscan_byprst_b  "logic fscan_byprst_b"
Toggle fscan_ram_wrdis_b  "logic fscan_ram_wrdis_b"
Toggle fscan_ram_rddis_b  "logic fscan_ram_rddis_b"
Toggle fscan_ram_odis_b  "logic fscan_ram_odis_b"
Toggle fscan_ram_awt_mode  "logic fscan_ram_awt_mode"
Toggle fscan_ram_awt_ren  "logic fscan_ram_awt_ren"
Toggle fscan_ram_awt_wen  "logic fscan_ram_awt_wen"
Toggle fscan_ram_bypsel  "logic fscan_ram_bypsel"
Toggle fscan_ram_init_val  "logic fscan_ram_init_val"
Toggle fscan_ram_init_en  "logic fscan_ram_init_en"
Toggle fsta_dfxact_afd  "logic fsta_dfxact_afd"
Toggle fsta_afd_en  "logic fsta_afd_en"
Toggle aary_mbist_diag_done [1:0] "logic aary_mbist_diag_done[1:0]"
