# Filename: default_package.yaml
#<MODEL> Main run directory
#<BASE>    <MODEL>/target/<dut>/<facet>/aceroot/results/DC/
#<BLOCK> run block name
#If you want to change the file name use
#<path_to_file>/<org_file_name> <new_file_name>
#
#Global: copy to the top signoff directory
#unit/partition/fc copy to the block directory
#
global:
    required:

    optional:
        - '<BASE>/*/collateral/timing_common/clock_procs*.tcl'
        - '<BASE>/*/collateral/timing_common/global_cross_clk_exceptions*.tcl'
        - '<BASE>/*/collateral/timing_common/global_cross_clk_groups*.tcl'
        - '<BASE>/*/collateral/timing_nominal/global_clock_params.tcl'
        - '<BASE>/*/collateral/timing_nominal/clock_uncertainty*.tcl'
        - '<BASE>/*/collateral/timing_nominal/clock_uncertainty*.tcl.gz'
        - '<BASE>/*/collateral/timing_nomxlt/global_clock_params.tcl'
        - '<BASE>/*/collateral/timing_nomxlt/clock_uncertainty*.tcl'
        - '<BASE>/config/dc/scripts/dfx_setup.tcl'
        - '<BASE>/fe2be_signoff_report_????_??_??_??_??_??.html'
        - '<BASE>/fe2be_signoff_report_????_??_??_??_??_??.xml'
        - '<BASE>/fe2be_signoff_report_????_??_??_??_??_??.win.html'
        - '<BASE>/fe2be_signoff_report_????_??_??_??_??_??.db.xml'
        - '<BASE>/fe2be_signoff_report_????_??_??_??_??_??_caliber.xml'
        - '<BASE>/fe2be_signoff_report_????_??_??_??_??_??_caliber.wide.xml'
        - '<BASE>/*/collateral/rtl/*_upf.cfg'

fc:
    required:
    optional:

unit:
    required:
        - '<BASE>/<BLOCK>/collateral/rtl/rtl_list_2stage.tcl'
        - '<BASE>/<BLOCK>/collateral/rtl/<BLOCK>_cfg.sv'
        - '<BASE>/<BLOCK>/syn/scripts/block_setup.tcl'
    optional:
        - '<BASE>/<BLOCK>/collateral/rtl/rtl_list.tcl'
        - '<BASE>/<BLOCK>/collateral/rtl/hip_list.tcl'
        - '<BASE>/<BLOCK>/collateral/rtl/bam_list.tcl'
        - '<BASE>/<BLOCK>/collateral/rtl/*.upf'
        - '<BASE>/<BLOCK>/collateral/rtl/<BLOCK>.upf'
        - '<BASE>/<BLOCK>/collateral/rtl/*.lst'
        - '<BASE>/<BLOCK>/collateral/rtl/*.list'
        - '<BASE>/<BLOCK>/collateral/rtl/*.upf.txt'
        - '<BASE>/<BLOCK>/collateral/rtl/*.config'
        - '<BASE>/<BLOCK>/collateral/rtl/*_upf*.tcl'
        - '<BASE>/<BLOCK>/collateral/rtl/*_srsn.tcl'
        - '<BASE>/<BLOCK>/collateral/rtl/*_iso_pins.tcl'
        - '<BASE>/<BLOCK>/collateral/dft/*_scan_waivers.tcl'
        - '<BASE>/<BLOCK>/syn/outputs/rtl_files_used.tar.gz'
        - '<BASE>/<BLOCK>/syn/inputs/<BLOCK>_internal_exceptions.tcl'
        - '<BASE>/<BLOCK>/collateral/rtl/<BLOCK>.rtl_gen_exceptions.tcl'
        - '<BASE>/<BLOCK>/collateral/timing_common/<BLOCK>_clocks*.tcl'
        - '<BASE>/<BLOCK>/syn/scripts/<BLOCK>_scan_config*.tcl'
        - '<BASE>/<BLOCK>/syn/outputs/*.svf'
        - '<BASE>/<BLOCK>/syn/outputs/*.vsdc'
        - '<BASE>/<BLOCK>/syn/outputs/<BLOCK>.syn_final.sdc'
        - '<BASE>/<BLOCK>/syn/outputs/<BLOCK>.syn_final.spef.gz'
        - '<BASE>/<BLOCK>/syn_caliber/report/<BLOCK>.analog_pins.lst'
        - '<BASE>/<BLOCK>/syn_caliber/report/<BLOCK>.analog_nets.lst'
        - '<BASE>/<BLOCK>/syn/reports/<BLOCK>.syn_final.resources'
        - '<BASE>/<BLOCK>/syn/logs/<BLOCK>.compile.change_names.log'
        - '<BASE>/<BLOCK>/syn/logs/<BLOCK>.syn_final.change_names.log'
        - '<BASE>/<BLOCK>/syn/logs/<BLOCK>.constraints.change_names.log'
        - '<MODEL>/target/collage/source/<BLOCK>/v95/<BLOCK>.v'
        - '<BASE>/<BLOCK>/collateral/rtl/*_upf*.cfg'
        - '<BASE>/<BLOCK>/fev/outputs/lp_power_data.rpt <BLOCK>_lp_power_data.rpt'
        - '<BASE>/<BLOCK>/fev/reports/fev_delseq*.xml'

partition:
    required:
    optional:
