#TSA_START_TAG#
#WARNING: content between TSA_START_TAG and TSA_END_TAG is auto-generated by TSA. Do not modify it!!!
#  TSA == Tool Setup Admin 
#  Below data is configured via 'tsa_finalized' and 'tsa_block_setup_caliber'.
#  To view the %toolConfig_tools data run below commands
#    >> ToolConfig.pl show_tool_info tsa_block_setup_caliber -1c -CUST <CUST> -1c-
#    >> ToolConfig.pl show_tool_info tsa_finalized -1c -CUST <CUST> -1c-

if {! [info exists G_ADDITIONAL_LINK_LIBRARIES]} {set G_ADDITIONAL_LINK_LIBRARIES [list]}
set G_VT_TYPE(default) ln
setvar G_DESIGN_NAME sbendpoint
setvar G_LIBRARY_TYPE e05


# START COMMON settings (or $ToolConfig_tools{tsa_block_setup_caliber}{TCLspec}{common}) 
setvar G_ENABLE_AOCVM "0"
setvar G_PRESERVE_ADDITIONAL_LINK_LIBRARIES "1"

# END COMMON settings

# START STDLIB_TYPE=e05 : LIB_VARIANT=ARRAY(0x10dd440) settings
# (or $ToolConfig_tools{tsa_block_setup_caliber}{TCLspec}{e05}{ARRAY(0x10dd440)})

# END STDLIB_TYPE=e05 : LIB_VARIANT=ARRAY(0x10dd440) settings
#TSA_END_TAG#


setvar G_CORNER_NAME_TYPE "tttt_v065_t100_max+MAX"

# scale factor for library to convert undimensioned constraints, 
# implicitly defined in ns, to library units.
set G_NS 1000

# ns period of the side_clk and agent_clk inputs to the endpoint
set EP_SIDE_CLK_PERIOD  3.33
set EP_AGENT_CLK_PERIOD 3.33

# Guardband (reduce) clock period by this ratio
# i.e. real period = target period * EP_CLK_GUARDBAND
set EP_CLK_GUARDBAND 0.80

# 0.1ns clock transition
set EP_CLK_TRANS [expr 0.1 * $G_NS]

# 5% period for clock uncertainty
set EP_CLK_UNCER_RATIO 0.05

# input|output delay as ratio of clock period
set EP_INPUT_DELAY   0.35
set EP_OUTPUT_DELAY  0.35
set EP_RELAXED_DELAY 0.05
set EP_STRAP_DELAY   0.35

set  G_INSERT_CLOCK_GATING 1
if {${G_LIBRARY_TYPE} == "d04"} {
   set G_MAX_ROUTING_LAYER "m8"
   set G_MIN_ROUTING_LAYER "m0"
}
set G_VISA_APPLY_CLOCK_STAMPING 1
set clk_period      [expr $EP_SIDE_CLK_PERIOD * $G_NS * $EP_CLK_GUARDBAND]
set clk_waveform    [list 0 [expr $clk_period * 0.5]]

create_clock -period $clk_period [get_ports side_clk]  -waveform $clk_waveform -name side_clk

set clk_period      [expr $EP_AGENT_CLK_PERIOD * $G_NS * $EP_CLK_GUARDBAND]
set clk_waveform    [list 0 [expr $clk_period * 0.5]]

create_clock -period $clk_period [get_ports agent_clk] -waveform $clk_waveform -name agent_clk