#!/bin/csh -f


cd $IP_ROOT/scripts

echo "#\!/bin/csh -f" > $IP_ROOT/scripts/ttemp1


foreach i (`grep "sh " run_all_configs | awk '{print $2}' | sed -e 's/\// /g' | awk '{print $NF}'`)
   awk '/cd /,/ace -cc/' $i  | grep -v ace  >> $IP_ROOT/scripts/ttemp1
   echo "cd tools/lint/"   >> $IP_ROOT/scripts/ttemp1
   echo "source RUN_LINTRA"   >> $IP_ROOT/scripts/ttemp1
   echo "mv lintra.rpt lintra.rpt.$i"      >> $IP_ROOT/scripts/ttemp1
   echo "cd ../../scripts"                 >> $IP_ROOT/scripts/ttemp1

   echo "cd ../tools/spyglass/"   >> $IP_ROOT/scripts/ttemp1
   ##echo "spyglass -f ./dfxsecure_plugin.spp"           >> $IP_ROOT/scripts/ttemp1
   echo "source README"           >> $IP_ROOT/scripts/ttemp1
   echo "mv SPYGLASS_WDIR/spyglass_reports/moresimple.rpt moresimple.rpt.$i"           >> $IP_ROOT/scripts/ttemp1
   echo "cd ../../scripts"                 >> $IP_ROOT/scripts/ttemp1
   echo ""  >> $IP_ROOT/scripts/ttemp1
end

chmod +x $IP_ROOT/scripts/ttemp1

cd $IP_ROOT
source  $IP_ROOT/scripts/ttemp1
